<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Str;

/**
 * Operator-friendly wrapper around Laravel's built-in `artisan down` /
 * `artisan up` with Jackpot branding + sensible defaults baked in.
 *
 *   php artisan jackpot:maintenance on       # enable, print bypass URL
 *   php artisan jackpot:maintenance off      # disable
 *   php artisan jackpot:maintenance status   # is it currently on?
 *
 * What this adds on top of vanilla `artisan down`:
 *   • Always renders `resources/views/errors/maintenance.blade.php` so visitors
 *     see the branded splash instead of Laravel's default "503 Service Unavailable".
 *   • Auto-generates a bypass secret each time and prints the URL operators
 *     need to set a cookie that exempts them from the maintenance wall.
 *   • Sets `Retry-After: 60` + a 60s meta refresh (matches the view).
 *
 * When maintenance is active, Laravel serves the pre-rendered HTML without
 * booting the full framework — so static assets (logo, favicon) served by the
 * web server still load, but any route that goes through PHP is blocked.
 *
 * @see \App\Console\Commands\MaintenanceCommand::handle()
 * @see resources/views/errors/maintenance.blade.php
 * @see docs/operations/MAINTENANCE_MODE.md
 */
class MaintenanceCommand extends Command
{
    protected $signature = 'jackpot:maintenance
                            {action : on | off | status}
                            {--secret= : Override the auto-generated bypass secret (on)}
                            {--retry=60 : Retry-After header value in seconds (on)}';

    protected $description = 'Put the Jackpot app into / out of branded maintenance mode';

    public function handle(): int
    {
        $action = strtolower((string) $this->argument('action'));

        return match ($action) {
            'on', 'enable', 'down' => $this->enable(),
            'off', 'disable', 'up' => $this->disable(),
            'status', 'state' => $this->status(),
            default => $this->bail("Unknown action '{$action}'. Use: on | off | status"),
        };
    }

    private function enable(): int
    {
        if ($this->isDown()) {
            $this->warn('Maintenance mode is already ON.');
            $this->printBypassHint();

            return 0;
        }

        // Bypass secret lets operators continue to use the site normally.
        // We regenerate on every `on` so an old secret leaked in Slack / a
        // terminal screenshot can't be used against the next maintenance window.
        $secret = (string) $this->option('secret') ?: Str::random(32);
        $retry = (int) $this->option('retry') ?: 60;

        $this->info('Enabling maintenance mode…');

        $exitCode = Artisan::call('down', [
            '--render' => 'errors.maintenance',
            '--retry' => $retry,
            '--refresh' => $retry,
            '--secret' => $secret,
            '--status' => 503,
        ], $this->getOutput());

        if ($exitCode !== 0) {
            $this->error('artisan down failed.');

            return $exitCode;
        }

        $this->newLine();
        $this->line('<fg=green>✓ Maintenance mode is ON.</> Visitors see the branded splash.');
        $this->newLine();
        $this->printBypassUrl($secret);

        return 0;
    }

    private function disable(): int
    {
        if (! $this->isDown()) {
            $this->warn('Maintenance mode is already OFF.');

            return 0;
        }

        $this->info('Disabling maintenance mode…');
        $exit = Artisan::call('up', [], $this->getOutput());

        if ($exit === 0) {
            $this->newLine();
            $this->line('<fg=green>✓ Maintenance mode is OFF.</> Site is back online.');
        }

        return $exit;
    }

    private function status(): int
    {
        if ($this->isDown()) {
            $this->line('Maintenance mode: <fg=yellow;options=bold>ON</>');
            $this->printBypassHint();
        } else {
            $this->line('Maintenance mode: <fg=green;options=bold>OFF</>');
        }

        return 0;
    }

    private function isDown(): bool
    {
        return app()->isDownForMaintenance();
    }

    private function printBypassUrl(string $secret): void
    {
        // Hitting /<secret> once sets a signed cookie named `laravel_maintenance`
        // that exempts that browser from the maintenance wall. Lasts until
        // `artisan up` — or until cookie expiry — whichever comes first.
        $base = rtrim((string) config('app.url') ?: url('/'), '/');
        $this->line('  <fg=cyan>Bypass URL (opens site for your browser):</>');
        $this->line("  {$base}/{$secret}");
        $this->newLine();
        $this->line('  <fg=gray>Share carefully — anyone with this link can access the site during maintenance.</>');
    }

    private function printBypassHint(): void
    {
        $this->newLine();
        $this->line("  <fg=gray>Lost the bypass URL? Disable + re-enable to generate a new one:</>");
        $this->line("  <fg=gray>  php artisan jackpot:maintenance off && php artisan jackpot:maintenance on</>");
    }

    private function bail(string $message): int
    {
        $this->error($message);

        return 1;
    }
}
