<?php

namespace App\Services;

use App\Models\Asset;
use App\Models\Brand;
use App\Models\Category;
use App\Models\Tenant;
use App\Services\AI\Contracts\AIProviderInterface;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;

/**
 * AI Metadata Generation Service
 *
 * Generates AI metadata candidates for assets by analyzing images using AI provider abstraction.
 * Creates candidates in asset_metadata_candidates table with producer='ai'.
 *
 * Critical Principles:
 * - Only processes fields with ai_eligible = true
 * - Only processes fields enabled for asset's category
 * - Structured candidates: select/multiselect fields with options (tags field has no options — handled via tag inference)
 * - Creates candidates (not suggestions) - suggestions are generated by AiMetadataSuggestionJob
 * - Never blocks uploads on failure
 * - Tracks costs accurately
 * - Provider-agnostic: Uses AIProviderInterface, not specific providers
 */
class AiMetadataGenerationService
{
    protected AIProviderInterface $provider;

    protected string $defaultModel;

    protected MetadataVisibilityResolver $visibilityResolver;

    protected TenantBucketService $bucketService;

    /** Minimum confidence (0–1) for structured fields and free-form tags from Vision JSON. */
    protected float $minConfidenceMetadata;

    /**
     * Create a new service instance.
     *
     * @param  AIProviderInterface|null  $provider  Provider instance (resolved from container if not provided)
     * @param  MetadataVisibilityResolver|null  $visibilityResolver  Visibility resolver (resolved from container if not provided)
     * @param  TenantBucketService|null  $bucketService  Bucket service for S3 fetch (resolved from container if not provided)
     */
    public function __construct(?AIProviderInterface $provider = null, ?MetadataVisibilityResolver $visibilityResolver = null, ?TenantBucketService $bucketService = null)
    {
        $this->provider = $provider ?? app(AIProviderInterface::class);
        $this->visibilityResolver = $visibilityResolver ?? app(MetadataVisibilityResolver::class);
        $this->bucketService = $bucketService ?? app(TenantBucketService::class);

        $modelConfig = config('ai.models.gpt-4o-mini', []);
        $this->defaultModel = $modelConfig['model_name'] ?? 'gpt-4o-mini';
        $this->minConfidenceMetadata = (float) config('ai.metadata_tagging.min_confidence', 0.90);
    }

    protected function getTaggingMinConfidence(): float
    {
        $v = $this->minConfidenceMetadata;
        if ($v < 0.5) {
            return 0.5;
        }
        if ($v > 0.99) {
            return 0.99;
        }

        return $v;
    }

    /**
     * Generate AI metadata candidates for an asset.
     *
     * @param  bool  $isManualRerun  From {@see AiMetadataGenerationJob} — allows tag inference even if Tags were previously approved.
     * @return array Results: candidates_created, tags_created, tag_inference_attempted, ai_tag_inference_status, ai_tag_inference_detail, tag_parse_stats, cost, fields_processed, tokens_in, tokens_out, model
     *
     * @throws \Exception If API call fails (caller should handle gracefully)
     */
    public function generateMetadata(Asset $asset, bool $isManualRerun = false): array
    {
        // Structured fields (select/multiselect with options). Tags field has no options — excluded here.
        $fields = $this->getEligibleFields($asset);

        // Tags are free-form (asset_tag_candidates). Run inference when the Tags field is AI-enabled
        // for this category even if no structured fields qualify — otherwise executions/deliverables often
        // skip the vision call entirely and never get AI tags.
        // Upload-time "Apply AI Tagging" sets _skip_ai_tagging — must not create tag candidates (same vision call can still fill structured fields).
        // Manual rerun: {@see AiMetadataGenerationJob} clears _skip_ai_tagging and ignores approved Tags so vision can run again.
        $tagInferenceDesired = $this->tagInferenceDesired($asset, $isManualRerun);
        $skipAiTaggingUpload = (bool) (($asset->metadata ?? [])['_skip_ai_tagging'] ?? false);
        $tagsInference = $tagInferenceDesired && ! $skipAiTaggingUpload;

        if (empty($fields) && ! $tagsInference) {
            Log::info('[AiMetadataGenerationService] No eligible fields and tag inference off', [
                'asset_id' => $asset->id,
            ]);

            return [
                'candidates_created' => 0,
                'tags_created' => 0,
                'tag_inference_attempted' => false,
                'ai_tag_inference_status' => 'vision_skipped_no_inputs',
                'ai_tag_inference_detail' => null,
                'tag_parse_stats' => null,
                'cost' => 0.0,
                'fields_processed' => [],
                'tokens_in' => 0,
                'tokens_out' => 0,
            ];
        }

        // Build prompt (structured + tags, or tags-only)
        $prompt = ! empty($fields)
            ? $this->buildPrompt($asset, $fields)
            : $this->buildPromptTagsOnly($asset);

        // Fetch image bytes internally via S3/IAM (never pass presigned URLs to AI providers)
        $imageBase64DataUrl = $this->fetchThumbnailAsBase64DataUrl($asset);
        if (! $imageBase64DataUrl) {
            Log::error('[AiMetadataGenerationService] AI image fetch failed before provider call', [
                'asset_id' => $asset->id,
                'thumbnail_status' => $asset->thumbnail_status?->value ?? 'null',
            ]);
            throw new \Exception('AI image fetch failed before provider call');
        }

        // Call provider's image analysis method (passes base64 data URL, not S3 URL)
        $response = $this->provider->analyzeImage($imageBase64DataUrl, $prompt, [
            'model' => $this->defaultModel,
            'max_tokens' => 1000,
            'response_format' => ['type' => 'json_object'],
        ]);

        // Parse response (returns both candidates and tags from ONE Vision API call)
        $parsed = $this->parseResponse($response, $asset, $fields);
        $candidates = $parsed['candidates'] ?? [];
        $tags = $parsed['tags'] ?? [];
        $tagParseStats = $parsed['tag_parse_stats'] ?? null;

        // Create candidates in database
        $candidatesCreated = $this->createCandidates($asset, $candidates);

        // Tag candidates only when Tags is AI-eligible for this category, upload did not opt out, and no approved tag yet.
        $tagsCreated = $tagsInference ? $this->createTags($asset, $tags) : 0;

        // Calculate cost using provider's cost calculation
        $cost = $this->provider->calculateCost(
            $response['tokens_in'] ?? 0,
            $response['tokens_out'] ?? 0,
            $response['model'] ?? $this->defaultModel
        );

        Log::info('[AiMetadataGenerationService] Generated metadata and tags', [
            'asset_id' => $asset->id,
            'candidates_created' => $candidatesCreated,
            'tags_created' => $tagsCreated,
            'fields_processed' => array_keys($candidates),
            'cost' => $cost,
            'tokens_in' => $response['tokens_in'] ?? 0,
            'tokens_out' => $response['tokens_out'] ?? 0,
        ]);

        $tagInferenceAttempted = $tagsInference;

        [$aiTagInferenceStatus, $aiTagInferenceDetail] = $this->resolveAiTagInferenceOutcome(
            $tagsInference,
            $tagInferenceDesired,
            $skipAiTaggingUpload,
            $tagsCreated,
            $tagParseStats
        );

        return [
            'candidates_created' => $candidatesCreated,
            'tags_created' => $tagsCreated,
            'tag_inference_attempted' => $tagInferenceAttempted,
            'ai_tag_inference_status' => $aiTagInferenceStatus,
            'ai_tag_inference_detail' => $aiTagInferenceDetail,
            'tag_parse_stats' => $tagParseStats,
            'cost' => $cost,
            'fields_processed' => array_keys($candidates),
            'tokens_in' => $response['tokens_in'] ?? 0,
            'tokens_out' => $response['tokens_out'] ?? 0,
            'model' => $response['model'] ?? $this->defaultModel,
        ];
    }

    /**
     * Human/debug status for asset metadata: skipped vs attempted vs zero usable tags.
     *
     * @param  array<string, mixed>|null  $tagParseStats
     * @return array{0: string, 1: string|null}
     */
    protected function resolveAiTagInferenceOutcome(
        bool $tagsInference,
        bool $tagInferenceDesired,
        bool $skipAiTaggingUpload,
        int $tagsCreated,
        ?array $tagParseStats
    ): array {
        if (! $tagsInference) {
            if ($tagInferenceDesired && $skipAiTaggingUpload) {
                return ['skipped_upload_opt_out', null];
            }

            return ['skipped_tags_not_eligible', null];
        }

        if ($tagsCreated > 0) {
            return ['attempted_ok', null];
        }

        $raw = (int) ($tagParseStats['raw_tag_count'] ?? 0);
        if ($raw === 0) {
            return ['attempted_empty', 'empty_model'];
        }

        return ['attempted_empty', 'no_tags_passed_filters'];
    }

    /**
     * Build AI inference plan for an asset (read-only planning step).
     *
     * Determines which metadata fields need AI inference using deterministic DB logic.
     * This is a read-only planning step that does NOT call AI or write metadata.
     *
     * @return array Plan structure: ['fields' => [['key' => string, 'label' => string, 'type' => string, 'allowed_values' => array]]]
     */
    public function buildAiInferencePlan(Asset $asset): array
    {
        // Get category
        $categoryId = $asset->metadata['category_id'] ?? null;
        if (! $categoryId) {
            return ['fields' => []];
        }

        // Get ai_eligible fields that are select/multiselect
        $fields = DB::table('metadata_fields')
            ->where('ai_eligible', true)
            ->whereIn('type', ['select', 'multiselect'])
            ->where(function ($query) use ($asset) {
                $query->where('scope', 'system')
                    ->orWhere(function ($q) use ($asset) {
                        $q->where('tenant_id', $asset->tenant_id)
                            ->where('scope', '!=', 'system');
                    });
            })
            ->get();

        $planFields = [];
        foreach ($fields as $field) {
            // Check if field is enabled for category
            if (! $this->isFieldEnabledForCategory($asset, $field->id, $categoryId)) {
                continue;
            }

            // Check if field already has an approved value
            // If approved_at is not null, the field has an approved value and should be skipped
            $hasApprovedValue = DB::table('asset_metadata')
                ->where('asset_id', $asset->id)
                ->where('metadata_field_id', $field->id)
                ->whereNotNull('approved_at')
                ->exists();

            if ($hasApprovedValue) {
                continue;
            }

            // Get allowed_values (options)
            $allowedValues = DB::table('metadata_options')
                ->where('metadata_field_id', $field->id)
                ->pluck('value')
                ->toArray();

            if (empty($allowedValues)) {
                continue;
            }

            $planFields[] = [
                'key' => $field->key,
                'label' => $field->system_label ?? $field->key,
                'type' => $field->type,
                'allowed_values' => $allowedValues,
            ];
        }

        return [
            'fields' => $planFields,
        ];
    }

    /**
     * Get ai_eligible fields for asset's category.
     *
     * @return array Array of field definitions with options
     */
    protected function getEligibleFields(Asset $asset): array
    {
        // Get category
        $categoryId = $asset->metadata['category_id'] ?? null;
        if (! $categoryId) {
            return [];
        }

        // Get ai_eligible fields
        $fields = DB::table('metadata_fields')
            ->where('ai_eligible', true)
            ->whereIn('type', ['select', 'multiselect'])
            ->where(function ($query) use ($asset) {
                $query->where('scope', 'system')
                    ->orWhere(function ($q) use ($asset) {
                        $q->where('tenant_id', $asset->tenant_id)
                            ->where('scope', '!=', 'system');
                    });
            })
            ->get();

        $enabledFields = [];
        foreach ($fields as $field) {
            // Check if field is enabled for category
            if (! $this->isFieldEnabledForCategory($asset, $field->id, $categoryId)) {
                continue;
            }

            // Check if field already has an approved value
            // If approved_at is not null, the field has an approved value and should be skipped
            // This prevents unnecessary API calls for fields that already have values
            $hasApprovedValue = DB::table('asset_metadata')
                ->where('asset_id', $asset->id)
                ->where('metadata_field_id', $field->id)
                ->whereNotNull('approved_at')
                ->exists();

            if ($hasApprovedValue) {
                continue;
            }

            // Get options
            $options = DB::table('metadata_options')
                ->where('metadata_field_id', $field->id)
                ->pluck('value', 'system_label')
                ->toArray();

            if (empty($options)) {
                continue;
            }

            $enabledFields[] = [
                'key' => $field->key,
                'label' => $field->system_label ?? $field->key,
                'type' => $field->type,
                'options' => array_values($options),
                'description' => $field->description ?? null,
            ];
        }

        return $enabledFields;
    }

    /**
     * Whether the Tags field would qualify for AI tag inference (ignores upload-time _skip_ai_tagging).
     *
     * @param  bool  $ignoreApprovedTags  Manual rerun: allow new tag candidates even if Tags was previously approved.
     */
    protected function tagInferenceDesired(Asset $asset, bool $ignoreApprovedTags = false): bool
    {
        $categoryId = $asset->metadata['category_id'] ?? null;
        if (! $categoryId) {
            return false;
        }

        $field = DB::table('metadata_fields')
            ->where('key', 'tags')
            ->where('ai_eligible', true)
            ->whereIn('type', ['select', 'multiselect'])
            ->where(function ($query) use ($asset) {
                $query->where('scope', 'system')
                    ->orWhere(function ($q) use ($asset) {
                        $q->where('tenant_id', $asset->tenant_id)
                            ->where('scope', '!=', 'system');
                    });
            })
            ->first();

        if (! $field) {
            return false;
        }

        if (! $this->isFieldEnabledForCategory($asset, (int) $field->id, (int) $categoryId)) {
            return false;
        }

        if (! $ignoreApprovedTags) {
            $hasApprovedValue = DB::table('asset_metadata')
                ->where('asset_id', $asset->id)
                ->where('metadata_field_id', $field->id)
                ->whereNotNull('approved_at')
                ->exists();

            if ($hasApprovedValue) {
                return false;
            }
        }

        return true;
    }

    /**
     * Whether to run vision for free-form tags only (asset_tag_candidates).
     * True when the Tags field is AI-eligible and enabled for the category, with no approved value yet,
     * and the uploader did not opt out via _skip_ai_tagging.
     */
    protected function shouldRunTagInference(Asset $asset): bool
    {
        if (! empty(($asset->metadata ?? [])['_skip_ai_tagging'])) {
            return false;
        }

        return $this->tagInferenceDesired($asset, false);
    }

    /**
     * Check if field is enabled for category.
     *
     * CRITICAL: Uses MetadataVisibilityResolver to check tenant/brand/category-specific visibility.
     * This ensures AI suggestions respect category-specific field enablement settings.
     */
    protected function isFieldEnabledForCategory(Asset $asset, int $fieldId, int $categoryId): bool
    {
        $field = DB::table('metadata_fields')->where('id', $fieldId)->first();
        if (! $field) {
            return false;
        }

        // Get the category
        $category = \App\Models\Category::find($categoryId);
        if (! $category) {
            // Category doesn't exist - field is enabled by default
            return true;
        }

        // Get tenant for visibility check
        $tenant = \App\Models\Tenant::find($asset->tenant_id);
        if (! $tenant) {
            // Tenant doesn't exist - field is enabled by default
            return true;
        }

        // Use MetadataVisibilityResolver to check if field is visible for this category
        // This checks both system-level and tenant-level visibility overrides
        $fieldDefinition = [
            'field_id' => $fieldId,
            'key' => $field->key,
        ];

        return $this->visibilityResolver->isFieldVisible($fieldDefinition, $category, $tenant);
    }

    /**
     * Shared vision pipeline: same S3 fetch rules as AI metadata (no presigned URLs to providers).
     *
     * @return string|null Base64 data URL (data:image/webp;base64,...) or null on failure
     */
    public function fetchThumbnailForVisionAnalysis(Asset $asset): ?string
    {
        return $this->fetchThumbnailAsBase64DataUrl($asset);
    }

    /**
     * Fetch medium thumbnail from S3/MinIO and return as base64 data URL.
     * Uses IAM role (worker) or configured credentials; never exposes S3 URLs to AI providers.
     *
     * @return string|null Base64 data URL (data:image/webp;base64,...) or null on failure
     */
    protected function fetchThumbnailAsBase64DataUrl(Asset $asset): ?string
    {
        $thumbnailPath = $this->resolveThumbnailPath($asset);
        if (! $thumbnailPath) {
            return null;
        }

        $bucket = $asset->storageBucket;
        if (! $bucket) {
            Log::warning('[AiMetadataGenerationService] Asset missing storage bucket', [
                'asset_id' => $asset->id,
            ]);

            return null;
        }

        try {
            $contents = $this->bucketService->getObjectContents($bucket, $thumbnailPath);
        } catch (\Throwable $e) {
            Log::error('[AiMetadataGenerationService] AI image fetch failed before provider call', [
                'asset_id' => $asset->id,
                'thumbnail_path' => $thumbnailPath,
                'bucket' => $bucket->name,
                'error' => $e->getMessage(),
            ]);

            return null;
        }

        if (strlen($contents) === 0) {
            Log::error('[AiMetadataGenerationService] AI image fetch failed: empty file', [
                'asset_id' => $asset->id,
                'thumbnail_path' => $thumbnailPath,
            ]);

            return null;
        }

        $base64 = base64_encode($contents);
        $mimeType = $this->inferMimeTypeFromPath($thumbnailPath);

        return "data:{$mimeType};base64,{$base64}";
    }

    /**
     * Resolve thumbnail path from asset metadata (for THUMB_MEDIUM / THUMB_PREVIEW variant resolution).
     *
     * @return string|null S3 key path (assets/... or temp/uploads/...) or null if not available
     */
    protected function resolveThumbnailPath(Asset $asset): ?string
    {
        $metadata = $asset->metadata ?? [];

        if (isset($metadata['thumbnails']['medium']['path'])) {
            $path = $metadata['thumbnails']['medium']['path'];
            if (str_starts_with($path, 'assets/') || str_starts_with($path, 'temp/uploads/')) {
                if (str_starts_with($path, 'temp/uploads/') && $asset->thumbnail_status !== \App\Enums\ThumbnailStatus::COMPLETED) {
                    return null;
                }

                return $path;
            }
        }

        if (isset($metadata['preview_thumbnails']['preview']['path'])) {
            return $metadata['preview_thumbnails']['preview']['path'];
        }

        return null;
    }

    /**
     * Infer MIME type from file extension.
     */
    protected function inferMimeTypeFromPath(string $path): string
    {
        $ext = strtolower(pathinfo($path, PATHINFO_EXTENSION));
        $map = [
            'webp' => 'image/webp',
            'jpg' => 'image/jpeg',
            'jpeg' => 'image/jpeg',
            'png' => 'image/png',
            'gif' => 'image/gif',
        ];

        return $map[$ext] ?? 'image/webp';
    }

    /**
     * Build structured prompt for AI provider.
     *
     * Uses ONE Vision API call to infer both structured field values and general descriptive tags.
     *
     * @param  array  $fields  Field definitions
     * @return string Prompt text
     */
    protected function buildPrompt(Asset $asset, array $fields): string
    {
        $fieldsJson = [];
        foreach ($fields as $field) {
            $fieldsJson[$field['key']] = [
                'label' => $field['label'],
                'type' => $field['type'],
                'allowed_values' => $field['options'],
                'description' => $field['description'] ?? "The {$field['label']} for this image",
            ];
        }

        $min = $this->getTaggingMinConfidence();
        $minStr = number_format($min, 2, '.', '');
        $ctx = $this->buildPromptContextBlock($asset, 'full');

        $prompt = "Analyze this image and provide both structured metadata field values and searchable tags.\n\n";

        $prompt .= $ctx;

        $prompt .= "STRUCTURED FIELDS:\n";
        $prompt .= "For each field below, select ONLY from the provided allowed values.\n";
        $prompt .= "Fields to analyze:\n";
        $prompt .= json_encode($fieldsJson, JSON_PRETTY_PRINT)."\n\n";

        $prompt .= "GENERAL TAGS (for search & discovery):\n";
        $prompt .= "Provide concise tags (1–3 words each) that help users find this asset in the library.\n";
        $prompt .= "Prefer concrete, searchable terms: subject, setting, style, mood, notable people or objects, production type when visible.\n";
        $prompt .= "Do not use the tag \"photo shoot\" or \"photoshoot\" — category already covers photography; tag specific subjects, people, objects, and visible settings instead.\n";
        $prompt .= "Use lowercase; use short phrases where helpful (e.g. \"on location\", \"model\", \"product\"); avoid punctuation.\n";
        $prompt .= "Do not repeat the category name unless it adds specificity.\n\n";

        $prompt .= "REQUIREMENTS:\n";
        $prompt .= "- Only return fields/tags where confidence is >= {$minStr} ({$minStr} = 0–1 scale)\n";
        $prompt .= "- Include confidence score for each value/tag\n";
        $prompt .= "- If confidence is below {$minStr}, omit that field/tag\n";
        $prompt .= "- Field values must exactly match one of the allowed_values\n";
        $prompt .= "- Tags must be lowercase; short phrases (spaces allowed) are OK\n";
        $prompt .= "- Return JSON format with both 'fields' and 'tags' sections:\n";
        $prompt .= "{\n";
        $prompt .= "  \"fields\": {\n";
        $prompt .= "    \"photo_type\": {\"value\": \"studio\", \"confidence\": 0.94}\n";
        $prompt .= "  },\n";
        $prompt .= "  \"tags\": []\n";
        $prompt .= "}\n";
        $prompt .= "(Populate \"tags\" with objects {\"value\": string, \"confidence\": number} only for terms at or above {$minStr}; use [] if none qualify.)\n\n";
        $prompt .= 'Response:';

        return $prompt;
    }

    /**
     * Tags-only prompt when no structured fields qualify (e.g. executions with only Tags AI-enabled).
     */
    protected function buildPromptTagsOnly(Asset $asset): string
    {
        $min = $this->getTaggingMinConfidence();
        $minStr = number_format($min, 2, '.', '');
        $ctx = $this->buildPromptContextBlock($asset, 'tags');

        $prompt = "Analyze this image and generate SEARCHABLE TAGS for a digital asset management system.\n\n";

        $prompt .= $ctx;

        $prompt .= "TAGGING RULES (STRICT):\n";
        $prompt .= "- Never use \"photo shoot\" or \"photoshoot\" as a tag — redundant in photography libraries; use specific visible subjects instead\n";
        $prompt .= "- Only include VISUALLY VERIFIABLE elements present in the image\n";
        $prompt .= "- Do NOT infer intent, meaning, or marketing context\n";
        $prompt .= "- Avoid abstract terms (e.g. \"modern\", \"professional\", \"aesthetic\", \"branding\")\n";
        $prompt .= "- Avoid subjective descriptors (e.g. \"beautiful\", \"clean\", \"bold\")\n";
        $prompt .= "- Prefer concrete nouns and simple descriptors\n";
        $prompt .= "- Tags should help someone FIND this exact image\n\n";

        $prompt .= "ALLOWED TAG TYPES:\n";
        $prompt .= "- Objects (e.g. \"person\", \"car\", \"fishing rod\")\n";
        $prompt .= "- People (e.g. \"man\", \"woman\", \"child\", \"group\")\n";
        $prompt .= "- Setting/location (e.g. \"lake\", \"studio\", \"outdoor\")\n";
        $prompt .= "- Activity (only if clearly visible, e.g. \"fishing\", \"casting\")\n";
        $prompt .= "- Asset type (e.g. \"logo\", \"product\", \"catalog page\")\n";
        $prompt .= "- Composition (e.g. \"close up\", \"wide shot\")\n\n";

        $prompt .= "NORMALIZATION RULES:\n";
        $prompt .= "- Use lowercase\n";
        $prompt .= "- 1–3 words max per tag\n";
        $prompt .= "- Do NOT include synonyms or duplicates (e.g. choose \"man\" OR \"person\", not both)\n";
        $prompt .= "- Do NOT repeat the category unless it adds specificity\n\n";

        $prompt .= "CONFIDENCE:\n";
        $prompt .= "- Confidence represents visual certainty (not guess or interpretation)\n";
        $prompt .= "- Only include tags where confidence >= {$minStr}\n";
        $prompt .= "- Be conservative — if unsure, exclude the tag\n\n";

        $prompt .= "OUTPUT FORMAT:\n";
        $prompt .= "{\n";
        $prompt .= "  \"fields\": {},\n";
        $prompt .= "  \"tags\": [\n";
        $prompt .= "    {\"value\": \"example tag\", \"confidence\": 0.95}\n";
        $prompt .= "  ]\n";
        $prompt .= "}\n\n";

        $prompt .= "Return ONLY valid JSON. No explanation.\n";

        return $prompt;
    }


    /**
     * Category/brand context for vision prompts.
     *
     * @param  string  $mode  'full' — category hints for structured fields + tags (searchTagsHintForCategory).
     *                        'tags' — category/brand only plus strict visual-only instruction (no search hints).
     */
    protected function buildPromptContextBlock(Asset $asset, string $mode = 'full'): string
    {
        $lines = [];
        $meta = $asset->metadata ?? [];
        $categoryId = $meta['category_id'] ?? null;
        $category = null;
        if ($categoryId) {
            $category = Category::find($categoryId);
            if ($category && $category->name) {
                $lines[] = 'Library category: '.$category->name.'.';
            }
        }
        if ($asset->brand_id) {
            $brand = Brand::find($asset->brand_id);
            if ($brand && $brand->name) {
                $lines[] = 'Brand: '.$brand->name.'.';
            }
        }
        if ($categoryId && ! $category) {
            $lines[] = 'Library category id: '.$categoryId.'.';
        }

        if ($mode === 'tags') {
            $lines[] = 'Only include concrete, visually verifiable elements such as objects, people, environments, and actions. Do not infer style, mood, or intent.';
        } else {
            $hint = $this->searchTagsHintForCategory($category);
            if ($hint !== '') {
                $lines[] = $hint;
            }
        }

        if (! empty($lines)) {
            return "CONTEXT:\n".implode("\n", $lines)."\n\n";
        }

        return '';
    }

    /**
     * Extra guidance for common categories (e.g. photography) so tags are useful in search.
     */
    protected function searchTagsHintForCategory(?Category $category): string
    {
        if (! $category || ! $category->name) {
            return '';
        }
        $name = strtolower($category->name);
        if (str_contains($name, 'photo')) {
            return 'For photography structured fields, use shoot type (studio, on location, editorial), roles, product, composition where applicable. For free-form tags, do not use \"photo shoot\" — prefer specific subjects, people, and objects visible in the image.';
        }

        return 'Include terms users might search for: subject, setting, style, mood, and notable objects or people when clearly visible.';
    }

    /**
     * Parse AI provider response into candidates and tags.
     *
     * Handles unified response with both 'fields' and 'tags' sections from ONE Vision API call.
     *
     * @param  array  $response  Provider response (from AIProviderInterface::analyzeImage)
     * @param  array  $fields  Field definitions
     * @return array ['candidates' => array, 'tags' => array] Candidates and tags ready for database insertion
     */
    protected function parseResponse(array $response, Asset $asset, array $fields): array
    {
        $text = $response['text'] ?? '';
        $candidates = [];
        $tags = [];
        $minConf = $this->getTaggingMinConfidence();
        $tagParseStats = [
            'raw_tag_count' => 0,
            'passed_confidence_count' => 0,
            'rejected_low_confidence_count' => 0,
        ];

        try {
            $data = json_decode($text, true);
            if (! is_array($data)) {
                Log::warning('[AiMetadataGenerationService] Invalid JSON response', [
                    'asset_id' => $asset->id,
                    'response' => $text,
                ]);

                return ['candidates' => [], 'tags' => [], 'tag_parse_stats' => $tagParseStats];
            }

            // Parse structured fields
            $fieldsData = $data['fields'] ?? [];
            if (is_array($fieldsData)) {
                foreach ($fieldsData as $fieldKey => $fieldData) {
                    if (! is_array($fieldData)) {
                        continue;
                    }

                    $value = $fieldData['value'] ?? null;
                    $confidence = $fieldData['confidence'] ?? null;

                    if (! is_numeric($confidence) || (float) $confidence < $minConf) {
                        Log::debug('[AiMetadataGenerationService] Low confidence field skipped', [
                            'asset_id' => $asset->id,
                            'field_key' => $fieldKey,
                            'confidence' => $confidence,
                            'min_confidence' => $minConf,
                        ]);

                        continue;
                    }

                    // Find field definition
                    $field = null;
                    foreach ($fields as $f) {
                        if ($f['key'] === $fieldKey) {
                            $field = $f;
                            break;
                        }
                    }

                    if (! $field) {
                        continue;
                    }

                    // Validate value is in allowed options
                    if (! $this->isValueAllowed($value, $field)) {
                        Log::debug('[AiMetadataGenerationService] Invalid value skipped', [
                            'asset_id' => $asset->id,
                            'field_key' => $fieldKey,
                            'value' => $value,
                        ]);

                        continue;
                    }

                    $candidates[$fieldKey] = [
                        'value' => $value,
                        'confidence' => (float) $confidence,
                    ];
                }
            }

            // Parse general tags
            $tagsData = $data['tags'] ?? [];
            if (is_array($tagsData)) {
                foreach ($tagsData as $tagData) {
                    if (! is_array($tagData)) {
                        // Handle case where tags might be simple strings
                        if (is_string($tagData)) {
                            $tagData = ['value' => $tagData, 'confidence' => $minConf];
                        } else {
                            continue;
                        }
                    }

                    $tagValue = $tagData['value'] ?? null;
                    $confidence = $tagData['confidence'] ?? null;

                    if (empty($tagValue) || ! is_string($tagValue)) {
                        continue;
                    }

                    $tagParseStats['raw_tag_count']++;

                    if (! is_numeric($confidence)) {
                        $tagParseStats['rejected_low_confidence_count']++;

                        continue;
                    }

                    if ((float) $confidence < $minConf) {
                        Log::debug('[AiMetadataGenerationService] Low confidence tag skipped', [
                            'asset_id' => $asset->id,
                            'tag' => $tagValue,
                            'confidence' => $confidence,
                            'min_confidence' => $minConf,
                        ]);
                        $tagParseStats['rejected_low_confidence_count']++;

                        continue;
                    }

                    // Normalize tag: lowercase, singular, no punctuation
                    $normalizedTag = $this->normalizeTag($tagValue);
                    if (empty($normalizedTag)) {
                        $tagParseStats['rejected_low_confidence_count']++;

                        continue;
                    }

                    if ($this->isRedundantTag($normalizedTag)) {
                        Log::debug('[AiMetadataGenerationService] Redundant tag skipped', [
                            'asset_id' => $asset->id,
                            'tag' => $normalizedTag,
                        ]);

                        continue;
                    }

                    $tagParseStats['passed_confidence_count']++;
                    $tags[] = [
                        'value' => $normalizedTag,
                        'confidence' => (float) $confidence,
                    ];
                }
            }
        } catch (\Exception $e) {
            Log::error('[AiMetadataGenerationService] Failed to parse response', [
                'asset_id' => $asset->id,
                'error' => $e->getMessage(),
                'response' => $text,
            ]);
        }

        return [
            'candidates' => $candidates,
            'tags' => $tags,
            'tag_parse_stats' => $tagParseStats,
        ];
    }

    /**
     * Normalize tag: lowercase, singular, no punctuation.
     *
     * @return string Normalized tag
     */
    protected function normalizeTag(string $tag): string
    {
        // Convert to lowercase
        $tag = strtolower(trim($tag));

        // Remove punctuation (keep alphanumeric and spaces)
        $tag = preg_replace('/[^a-z0-9\s]/', '', $tag);

        // Convert to singular (basic plural removal - could be enhanced)
        // Remove trailing 's' if word is plural (simple heuristic)
        if (strlen($tag) > 1 && substr($tag, -1) === 's' && substr($tag, -2, 1) !== 's') {
            $tag = substr($tag, 0, -1);
        }

        // Remove extra spaces and trim
        $tag = preg_replace('/\s+/', ' ', $tag);
        $tag = trim($tag);

        return $tag;
    }

    /**
     * Tags that duplicate category-level concepts and should never be stored (e.g. "photo shoot" in a DAM photography context).
     */
    protected function isRedundantTag(string $normalized): bool
    {
        $t = preg_replace('/\s+/', ' ', trim($normalized));
        $compact = str_replace(' ', '', $t);

        return $t === 'photo shoot' || strcasecmp($compact, 'photoshoot') === 0;
    }

    /**
     * Check if value is allowed (in field options).
     *
     * @param  mixed  $value
     * @param  array  $field  Field definition
     */
    protected function isValueAllowed($value, array $field): bool
    {
        $options = $field['options'] ?? [];

        if ($field['type'] === 'multiselect') {
            if (! is_array($value)) {
                return false;
            }
            // All values must be in options
            foreach ($value as $v) {
                if (! in_array($v, $options, true)) {
                    return false;
                }
            }

            return true;
        }

        // Single select
        return in_array($value, $options, true);
    }

    /**
     * Create metadata field candidates in asset_metadata_candidates table.
     *
     * Stores AI-generated field values as candidates (not approved data).
     * Candidates must be reviewed and approved before being applied to the asset.
     *
     * @param  array  $candidates  Array of field candidates: ['field_key' => ['value' => mixed, 'confidence' => float]]
     * @return int Number of candidates created
     */
    protected function createCandidates(Asset $asset, array $candidates): int
    {
        if (empty($candidates)) {
            return 0;
        }

        $created = 0;
        foreach ($candidates as $fieldKey => $candidateData) {
            // Get field ID
            $field = DB::table('metadata_fields')
                ->where('key', $fieldKey)
                ->where(function ($query) use ($asset) {
                    $query->where('scope', 'system')
                        ->orWhere(function ($q) use ($asset) {
                            $q->where('tenant_id', $asset->tenant_id)
                                ->where('scope', '!=', 'system');
                        });
                })
                ->first();

            if (! $field) {
                continue;
            }

            // Check if candidate already exists
            $existing = DB::table('asset_metadata_candidates')
                ->where('asset_id', $asset->id)
                ->where('metadata_field_id', $field->id)
                ->where('producer', 'ai')
                ->whereNull('resolved_at')
                ->whereNull('dismissed_at')
                ->first();

            if ($existing) {
                // Update existing candidate
                DB::table('asset_metadata_candidates')
                    ->where('id', $existing->id)
                    ->update([
                        'value_json' => json_encode($candidateData['value']),
                        'confidence' => $candidateData['confidence'],
                        'source' => 'ai',
                        'updated_at' => now(),
                    ]);
            } else {
                // Create new candidate
                DB::table('asset_metadata_candidates')->insert([
                    'asset_id' => $asset->id,
                    'metadata_field_id' => $field->id,
                    'value_json' => json_encode($candidateData['value']),
                    'confidence' => $candidateData['confidence'],
                    'source' => 'ai',
                    'producer' => 'ai',
                    'created_at' => now(),
                    'updated_at' => now(),
                ]);
            }

            $created++;
        }

        return $created;
    }

    /**
     * Create tag candidates in asset_tag_candidates table.
     *
     * Stores AI-generated tags as candidates (not approved data).
     * Tags must be reviewed and approved before being applied to the asset.
     *
     * @param  array  $tags  Array of ['value' => string, 'confidence' => float]
     * @return int Number of tag candidates created
     */
    protected function createTags(Asset $asset, array $tags): int
    {
        if (empty($tags)) {
            return 0;
        }

        $created = 0;
        $now = now();

        foreach ($tags as $tagData) {
            $tagValue = $tagData['value'] ?? null;
            $confidence = $tagData['confidence'] ?? null;

            if (empty($tagValue) || ! is_string($tagValue)) {
                continue;
            }

            // Phase J.2.1: Normalize tag and check if canonical form has been dismissed
            $tagNormalizationService = app(\App\Services\TagNormalizationService::class);
            $tenant = Tenant::find($asset->tenant_id);
            $canonicalTag = $tagNormalizationService->normalize($tagValue, $tenant);

            // Skip if normalization results in blocked/invalid tag
            if ($canonicalTag === null) {
                continue;
            }

            // Check if any candidate with this canonical form has been dismissed
            $allCandidates = DB::table('asset_tag_candidates')
                ->where('asset_id', $asset->id)
                ->where('producer', 'ai')
                ->whereNotNull('dismissed_at')
                ->get();

            $canonicalDismissed = false;
            foreach ($allCandidates as $dismissedCandidate) {
                $dismissedCanonical = $tagNormalizationService->normalize($dismissedCandidate->tag, $tenant);
                if ($dismissedCanonical === $canonicalTag) {
                    $canonicalDismissed = true;
                    break;
                }
            }

            if ($canonicalDismissed) {
                // Skip creating candidate for dismissed canonical tag
                continue;
            }

            // Check if candidate already exists (avoid duplicates)
            $existing = DB::table('asset_tag_candidates')
                ->where('asset_id', $asset->id)
                ->where('tag', $tagValue)
                ->where('producer', 'ai')
                ->whereNull('resolved_at')
                ->whereNull('dismissed_at')
                ->first();

            if ($existing) {
                // Update existing candidate with new confidence if higher
                if (is_numeric($confidence) && $confidence > ($existing->confidence ?? 0)) {
                    DB::table('asset_tag_candidates')
                        ->where('id', $existing->id)
                        ->update([
                            'confidence' => $confidence,
                            'updated_at' => $now,
                        ]);
                    $created++;
                }

                continue;
            }

            // Create new tag candidate (NOT approved - stored as candidate for review)
            DB::table('asset_tag_candidates')->insert([
                'asset_id' => $asset->id,
                'tag' => $tagValue,
                'source' => 'ai',
                'confidence' => is_numeric($confidence) ? $confidence : null,
                'producer' => 'ai',
                'created_at' => $now,
                'updated_at' => $now,
            ]);

            $created++;
        }

        return $created;
    }
}
