<?php

namespace App\Services;

use App\Enums\AITaskType;
use App\Models\AIAgentRun;
use App\Models\Asset;
use App\Models\Brand;
use App\Models\Category;
use App\Models\Tenant;
use App\Services\AI\Contracts\AIProviderInterface;
use App\Services\AI\Vision\AwsRekognitionVisionTagProvider;
use App\Services\AI\Vision\Contracts\VisionTagCandidateProvider;
use App\Services\AI\Vision\VisionTagCandidate;
use App\Services\AI\Vision\VisionTagCandidateResult;
use App\Services\BrandIntelligence\PdfBrandIntelligencePageRasterCatalog;
use App\Services\PlanService;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;

/**
 * AI Metadata Generation Service
 *
 * Generates AI metadata candidates for assets by analyzing images using AI provider abstraction.
 * Creates candidates in asset_metadata_candidates table with producer='ai'.
 *
 * Critical Principles:
 * - Only processes fields with ai_eligible = true
 * - Only processes fields enabled for asset's category
 * - Structured candidates: select/multiselect fields with options (tags field has no options — handled via tag inference)
 * - Creates candidates (not suggestions) - suggestions are generated by AiMetadataSuggestionJob
 * - Never blocks uploads on failure
 * - Tracks costs accurately
 * - Provider-agnostic: Uses AIProviderInterface, not specific providers
 */
class AiMetadataGenerationService
{
    /** Max words per AI vision tag after canonicalization (server-side). */
    protected const VISION_TAG_MAX_WORDS = 3;

    /**
     * Optional model output: silent asset family before tagging. Parsed for sanitation only — not persisted.
     *
     * @var list<string>
     */
    protected const VISION_DETECTED_ASSET_TYPES = [
        'brand_mark',
        'product_image',
        'product_render',
        'lifestyle_photo',
        'environment_photo',
        'people_photo',
        'graphic_design',
        'marketing_layout',
        'document',
        'presentation',
        'screen_capture',
        'video_still',
        'audio_asset',
        'font_asset',
        'source_file',
        'unknown',
    ];

    protected AIProviderInterface $provider;

    protected string $defaultModel;

    protected MetadataVisibilityResolver $visibilityResolver;

    protected TenantBucketService $bucketService;

    /** Optional vision tag candidate provider (e.g. AWS Rekognition). Resolved lazily so tests can override. */
    protected ?VisionTagCandidateProvider $visionTagProvider;

    /** Minimum confidence (0–1) for structured fields and free-form tags from Vision JSON. */
    protected float $minConfidenceMetadata;

    /**
     * Create a new service instance.
     *
     * @param  AIProviderInterface|null  $provider  Provider instance (resolved from container if not provided)
     * @param  MetadataVisibilityResolver|null  $visibilityResolver  Visibility resolver (resolved from container if not provided)
     * @param  TenantBucketService|null  $bucketService  Bucket service for S3 fetch (resolved from container if not provided)
     * @param  VisionTagCandidateProvider|null  $visionTagProvider  Optional explicit vision tag provider (Rekognition).
     *                                                              When omitted, the active provider is resolved from
     *                                                              {@see config('ai.metadata_tagging.vision_provider')}.
     */
    public function __construct(
        ?AIProviderInterface $provider = null,
        ?MetadataVisibilityResolver $visibilityResolver = null,
        ?TenantBucketService $bucketService = null,
        ?VisionTagCandidateProvider $visionTagProvider = null,
    ) {
        $this->provider = $provider ?? app(AIProviderInterface::class);
        $this->visibilityResolver = $visibilityResolver ?? app(MetadataVisibilityResolver::class);
        $this->bucketService = $bucketService ?? app(TenantBucketService::class);
        $this->visionTagProvider = $visionTagProvider;

        $modelConfig = config('ai.models.gpt-4o-mini', []);
        $this->defaultModel = $modelConfig['model_name'] ?? 'gpt-4o-mini';
        $this->minConfidenceMetadata = (float) config('ai.metadata_tagging.min_confidence', 0.90);
    }

    /**
     * Test seam: override the vision tag provider after construction.
     */
    public function setVisionTagProvider(?VisionTagCandidateProvider $provider): void
    {
        $this->visionTagProvider = $provider;
    }

    protected function getTaggingMinConfidence(): float
    {
        $v = $this->minConfidenceMetadata;
        if ($v < 0.5) {
            return 0.5;
        }
        if ($v > 0.99) {
            return 0.99;
        }

        return $v;
    }

    /**
     * Generate AI metadata candidates for an asset.
     *
     * @return array Results: candidates_created, tags_created, tag_inference_attempted, ai_tag_inference_status, ai_tag_inference_detail, tag_parse_stats, cost, fields_processed, tokens_in, tokens_out, model
     *
     * @throws \Exception If API call fails (caller should handle gracefully)
     */
    public function generateMetadata(Asset $asset): array
    {
        // Upload-time toggles: structured field suggestions vs tag candidates are independent in the UI.
        // _skip_ai_metadata: do not create asset_metadata_candidates (photo type, scene, etc.).
        // _skip_ai_tagging: do not create asset_tag_candidates (still one vision call when either runs).
        $skipAiMetadataUpload = (bool) (($asset->metadata ?? [])['_skip_ai_metadata'] ?? false);

        // Structured fields (select/multiselect with options). Tags field has no options — excluded here.
        $fields = $skipAiMetadataUpload ? [] : $this->getEligibleFields($asset);

        // Tags are free-form (asset_tag_candidates). Run inference when the Tags field is AI-enabled
        // for this category even if no structured fields qualify — otherwise executions/deliverables often
        // skip the vision call entirely and never get AI tags.
        // Upload-time "Apply AI Tagging" sets _skip_ai_tagging — must not create tag candidates (same vision call can still fill structured fields).
        // Manual rerun: {@see AiMetadataGenerationJob} clears _skip_ai_tagging so vision can run again.
        $tagInferenceDesired = $this->tagInferenceDesired($asset);
        $skipAiTaggingUpload = (bool) (($asset->metadata ?? [])['_skip_ai_tagging'] ?? false);
        $tagsInference = $tagInferenceDesired && ! $skipAiTaggingUpload;

        if (empty($fields) && ! $tagsInference) {
            Log::info('[AiMetadataGenerationService] No eligible fields and tag inference off', [
                'asset_id' => $asset->id,
                'user_id' => $asset->user_id,
                'tenant_id' => $asset->tenant_id,
                'brand_id' => $asset->brand_id,
                'category_id' => $asset->metadata['category_id'] ?? null,
                'tag_inference_desired' => $tagInferenceDesired,
                'skip_ai_tagging_upload' => $skipAiTaggingUpload,
            ]);

            return [
                'candidates_created' => 0,
                'tags_created' => 0,
                'tag_inference_attempted' => false,
                'ai_tag_inference_status' => 'vision_skipped_no_inputs',
                'ai_tag_inference_detail' => null,
                'tag_parse_stats' => null,
                'cost' => 0.0,
                'fields_processed' => [],
                'tokens_in' => 0,
                'tokens_out' => 0,
            ];
        }

        $category = null;
        $catId = $asset->metadata['category_id'] ?? null;
        if ($catId !== null && $catId !== '') {
            $category = Category::find($catId);
        }
        $lib = app(CategoryAiLibraryContextService::class)->buildForAsset($asset, $category);
        $libAddendum = (string) ($lib['prompt_addendum'] ?? '');

        // Image tag candidates can be generated by AWS Rekognition independently of OpenAI vision.
        // - 'aws_rekognition' (default): tags come from Rekognition; OpenAI vision handles ONLY structured fields.
        // - 'openai' (revert):           legacy combined OpenAI call returns both fields and tags.
        $visionProviderKey = $this->resolveVisionProviderKey();
        $useRekognitionForTags = $tagsInference && $visionProviderKey === AwsRekognitionVisionTagProvider::PROVIDER_KEY;
        $useOpenAiForTags = $tagsInference && ! $useRekognitionForTags;
        $needsOpenAiCall = ! empty($fields) || $useOpenAiForTags;

        $candidates = [];
        $tags = [];
        $tagParseStats = null;
        $openAiResponse = null;

        if ($needsOpenAiCall) {
            // Fields-only prompt when Rekognition handles tags; combined prompt for the legacy revert path.
            $prompt = $useOpenAiForTags
                ? (! empty($fields)
                    ? $this->buildPrompt($asset, $fields, $libAddendum)
                    : $this->buildPromptTagsOnly($asset, $libAddendum))
                : $this->buildPromptFieldsOnly($asset, $fields, $libAddendum);

            $imageBase64DataUrl = $this->fetchThumbnailAsBase64DataUrl($asset);
            if (! $imageBase64DataUrl) {
                Log::error('[AiMetadataGenerationService] AI image fetch failed before provider call', [
                    'asset_id' => $asset->id,
                    'thumbnail_status' => $asset->thumbnail_status?->value ?? 'null',
                ]);
                throw new \Exception('AI image fetch failed before provider call');
            }

            $analyzeOptions = [
                'model' => $this->defaultModel,
                'max_tokens' => 1000,
                'response_format' => ['type' => 'json_object'],
            ];
            if (! empty($lib['reference_image_data_urls']) && is_array($lib['reference_image_data_urls'])) {
                $analyzeOptions['reference_image_data_urls'] = $lib['reference_image_data_urls'];
            }

            $openAiResponse = $this->provider->analyzeImage($imageBase64DataUrl, $prompt, $analyzeOptions);

            $parsed = $this->parseResponse($openAiResponse, $asset, $fields);
            $candidates = $parsed['candidates'] ?? [];
            $tagParseStats = $parsed['tag_parse_stats'] ?? null;
            // When Rekognition owns tags, ignore any tags the OpenAI fields-only response might still emit.
            if ($useOpenAiForTags) {
                $tags = $parsed['tags'] ?? [];
            }
        }

        $rekognitionRunInfo = null;
        $fallbackOpenAi = null;
        if ($useRekognitionForTags) {
            $rekognitionRunInfo = $this->runRekognitionForTagCandidates($asset, $category);
            if ($rekognitionRunInfo !== null) {
                $tags = $rekognitionRunInfo['tags'];
                $tagParseStats = $this->mergeTagParseStats($tagParseStats, $rekognitionRunInfo['tag_parse_stats']);
            }
            $rekognitionFailed = $rekognitionRunInfo !== null && ! empty($rekognitionRunInfo['provider_failed']);
            $rekognitionMissing = $rekognitionRunInfo === null;
            if ((bool) config('ai.metadata_tagging.rekognition_fallback_to_openai', false)
                && ($rekognitionMissing || $rekognitionFailed)) {
                // Opt-in fallback: tags-only OpenAI vision when Rekognition is off/unavailable or failed non-retryably.
                Log::warning('[AiMetadataGenerationService] Falling back to OpenAI vision for tags after Rekognition skip/failure', [
                    'asset_id' => $asset->id,
                    'rekognition_missing' => $rekognitionMissing,
                    'rekognition_failed' => $rekognitionFailed,
                ]);
                $fallbackOpenAi = $this->runOpenAiTagsOnlyFallback($asset, $libAddendum, $lib);
                if ($fallbackOpenAi !== null) {
                    $tags = $fallbackOpenAi['tags'];
                    $tagParseStats = $this->mergeTagParseStats($tagParseStats, $fallbackOpenAi['tag_parse_stats']);
                }
            }
        }

        $candidatesCreated = $skipAiMetadataUpload ? 0 : $this->createCandidates($asset, $candidates);
        $tagsCreated = $tagsInference ? $this->createTags($asset, $this->capVisionTagCandidatesForPlan($asset, $tags)) : 0;

        $primaryOpenAiTokensIn = (int) ($openAiResponse['tokens_in'] ?? 0);
        $primaryOpenAiTokensOut = (int) ($openAiResponse['tokens_out'] ?? 0);
        $primaryOpenAiModel = $openAiResponse['model'] ?? $this->defaultModel;
        $primaryOpenAiCost = $openAiResponse !== null
            ? $this->provider->calculateCost($primaryOpenAiTokensIn, $primaryOpenAiTokensOut, $primaryOpenAiModel)
            : 0.0;

        $fallbackTokensIn = (int) ($fallbackOpenAi['tokens_in'] ?? 0);
        $fallbackTokensOut = (int) ($fallbackOpenAi['tokens_out'] ?? 0);
        $fallbackCost = (float) ($fallbackOpenAi['cost'] ?? 0.0);

        $openAiTokensIn = $primaryOpenAiTokensIn + $fallbackTokensIn;
        $openAiTokensOut = $primaryOpenAiTokensOut + $fallbackTokensOut;
        $openAiCost = $primaryOpenAiCost + $fallbackCost;
        $openAiModel = $primaryOpenAiModel;

        $rekognitionCost = (float) ($rekognitionRunInfo['cost'] ?? 0.0);
        $totalCost = $openAiCost + $rekognitionCost;

        $fieldsProcessedKeys = $skipAiMetadataUpload ? [] : array_keys($candidates);

        Log::info('[AiMetadataGenerationService] Generated metadata and tags', [
            'asset_id' => $asset->id,
            'vision_provider' => $visionProviderKey,
            'used_rekognition_for_tags' => $useRekognitionForTags,
            'candidates_created' => $candidatesCreated,
            'tags_created' => $tagsCreated,
            'fields_processed' => $fieldsProcessedKeys,
            'cost_total_usd' => $totalCost,
            'cost_openai_usd' => $openAiCost,
            'cost_rekognition_usd' => $rekognitionCost,
            'openai_tokens_in' => $openAiTokensIn,
            'openai_tokens_out' => $openAiTokensOut,
        ]);

        [$aiTagInferenceStatus, $aiTagInferenceDetail] = $this->resolveAiTagInferenceOutcome(
            $tagsInference,
            $tagInferenceDesired,
            $skipAiTaggingUpload,
            $tagsCreated,
            $tagParseStats,
            (is_array($rekognitionRunInfo) && ! empty($rekognitionRunInfo['provider_failed']))
                ? (string) ($rekognitionRunInfo['provider_failure_class'] ?? '')
                : null,
        );

        return [
            'candidates_created' => $candidatesCreated,
            'tags_created' => $tagsCreated,
            'tag_inference_attempted' => $tagsInference,
            'ai_tag_inference_status' => $aiTagInferenceStatus,
            'ai_tag_inference_detail' => $aiTagInferenceDetail,
            'tag_parse_stats' => $tagParseStats,
            'cost' => $totalCost,
            'fields_processed' => $fieldsProcessedKeys,
            'tokens_in' => $openAiTokensIn,
            'tokens_out' => $openAiTokensOut,
            'model' => $openAiModel,
            'vision_tag_provider' => $useRekognitionForTags
                ? AwsRekognitionVisionTagProvider::PROVIDER_KEY
                : ($useOpenAiForTags ? 'openai' : null),
            'rekognition_run' => $rekognitionRunInfo === null ? null : [
                'estimated_cost_usd' => $rekognitionRunInfo['cost'],
                'raw_label_count' => $rekognitionRunInfo['raw_label_count'],
                'accepted_count' => count($rekognitionRunInfo['tags']),
                'source_bucket' => $rekognitionRunInfo['source_bucket'],
                'source_key' => $rekognitionRunInfo['source_key'],
                'features' => $rekognitionRunInfo['features'],
                'provider_failed' => (bool) ($rekognitionRunInfo['provider_failed'] ?? false),
                'provider_failure_class' => $rekognitionRunInfo['provider_failure_class'] ?? null,
            ],
        ];
    }

    /**
     * Active vision tag provider key (config-driven; image tags only). 'aws_rekognition' or 'openai'.
     */
    protected function resolveVisionProviderKey(): string
    {
        $key = (string) config('ai.metadata_tagging.vision_provider', AwsRekognitionVisionTagProvider::PROVIDER_KEY);
        $key = strtolower(trim($key));
        if ($key === '' || ! in_array($key, [AwsRekognitionVisionTagProvider::PROVIDER_KEY, 'openai'], true)) {
            return AwsRekognitionVisionTagProvider::PROVIDER_KEY;
        }

        return $key;
    }

    /**
     * Run Rekognition DetectLabels and feed candidates through the same sanitizer/category-ban
     * pipeline used by the OpenAI vision path. Records an AIAgentRun + ai_usage row with
     * tokens=0 and unit_type=image (Rekognition is per-call billed).
     *
     * Returns null when Rekognition is disabled or the provider cannot be resolved
     * (OpenAI fields-only path still runs; caller may fall back to OpenAI tags if configured).
     * On non-retryable API failures returns an empty tag set with `provider_failed` set (distinct from null).
     *
     * @return array{
     *   tags: list<array{value: string, confidence: float}>,
     *   tag_parse_stats: array<string, int>,
     *   cost: float,
     *   raw_label_count: int,
     *   source_bucket: string,
     *   source_key: string,
     *   features: list<string>,
     *   provider_failed?: bool,
     *   provider_failure_class?: string,
     * }|null
     */
    protected function runRekognitionForTagCandidates(Asset $asset, ?Category $category): ?array
    {
        $provider = $this->resolveVisionTagProvider();
        if ($provider === null) {
            Log::warning('[AiMetadataGenerationService] Rekognition vision tag provider not available; skipping per-image tag detection.', [
                'asset_id' => $asset->id,
            ]);

            return null;
        }

        $agentRun = AIAgentRun::create([
            'agent_id' => 'metadata_image_tags_rekognition',
            'triggering_context' => 'tenant',
            'environment' => app()->environment(),
            'tenant_id' => $asset->tenant_id,
            'user_id' => null,
            'task_type' => AITaskType::ASSET_METADATA_GENERATION,
            'model_used' => AwsRekognitionVisionTagProvider::MODEL_KEY,
            'tokens_in' => 0,
            'tokens_out' => 0,
            'estimated_cost' => 0,
            'status' => 'failed',
            'started_at' => now(),
            'metadata' => [
                'asset_id' => $asset->id,
                'provider' => AwsRekognitionVisionTagProvider::PROVIDER_KEY,
                'capability' => 'vision_tagging',
                'cost_unit' => 'image',
                'category_id' => $category?->id,
                'category_slug' => $category?->slug,
            ],
        ]);

        try {
            $result = $provider->detectTagsForAsset($asset, $category);
        } catch (\Throwable $e) {
            $reason = $this->classifyRekognitionFailure($e);
            Log::error('[AiMetadataGenerationService] Rekognition vision tag detection failed', [
                'asset_id' => $asset->id,
                'tenant_id' => $asset->tenant_id,
                'brand_id' => $asset->brand_id,
                'category_id' => $category?->id,
                'provider' => AwsRekognitionVisionTagProvider::PROVIDER_KEY,
                'model' => AwsRekognitionVisionTagProvider::MODEL_KEY,
                'failure_class' => get_class($e),
                'failure_reason' => $reason,
                'error' => $e->getMessage(),
            ]);
            $agentRun->markAsFailed(sprintf('%s: %s', get_class($e), $e->getMessage()));

            // Throttling/server errors should bubble up so the queue worker can retry/back off.
            if ($reason === 'retryable') {
                throw $e;
            }

            // Non-retryable failure: return an empty run shape (not null) so callers can distinguish
            // "Rekognition never configured" (null) from "API failed" — metadata + UI can show the
            // real reason instead of mislabeling as `empty_model`, and OpenAI fallback can still run.
            $emptyStats = [
                'raw_tag_count' => 0,
                'passed_confidence_count' => 0,
                'rejected_low_confidence_count' => 0,
                'rejected_blocklist_count' => 0,
                'rejected_sanitizer_count' => 0,
                'rejected_duplicate_count' => 0,
            ];

            return [
                'tags' => [],
                'tag_parse_stats' => $emptyStats,
                'cost' => 0.0,
                'raw_label_count' => 0,
                'source_bucket' => '',
                'source_key' => '',
                'features' => ['GENERAL_LABELS'],
                'provider_failed' => true,
                'provider_failure_class' => class_basename($e),
            ];
        }

        $detectedAssetType = null;
        $seenCanonicalTags = [];
        $tags = [];
        $tagParseStats = [
            'raw_tag_count' => 0,
            'passed_confidence_count' => 0,
            'rejected_low_confidence_count' => 0,
            'rejected_blocklist_count' => 0,
            'rejected_sanitizer_count' => 0,
            'rejected_duplicate_count' => 0,
        ];
        $categoryVisionBanSet = $this->buildVisionTagCategoryBanSet($category);

        $minConf = $this->getTaggingMinConfidence();
        $rekognitionMin01 = max(0.0, min(1.0, ((float) ($result->usage['min_confidence'] ?? 70)) / 100.0));
        $effectiveMin = max($minConf, $rekognitionMin01);

        foreach ($result->candidates as $candidate) {
            /** @var VisionTagCandidate $candidate */
            $this->acceptVisionTagCandidate(
                (string) $asset->id,
                $candidate->value,
                $candidate->confidence,
                $effectiveMin,
                $tags,
                $tagParseStats,
                $detectedAssetType,
                $seenCanonicalTags,
                $categoryVisionBanSet
            );
        }

        $cost = (float) ($result->usage['estimated_cost_usd'] ?? 0.0);
        $rawLabelCount = is_array($result->rawResponse['Labels'] ?? null) ? count($result->rawResponse['Labels']) : 0;

        $agentRun->markAsSuccessful(0, 0, $cost, array_merge($agentRun->metadata ?? [], [
            'billing_type' => 'per_image',
            'unit_type' => $result->usage['unit_type'] ?? 'image',
            'unit_count' => $result->usage['unit_count'] ?? 1,
            'features' => $result->usage['features'] ?? ['GENERAL_LABELS'],
            'max_labels' => $result->usage['max_labels'] ?? null,
            'min_confidence' => $result->usage['min_confidence'] ?? null,
            'source' => $result->sourceType,
            'source_bucket' => $result->sourceBucket,
            'source_key' => $result->sourceKey,
            'source_mime' => $result->sourceMime,
            'source_asset_version_id' => $result->sourceAssetVersionId,
            'raw_label_count' => $rawLabelCount,
            'accepted_tag_count' => count($tags),
            'rejected_low_confidence_count' => $tagParseStats['rejected_low_confidence_count'],
            'rejected_sanitizer_count' => $tagParseStats['rejected_sanitizer_count'],
            'rejected_blocklist_count' => $tagParseStats['rejected_blocklist_count'],
            'rejected_duplicate_count' => $tagParseStats['rejected_duplicate_count'],
        ]));

        return [
            'tags' => $tags,
            'tag_parse_stats' => $tagParseStats,
            'cost' => $cost,
            'raw_label_count' => $rawLabelCount,
            'source_bucket' => $result->sourceBucket,
            'source_key' => $result->sourceKey,
            'features' => $result->usage['features'] ?? ['GENERAL_LABELS'],
        ];
    }

    /**
     * Resolve a Rekognition vision tag provider when the active config selects it.
     */
    protected function resolveVisionTagProvider(): ?VisionTagCandidateProvider
    {
        if ($this->visionTagProvider !== null) {
            return $this->visionTagProvider;
        }
        if (! (bool) config('ai.metadata_tagging.aws_rekognition.enabled', true)) {
            return null;
        }
        try {
            $this->visionTagProvider = app(AwsRekognitionVisionTagProvider::class);
        } catch (\Throwable $e) {
            Log::warning('[AiMetadataGenerationService] Could not resolve AwsRekognitionVisionTagProvider', [
                'error' => $e->getMessage(),
            ]);

            return null;
        }

        return $this->visionTagProvider;
    }

    /**
     * AWS error classification:
     *   - 'retryable' — throttling / 5xx / provisioned throughput; let queue retry/backoff
     *   - 'permanent' — invalid format / missing object / access denied; do not retry forever
     *   - 'unknown'   — anything else (treat as non-retryable from the tag pipeline's perspective)
     */
    protected function classifyRekognitionFailure(\Throwable $e): string
    {
        $class = class_basename(get_class($e));
        $retryable = ['ThrottlingException', 'ProvisionedThroughputExceededException', 'ServerException', 'InternalServerError'];
        if (in_array($class, $retryable, true)) {
            return 'retryable';
        }
        $permanent = [
            'InvalidS3ObjectException',
            'InvalidImageFormatException',
            'ImageTooLargeException',
            'AccessDeniedException',
            'InvalidParameterException',
        ];
        if (in_array($class, $permanent, true)) {
            return 'permanent';
        }

        return 'unknown';
    }

    /**
     * Optional fallback: when Rekognition fails non-retryably AND
     * `ai.metadata_tagging.rekognition_fallback_to_openai` is true, run a tags-only OpenAI vision
     * call so the asset still gets candidate tags. Same sanitizer/category-ban pipeline.
     *
     * @param  array<string, mixed>  $lib
     * @return array{
     *   tags: list<array{value: string, confidence: float}>,
     *   tag_parse_stats: array<string, int>,
     *   tokens_in: int,
     *   tokens_out: int,
     *   cost: float,
     * }|null
     */
    protected function runOpenAiTagsOnlyFallback(Asset $asset, string $libraryAddendum, array $lib): ?array
    {
        try {
            $imageBase64DataUrl = $this->fetchThumbnailAsBase64DataUrl($asset);
            if (! $imageBase64DataUrl) {
                return null;
            }

            $analyzeOptions = [
                'model' => $this->defaultModel,
                'max_tokens' => 1000,
                'response_format' => ['type' => 'json_object'],
            ];
            if (! empty($lib['reference_image_data_urls']) && is_array($lib['reference_image_data_urls'])) {
                $analyzeOptions['reference_image_data_urls'] = $lib['reference_image_data_urls'];
            }

            $prompt = $this->buildPromptTagsOnly($asset, $libraryAddendum);
            $response = $this->provider->analyzeImage($imageBase64DataUrl, $prompt, $analyzeOptions);
            $parsed = $this->parseResponse($response, $asset, []);

            $tokensIn = (int) ($response['tokens_in'] ?? 0);
            $tokensOut = (int) ($response['tokens_out'] ?? 0);
            $cost = $this->provider->calculateCost($tokensIn, $tokensOut, $response['model'] ?? $this->defaultModel);

            return [
                'tags' => $parsed['tags'] ?? [],
                'tag_parse_stats' => $parsed['tag_parse_stats'] ?? [],
                'tokens_in' => $tokensIn,
                'tokens_out' => $tokensOut,
                'cost' => $cost,
            ];
        } catch (\Throwable $e) {
            Log::error('[AiMetadataGenerationService] OpenAI tags-only fallback failed after Rekognition failure', [
                'asset_id' => $asset->id,
                'error' => $e->getMessage(),
            ]);

            return null;
        }
    }

    /**
     * Sum two tag_parse_stats shapes into one (used when both OpenAI fields-only and Rekognition run).
     *
     * @param  array<string, int>|null  $a
     * @param  array<string, int>|null  $b
     * @return array<string, int>|null
     */
    protected function mergeTagParseStats(?array $a, ?array $b): ?array
    {
        if ($a === null && $b === null) {
            return null;
        }
        $a = $a ?? [];
        $b = $b ?? [];
        $keys = array_unique(array_merge(array_keys($a), array_keys($b)));
        $out = [];
        foreach ($keys as $k) {
            $out[$k] = (int) ($a[$k] ?? 0) + (int) ($b[$k] ?? 0);
        }

        return $out;
    }

    /**
     * Human/debug status for asset metadata: skipped vs attempted vs zero usable tags.
     *
     * @param  array<string, mixed>|null  $tagParseStats
     * @return array{0: string, 1: string|null}
     */
    protected function resolveAiTagInferenceOutcome(
        bool $tagsInference,
        bool $tagInferenceDesired,
        bool $skipAiTaggingUpload,
        int $tagsCreated,
        ?array $tagParseStats,
        ?string $rekognitionFailureClass = null,
    ): array {
        if (! $tagsInference) {
            if ($tagInferenceDesired && $skipAiTaggingUpload) {
                return ['skipped_upload_opt_out', null];
            }

            return ['skipped_tags_not_eligible', null];
        }

        if ($tagsCreated > 0) {
            return ['attempted_ok', null];
        }

        if ($rekognitionFailureClass !== null && $rekognitionFailureClass !== '') {
            return ['attempted_empty', 'rekognition_error:'.strtolower($rekognitionFailureClass)];
        }

        $raw = (int) ($tagParseStats['raw_tag_count'] ?? 0);
        if ($raw === 0) {
            return ['attempted_empty', 'empty_model'];
        }

        return ['attempted_empty', 'no_tags_passed_filters'];
    }

    /**
     * Build AI inference plan for an asset (read-only planning step).
     *
     * Determines which metadata fields need AI inference using deterministic DB logic.
     * This is a read-only planning step that does NOT call AI or write metadata.
     *
     * @return array Plan structure: ['fields' => [['key' => string, 'label' => string, 'type' => string, 'allowed_values' => array]]]
     */
    public function buildAiInferencePlan(Asset $asset): array
    {
        // Get category
        $categoryId = $asset->metadata['category_id'] ?? null;
        if (! $categoryId) {
            return ['fields' => []];
        }

        // Get ai_eligible fields that are select/multiselect
        $fields = DB::table('metadata_fields')
            ->where('ai_eligible', true)
            ->whereIn('type', ['select', 'multiselect'])
            ->where(function ($query) use ($asset) {
                $query->where('scope', 'system')
                    ->orWhere(function ($q) use ($asset) {
                        $q->where('tenant_id', $asset->tenant_id)
                            ->where('scope', '!=', 'system');
                    });
            })
            ->get();

        $planFields = [];
        foreach ($fields as $field) {
            // Check if field is enabled for category
            if (! $this->isFieldEnabledForCategory($asset, $field->id, $categoryId)) {
                continue;
            }

            // Check if field already has an approved value
            // If approved_at is not null, the field has an approved value and should be skipped
            $hasApprovedValue = DB::table('asset_metadata')
                ->where('asset_id', $asset->id)
                ->where('metadata_field_id', $field->id)
                ->whereNotNull('approved_at')
                ->exists();

            if ($hasApprovedValue) {
                continue;
            }

            // Get allowed_values (options)
            $allowedValues = DB::table('metadata_options')
                ->where('metadata_field_id', $field->id)
                ->pluck('value')
                ->toArray();

            if (empty($allowedValues)) {
                continue;
            }

            $planFields[] = [
                'key' => $field->key,
                'label' => $field->system_label ?? $field->key,
                'type' => $field->type,
                'allowed_values' => $allowedValues,
            ];
        }

        return [
            'fields' => $planFields,
        ];
    }

    /**
     * Get ai_eligible fields for asset's category.
     *
     * @return array Array of field definitions with options
     */
    protected function getEligibleFields(Asset $asset): array
    {
        // Get category
        $categoryId = $asset->metadata['category_id'] ?? null;
        if (! $categoryId) {
            return [];
        }

        // Get ai_eligible fields
        $fields = DB::table('metadata_fields')
            ->where('ai_eligible', true)
            ->whereIn('type', ['select', 'multiselect'])
            ->where(function ($query) use ($asset) {
                $query->where('scope', 'system')
                    ->orWhere(function ($q) use ($asset) {
                        $q->where('tenant_id', $asset->tenant_id)
                            ->where('scope', '!=', 'system');
                    });
            })
            ->get();

        $enabledFields = [];
        foreach ($fields as $field) {
            // Check if field is enabled for category
            if (! $this->isFieldEnabledForCategory($asset, $field->id, $categoryId)) {
                continue;
            }

            // Check if field already has an approved value
            // If approved_at is not null, the field has an approved value and should be skipped
            // This prevents unnecessary API calls for fields that already have values
            $hasApprovedValue = DB::table('asset_metadata')
                ->where('asset_id', $asset->id)
                ->where('metadata_field_id', $field->id)
                ->whereNotNull('approved_at')
                ->exists();

            if ($hasApprovedValue) {
                continue;
            }

            // Get options
            $options = DB::table('metadata_options')
                ->where('metadata_field_id', $field->id)
                ->pluck('value', 'system_label')
                ->toArray();

            if (empty($options)) {
                continue;
            }

            $enabledFields[] = [
                'key' => $field->key,
                'label' => $field->system_label ?? $field->key,
                'type' => $field->type,
                'options' => array_values($options),
                'description' => $field->description ?? null,
            ];
        }

        return $enabledFields;
    }

    /**
     * Whether the Tags field would qualify for AI tag inference (ignores upload-time _skip_ai_tagging).
     */
    protected function tagInferenceDesired(Asset $asset): bool
    {
        $categoryId = $asset->metadata['category_id'] ?? null;
        if (! $categoryId) {
            return false;
        }

        $field = DB::table('metadata_fields')
            ->where('key', 'tags')
            ->where('ai_eligible', true)
            ->whereIn('type', ['select', 'multiselect'])
            ->where(function ($query) use ($asset) {
                $query->where('scope', 'system')
                    ->orWhere(function ($q) use ($asset) {
                        $q->where('tenant_id', $asset->tenant_id)
                            ->where('scope', '!=', 'system');
                    });
            })
            ->first();

        if (! $field) {
            return false;
        }

        if (! $this->isFieldEnabledForCategory($asset, (int) $field->id, (int) $categoryId)) {
            return false;
        }

        return true;
    }

    /**
     * Whether to run vision for free-form tags only (asset_tag_candidates).
     * True when the Tags field is AI-eligible and enabled for the category
     * and the uploader did not opt out via _skip_ai_tagging.
     */
    protected function shouldRunTagInference(Asset $asset): bool
    {
        if (! empty(($asset->metadata ?? [])['_skip_ai_tagging'])) {
            return false;
        }

        return $this->tagInferenceDesired($asset);
    }

    /**
     * Check if field is enabled for category.
     *
     * CRITICAL: Uses MetadataVisibilityResolver to check tenant/brand/category-specific visibility.
     * This ensures AI suggestions respect category-specific field enablement settings.
     */
    protected function isFieldEnabledForCategory(Asset $asset, int $fieldId, int $categoryId): bool
    {
        $field = DB::table('metadata_fields')->where('id', $fieldId)->first();
        if (! $field) {
            return false;
        }

        // Get the category
        $category = \App\Models\Category::find($categoryId);
        if (! $category) {
            // Category doesn't exist - field is enabled by default
            return true;
        }

        // Get tenant for visibility check
        $tenant = \App\Models\Tenant::find($asset->tenant_id);
        if (! $tenant) {
            // Tenant doesn't exist - field is enabled by default
            return true;
        }

        // Use MetadataVisibilityResolver to check if field is visible for this category
        // This checks both system-level and tenant-level visibility overrides
        $fieldDefinition = [
            'field_id' => $fieldId,
            'key' => $field->key,
        ];

        return $this->visibilityResolver->isFieldVisible($fieldDefinition, $category, $tenant);
    }

    /**
     * Shared vision pipeline: same S3 fetch rules as AI metadata (no presigned URLs to providers).
     *
     * @return string|null Base64 data URL (data:image/webp;base64,...) or null on failure
     */
    public function fetchThumbnailForVisionAnalysis(Asset $asset): ?string
    {
        return $this->fetchThumbnailAsBase64DataUrl($asset);
    }

    /**
     * Fetch a specific stored raster path (e.g. PDF page render) for vision — same bucket rules as thumbnails.
     *
     * @return string|null Base64 data URL (data:image/webp;base64,...) or null on failure
     */
    public function fetchStoragePathForVisionAnalysis(Asset $asset, string $storagePath): ?string
    {
        if (! PdfBrandIntelligencePageRasterCatalog::isUsableStoragePath($storagePath, $asset)) {
            return null;
        }

        return $this->fetchObjectPathAsBase64DataUrl($asset, $storagePath);
    }

    /**
     * Fetch medium thumbnail from S3/MinIO and return as base64 data URL.
     * Uses IAM role (worker) or configured credentials; never exposes S3 URLs to AI providers.
     *
     * @return string|null Base64 data URL (data:image/webp;base64,...) or null on failure
     */
    protected function fetchThumbnailAsBase64DataUrl(Asset $asset): ?string
    {
        $thumbnailPath = $this->resolveThumbnailPath($asset);
        if (! $thumbnailPath) {
            return null;
        }

        return $this->fetchObjectPathAsBase64DataUrl($asset, $thumbnailPath);
    }

    /**
     * @return string|null Base64 data URL or null
     */
    protected function fetchObjectPathAsBase64DataUrl(Asset $asset, string $objectPath): ?string
    {
        $bucket = $asset->storageBucket;
        if (! $bucket) {
            Log::warning('[AiMetadataGenerationService] Asset missing storage bucket', [
                'asset_id' => $asset->id,
            ]);

            return null;
        }

        try {
            $contents = $this->bucketService->getObjectContents($bucket, $objectPath);
        } catch (\Throwable $e) {
            Log::error('[AiMetadataGenerationService] AI image fetch failed before provider call', [
                'asset_id' => $asset->id,
                'thumbnail_path' => $objectPath,
                'bucket' => $bucket->name,
                'error' => $e->getMessage(),
            ]);

            return null;
        }

        if (strlen($contents) === 0) {
            Log::error('[AiMetadataGenerationService] AI image fetch failed: empty file', [
                'asset_id' => $asset->id,
                'thumbnail_path' => $objectPath,
            ]);

            return null;
        }

        $base64 = base64_encode($contents);
        $mimeType = $this->inferMimeTypeFromPath($objectPath);

        return "data:{$mimeType};base64,{$base64}";
    }

    /**
     * Resolve thumbnail path from asset metadata (for THUMB_MEDIUM / THUMB_PREVIEW variant resolution).
     *
     * @return string|null S3 key path (assets/... or temp/uploads/...) or null if not available
     */
    protected function resolveThumbnailPath(Asset $asset): ?string
    {
        $metadata = $asset->metadata ?? [];

        $path = \App\Support\ThumbnailMetadata::stylePath($metadata, 'medium');
        if ($path) {
            if (str_starts_with($path, 'assets/') || str_starts_with($path, 'temp/uploads/')) {
                if (str_starts_with($path, 'temp/uploads/') && $asset->thumbnail_status !== \App\Enums\ThumbnailStatus::COMPLETED) {
                    return null;
                }

                return $path;
            }
        }

        $previewPath = \App\Support\ThumbnailMetadata::previewPath($metadata);
        if ($previewPath) {
            return $previewPath;
        }

        return null;
    }

    /**
     * Infer MIME type from file extension.
     */
    protected function inferMimeTypeFromPath(string $path): string
    {
        $ext = strtolower(pathinfo($path, PATHINFO_EXTENSION));
        $map = [
            'webp' => 'image/webp',
            'jpg' => 'image/jpeg',
            'jpeg' => 'image/jpeg',
            'png' => 'image/png',
            'gif' => 'image/gif',
        ];

        return $map[$ext] ?? 'image/webp';
    }

    /**
     * Build structured prompt for AI provider.
     *
     * Uses ONE Vision API call to infer both structured field values and general descriptive tags.
     *
     * @param  array  $fields  Field definitions
     * @param  string  $libraryAddendum  Optional custom-category peer context ({@see CategoryAiLibraryContextService})
     * @return string Prompt text
     */
    protected function buildPrompt(Asset $asset, array $fields, string $libraryAddendum = ''): string
    {
        $fieldsJson = [];
        foreach ($fields as $field) {
            $fieldsJson[$field['key']] = [
                'label' => $field['label'],
                'type' => $field['type'],
                'allowed_values' => $field['options'],
                'description' => $field['description'] ?? "The {$field['label']} for this image",
            ];
        }

        $min = $this->getTaggingMinConfidence();
        $minStr = number_format($min, 2, '.', '');
        $ctx = $this->buildPromptContextBlock($asset, 'full');

        $prompt = "Analyze this image and provide both structured metadata field values and searchable tags.\n\n";

        $prompt .= $ctx;
        if ($libraryAddendum !== '') {
            $prompt .= $libraryAddendum;
        }

        $prompt .= "STRUCTURED FIELDS:\n";
        $prompt .= "For each field below, select ONLY from the provided allowed values.\n";
        $prompt .= "Fields to analyze:\n";
        $prompt .= json_encode($fieldsJson, JSON_PRETTY_PRINT)."\n\n";

        $prompt .= "GENERAL TAGS:\n";
        $prompt .= $this->promptGeneralTagsBodyBlock();
        $prompt .= $this->promptNormalizationForAiTagsBlock();

        $prompt .= "REQUIREMENTS:\n";
        $prompt .= "- Only return fields/tags where confidence is >= {$minStr} ({$minStr} = 0–1 scale)\n";
        $prompt .= "- Include confidence score for each value/tag\n";
        $prompt .= "- If confidence is below {$minStr}, omit that field/tag\n";
        $prompt .= "- Field values must exactly match one of the allowed_values\n";
        $prompt .= "- Tags: follow NORMALIZATION above; optional 'detected_asset_type' is internal classification only (see GENERAL TAGS)\n";
        $prompt .= "- Return JSON with 'fields', optional 'detected_asset_type', and 'tags':\n";
        $prompt .= "{\n";
        $prompt .= "  \"detected_asset_type\": \"product_image\",\n";
        $prompt .= "  \"fields\": {\n";
        $prompt .= "    \"FIELD_KEY\": {\"value\": \"OPTION_FROM_ALLOWED_LIST\", \"confidence\": 0.94}\n";
        $prompt .= "  },\n";
        $prompt .= "  \"tags\": [{\"value\": \"example tag\", \"confidence\": 0.94}]\n";
        $prompt .= "}\n";
        $prompt .= "(Omit \"detected_asset_type\" if unsure — then use \"unknown\". Populate \"tags\" with objects {\"value\": string, \"confidence\": number} only for terms at or above {$minStr}; confidence means visual certainty only. Prefer fewer precise tags over many weak ones.)\n\n";
        $prompt .= 'Response:';

        return $prompt;
    }

    /**
     * Structured-fields-only prompt — used when free-form image tags are produced by a
     * separate provider (e.g. {@see AwsRekognitionVisionTagProvider}). The OpenAI vision
     * call is asked for `fields` only and is told to return an empty `tags` array so we
     * never accidentally hallucinate tags alongside the field inference.
     */
    protected function buildPromptFieldsOnly(Asset $asset, array $fields, string $libraryAddendum = ''): string
    {
        $fieldsJson = [];
        foreach ($fields as $field) {
            $fieldsJson[$field['key']] = [
                'label' => $field['label'],
                'type' => $field['type'],
                'allowed_values' => $field['options'],
                'description' => $field['description'] ?? "The {$field['label']} for this image",
            ];
        }

        $min = $this->getTaggingMinConfidence();
        $minStr = number_format($min, 2, '.', '');
        $ctx = $this->buildPromptContextBlock($asset, 'full');

        $prompt = "Analyze this image and provide ONLY structured metadata field values for a brand digital asset management system.\n\n";
        $prompt .= $ctx;
        if ($libraryAddendum !== '') {
            $prompt .= $libraryAddendum;
        }

        $prompt .= "STRUCTURED FIELDS:\n";
        $prompt .= "For each field below, select ONLY from the provided allowed values.\n";
        $prompt .= "Fields to analyze:\n";
        $prompt .= json_encode($fieldsJson, JSON_PRETTY_PRINT)."\n\n";

        $prompt .= "REQUIREMENTS:\n";
        $prompt .= "- Only return fields where confidence is >= {$minStr} ({$minStr} = 0–1 scale)\n";
        $prompt .= "- Include confidence score for each value\n";
        $prompt .= "- If confidence is below {$minStr}, omit that field\n";
        $prompt .= "- Field values must exactly match one of the allowed_values\n";
        $prompt .= "- DO NOT generate free-form tags. The \"tags\" array MUST be empty — image tag candidates are produced by a separate provider.\n";
        $prompt .= "- Return JSON with 'fields' and an empty 'tags' list:\n";
        $prompt .= "{\n";
        $prompt .= "  \"fields\": {\n";
        $prompt .= "    \"FIELD_KEY\": {\"value\": \"OPTION_FROM_ALLOWED_LIST\", \"confidence\": 0.94}\n";
        $prompt .= "  },\n";
        $prompt .= "  \"tags\": []\n";
        $prompt .= "}\n\n";
        $prompt .= 'Response:';

        return $prompt;
    }

    /**
     * Tags-only prompt when no structured fields qualify (e.g. executions with only Tags AI-enabled).
     */
    protected function buildPromptTagsOnly(Asset $asset, string $libraryAddendum = ''): string
    {
        $min = $this->getTaggingMinConfidence();
        $minStr = number_format($min, 2, '.', '');
        $ctx = $this->buildPromptContextBlock($asset, 'tags');

        $prompt = "Analyze this image and generate conservative, searchable tags for a brand digital asset management system.\n\n";

        $prompt .= $ctx;
        if ($libraryAddendum !== '') {
            $prompt .= $libraryAddendum;
        }

        $prompt .= "GENERAL TAGS:\n";
        $prompt .= $this->promptGeneralTagsBodyBlock();
        $prompt .= $this->promptNormalizationForAiTagsBlock();

        $prompt .= "CONFIDENCE:\n";
        $prompt .= "- Confidence represents visual certainty (not guess or interpretation)\n";
        $prompt .= "- Only include tags where confidence >= {$minStr}\n";
        $prompt .= "- Be conservative — if unsure, exclude the tag\n\n";

        $prompt .= "OUTPUT FORMAT:\n";
        $prompt .= "{\n";
        $prompt .= "  \"detected_asset_type\": \"graphic_design\",\n";
        $prompt .= "  \"fields\": {},\n";
        $prompt .= "  \"tags\": []\n";
        $prompt .= "}\n";
        $prompt .= "Populate \"tags\" with objects {\"value\": string, \"confidence\": number} derived only from the asset—never placeholder strings from this prompt.\n";
        $prompt .= "Use \"detected_asset_type\" exactly as in the broad asset family list under GENERAL TAGS, or omit it / use \"unknown\" if uncertain.\n\n";

        $prompt .= "Return ONLY valid JSON. No explanation.\n";

        return $prompt;
    }

    /**
     * Shared GENERAL TAGS body for both structured and tags-only vision prompts (after the "GENERAL TAGS:" header).
     */
    protected function promptGeneralTagsBodyBlock(): string
    {
        return "Generate conservative searchable tags for a brand asset management system.\n\n"
            ."The asset already has a category/folder. Do not repeat the category name, plural/singular variants, or obvious synonyms as tags. Tags should add searchable detail beyond the category.\n\n"
            ."First silently identify the broad asset family:\n"
            ."brand_mark, product_image, product_render, lifestyle_photo, environment_photo, people_photo, graphic_design, marketing_layout, document, presentation, screen_capture, video_still, audio_asset, font_asset, source_file, or unknown.\n\n"
            ."Do not output the broad asset family if it merely repeats the asset's existing category. Only output family/type terms when they add useful specificity beyond the category.\n\n"
            ."TAGGING PRINCIPLES:\n"
            ."- Tags should help a user find this asset later.\n"
            ."- Use visible subjects, objects, product types, readable text, layout purpose, environment, material, color, format, and composition when clear.\n"
            ."- Do not tag the category itself.\n"
            ."- Do not describe how the asset may have been created unless that is visually obvious and useful.\n"
            ."- Do not infer campaign strategy, audience, mood, lighting setup, shoot setup, or production process.\n"
            ."- Do not use examples from these instructions as tags unless they are clearly visible in the asset.\n"
            ."- Fewer accurate tags are better than many guessed tags.\n"
            ."- Return 3–8 tags when possible; 1–4 is acceptable for simple assets.\n\n"
            ."CATEGORY EXCLUSION RULE:\n"
            ."Before returning tags, compare each tag against the asset category/folder name and known category aliases.\n"
            ."Reject tags that simply restate the category.\n\n"
            ."Examples:\n"
            ."- Category \"Logos\": reject logo, logos, brand mark.\n"
            ."- Category \"Photography\": reject photography, photo, image.\n"
            ."- Category \"Bottle Renders\": reject bottle render, render, product render.\n"
            ."- Category \"Graphics\": reject graphic, graphics, design.\n"
            ."- Category \"Video\": reject video.\n"
            ."- Category \"Fonts\": reject font, fonts, typeface.\n"
            ."- Category \"Documents\" or \"PDFs\": reject document, pdf, file unless it adds specific meaning not already captured by the category.\n\n"
            ."ASSET-FAMILY GUIDANCE:\n"
            ."- For logos/brand marks: do not tag logo if the category is already Logos. Instead tag visible details such as wordmark, monogram, badge, icon mark, script type, gold, black, transparent background, readable brand/product words, or visual motif.\n"
            ."- For product images/renders: tag visible product, packaging, label, container, color, surface, angle, and composition only when obvious. Do not tag render/product render if that is already the category.\n"
            ."- For lifestyle/environment photography: tag visible people, place type, objects, activity, environment, material, and composition only when obvious. Do not tag photography/photo.\n"
            ."- For graphic design/marketing layouts: tag visible product, layout purpose, readable location/topic, offer/announcement type, format, and prominent design elements. Do not tag graphic/design if that is already the category.\n"
            ."- For documents/presentations: tag visible topic, chart/table/text elements, brand/product references, page type, and readable headings. Do not tag document/pdf if that is already the category.\n"
            ."- For screen captures: tag visible software/page type, navigation/search/content areas, and readable feature labels when useful. Do not over-tag narrow UI terms unless they are clearly relevant.\n"
            ."- For source files/audio/video/fonts: tag based on visible preview, allowed file metadata, and known file type, but do not repeat the category itself.\n\n"
            ."DO NOT USE THESE AS GENERIC FILLER TAGS:\n"
            ."studio, lighting setup, studio lighting, background, professional, modern, clean, aesthetic, branding, photoshoot, photo shoot, fashion, model, indoor, outdoor, close up, lifestyle.\n\n"
            ."These may only survive if directly and specifically supported by the visible asset and not merely guessed.\n\n";
    }

    /**
     * Normalization rules appended after GENERAL TAGS body (both prompt paths).
     */
    protected function promptNormalizationForAiTagsBlock(): string
    {
        return "NORMALIZATION:\n"
            ."- lowercase\n"
            ."- spaces, not hyphens or underscores\n"
            ."- 1–3 words per tag\n"
            ."- no duplicates or near-duplicates\n"
            ."- no subjective adjectives\n"
            ."- no category-name duplicates\n"
            ."- no prompt-example leakage\n"
            ."- confidence means visual certainty only\n\n";
    }

    /**
     * Category/brand context for vision prompts.
     *
     * @param  string  $mode  'full' — category hints for structured fields + tags (searchTagsHintForCategory).
     *                        'tags' — category/brand only plus strict visual-only instruction (no search hints).
     */
    protected function buildPromptContextBlock(Asset $asset, string $mode = 'full'): string
    {
        $lines = [];
        $meta = $asset->metadata ?? [];
        $categoryId = $meta['category_id'] ?? null;
        $category = null;
        if ($categoryId) {
            $category = Category::find($categoryId);
            if ($category && $category->name) {
                $lines[] = 'Library category: '.$category->name.'.';
                $lines[] = 'Do not repeat this category name, plural/singular variants, or obvious synonyms as tags; add searchable visible detail instead.';
            }
        }
        if ($asset->brand_id) {
            $brand = Brand::find($asset->brand_id);
            if ($brand && $brand->name) {
                $lines[] = 'Brand: '.$brand->name.'.';
            }
        }
        if ($categoryId && ! $category) {
            $lines[] = 'Library category id: '.$categoryId.'.';
        }

        if ($mode === 'tags') {
            $lines[] = 'Only include concrete, visually verifiable elements such as objects, people, environments, and actions. Do not infer style, mood, or intent.';
        } else {
            $hint = $this->searchTagsHintForCategory($category);
            if ($hint !== '') {
                $lines[] = $hint;
            }
        }

        if (! empty($lines)) {
            return "CONTEXT:\n".implode("\n", $lines)."\n\n";
        }

        return '';
    }

    /**
     * Extra guidance for common categories (e.g. photography) so tags are useful in search.
     */
    protected function searchTagsHintForCategory(?Category $category): string
    {
        if (! $category || ! $category->name) {
            return '';
        }
        $name = strtolower($category->name);
        if (str_contains($name, 'photo')) {
            return 'For photography structured fields, use shoot type (studio, on location, editorial), roles, product, composition where applicable. For free-form tags, do not use \"photo shoot\" — prefer specific subjects, people, and objects visible in the image.';
        }

        if (str_contains($name, 'product') || str_contains($name, 'marketing') || str_contains($name, 'graphic') || str_contains($name, 'print')) {
            return 'For free-form tags, emphasize visible product, packaging, beverage type, print format (sell sheet, poster, case card), and readable brand cues — avoid vague lifestyle labels unless clearly shown.';
        }

        return 'For free-form tags in product, marketing, graphic, or print categories, prefer what is visibly on the asset (product, packaging, format, readable type) rather than vague genre labels unless plainly shown.';
    }

    /**
     * Parse AI provider response into candidates and tags.
     *
     * Handles unified response with both 'fields' and 'tags' sections from ONE Vision API call.
     *
     * @param  array  $response  Provider response (from AIProviderInterface::analyzeImage)
     * @param  array  $fields  Field definitions
     * @return array ['candidates' => array, 'tags' => array] Candidates and tags ready for database insertion
     */
    protected function parseResponse(array $response, Asset $asset, array $fields): array
    {
        $text = $response['text'] ?? '';
        $candidates = [];
        $tags = [];
        $minConf = $this->getTaggingMinConfidence();
        $tagParseStats = [
            'raw_tag_count' => 0,
            'passed_confidence_count' => 0,
            'rejected_low_confidence_count' => 0,
            'rejected_blocklist_count' => 0,
            'rejected_sanitizer_count' => 0,
            'rejected_duplicate_count' => 0,
        ];

        try {
            $data = json_decode($text, true);
            if (! is_array($data)) {
                Log::warning('[AiMetadataGenerationService] Invalid JSON response', [
                    'asset_id' => $asset->id,
                    'response' => $text,
                ]);

                return ['candidates' => [], 'tags' => [], 'tag_parse_stats' => $tagParseStats];
            }

            $detectedAssetType = $this->parseDetectedAssetTypeFromVisionJson($data);
            $seenCanonicalTags = [];

            $category = null;
            $catIdForParse = $asset->metadata['category_id'] ?? null;
            if ($catIdForParse !== null && $catIdForParse !== '') {
                $category = Category::find($catIdForParse);
            }
            $categoryVisionBanSet = $this->buildVisionTagCategoryBanSet($category);

            // Parse structured fields
            $fieldsData = $data['fields'] ?? [];
            if (is_array($fieldsData)) {
                foreach ($fieldsData as $fieldKey => $fieldData) {
                    if (! is_array($fieldData)) {
                        continue;
                    }

                    $value = $fieldData['value'] ?? null;
                    $confidence = $fieldData['confidence'] ?? null;

                    if (! is_numeric($confidence) || (float) $confidence < $minConf) {
                        Log::debug('[AiMetadataGenerationService] Low confidence field skipped', [
                            'asset_id' => $asset->id,
                            'field_key' => $fieldKey,
                            'confidence' => $confidence,
                            'min_confidence' => $minConf,
                        ]);

                        continue;
                    }

                    // Find field definition
                    $field = null;
                    foreach ($fields as $f) {
                        if ($f['key'] === $fieldKey) {
                            $field = $f;
                            break;
                        }
                    }

                    if (! $field) {
                        continue;
                    }

                    // Validate value is in allowed options
                    if (! $this->isValueAllowed($value, $field)) {
                        Log::debug('[AiMetadataGenerationService] Invalid value skipped', [
                            'asset_id' => $asset->id,
                            'field_key' => $fieldKey,
                            'value' => $value,
                        ]);

                        continue;
                    }

                    $candidates[$fieldKey] = [
                        'value' => $value,
                        'confidence' => (float) $confidence,
                    ];
                }
            }

            // Parse general tags (primary shape: list of {value, confidence})
            $tagsData = $data['tags'] ?? [];
            if (is_array($tagsData)) {
                foreach ($tagsData as $tagData) {
                    if (! is_array($tagData)) {
                        if (is_string($tagData)) {
                            $tagData = ['value' => $tagData, 'confidence' => $minConf];
                        } else {
                            continue;
                        }
                    }

                    $tagValue = $tagData['value'] ?? null;
                    $confidence = $tagData['confidence'] ?? null;
                    if (empty($tagValue) || ! is_string($tagValue)) {
                        continue;
                    }

                    $this->acceptVisionTagCandidate(
                        $asset->id,
                        $tagValue,
                        $confidence,
                        $minConf,
                        $tags,
                        $tagParseStats,
                        $detectedAssetType,
                        $seenCanonicalTags,
                        $categoryVisionBanSet
                    );
                }
            }

            // Models often return [] or omit tags under strict confidence rules, or use alternate JSON keys / a map.
            if (($tagParseStats['raw_tag_count'] ?? 0) === 0) {
                $this->parseTagsFromAlternateVisionJsonShapes(
                    $data,
                    $minConf,
                    $asset->id,
                    $tags,
                    $tagParseStats,
                    $detectedAssetType,
                    $seenCanonicalTags,
                    $categoryVisionBanSet
                );
            }
        } catch (\Exception $e) {
            Log::error('[AiMetadataGenerationService] Failed to parse response', [
                'asset_id' => $asset->id,
                'error' => $e->getMessage(),
                'response' => $text,
            ]);
        }

        return [
            'candidates' => $candidates,
            'tags' => $tags,
            'tag_parse_stats' => $tagParseStats,
        ];
    }

    /**
     * Optional vision JSON key: silent asset classification (not persisted).
     */
    protected function parseDetectedAssetTypeFromVisionJson(array $data): ?string
    {
        if (! array_key_exists('detected_asset_type', $data)) {
            return null;
        }
        $v = $data['detected_asset_type'];
        if (! is_string($v)) {
            return null;
        }
        $v = strtolower(trim($v));
        if ($v === '' || $v === 'unknown') {
            return null;
        }
        if (in_array($v, self::VISION_DETECTED_ASSET_TYPES, true)) {
            return $v;
        }
        $mapped = $this->mapLegacyVisionDetectedAssetType($v);

        return in_array($mapped, self::VISION_DETECTED_ASSET_TYPES, true) ? $mapped : null;
    }

    /**
     * Map older vision JSON classifications to current asset-family ids.
     */
    protected function mapLegacyVisionDetectedAssetType(string $v): ?string
    {
        return match ($v) {
            'ui_screenshot' => 'screen_capture',
            'product_photo' => 'product_image',
            'packaging' => 'product_image',
            'logo_graphic' => 'brand_mark',
            'illustration' => 'graphic_design',
            'printed_layout' => 'marketing_layout',
            default => null,
        };
    }

    /**
     * Normalize only generic structural variants (after {@see canonicalizeAiVisionTagString}).
     * Do not collapse product-specific compounds (e.g. bourbon bottle, bottle label) — those stay searchable.
     */
    protected function applyVisionTagPhraseAliases(string $canonical): string
    {
        $t = preg_replace('/\s+/', ' ', trim($canonical));
        if ($t === '') {
            return '';
        }
        $pairs = [
            'bourbon whiskey' => 'bourbon',
            'bottle product' => 'bottle',
            'product bottle' => 'bottle',
            'transparent bg' => 'transparent background',
            'ui screenshot' => 'screen capture',
            'app screen' => 'screen capture',
        ];
        foreach ($pairs as $from => $to) {
            if (str_contains($t, $from)) {
                $t = str_replace($from, $to, $t);
            }
        }
        $t = preg_replace('/\s+/', ' ', trim($t));
        if ($t === 'webpage') {
            $t = 'screen capture';
        }

        return $t;
    }

    /**
     * Canonical form for vision tag comparison and storage (hyphens/underscores → spaces, punctuation stripped).
     */
    protected function canonicalizeAiVisionTagString(string $tag): string
    {
        $tag = strtolower(trim($tag));
        $tag = str_replace(['_', '-'], ' ', $tag);
        $tag = preg_replace('/[^a-z0-9\s]+/', '', $tag);
        $tag = preg_replace('/\s+/', ' ', $tag);
        $tag = trim((string) $tag);
        if (strlen($tag) > 1 && substr($tag, -1) === 's' && substr($tag, -2, 1) !== 's') {
            $tag = substr($tag, 0, -1);
        }
        $tag = preg_replace('/\s+/', ' ', trim($tag));

        return $tag;
    }

    protected function visionTagWordCount(string $canonicalLower): int
    {
        if ($canonicalLower === '') {
            return 0;
        }

        return count(preg_split('/\s+/', $canonicalLower, -1, PREG_SPLIT_NO_EMPTY));
    }

    /**
     * Instruction-like strings echoed as tags.
     */
    protected function visionTagLooksLikePromptLeakage(string $canonicalLower): bool
    {
        $fragments = [
            'allowed_values',
            'allowed values',
            'peer examples',
            'vocabulary hints',
            'anti-overfit',
            'anti-filler',
            'detected_asset_type',
            'broad asset family',
            'category exclusion',
            'tagging principles',
            'asset family guidance',
            'generic filler tags',
            'normalization',
            'library category',
            'structured fields',
            'illustrative string',
            'option from allowed list',
            'field key',
            'example tag',
            'populate tags',
            'json format',
            'requirement',
            'asset family hints',
        ];
        foreach ($fragments as $f) {
            if (str_contains($canonicalLower, $f)) {
                return true;
            }
        }

        return false;
    }

    /**
     * Pipeline / provenance noise sometimes echoed as tags (exact canonical match only).
     */
    protected function visionTagProvenancePipelineLeakageRejectionReason(string $canonicalLower): ?string
    {
        $phrases = [
            'from vision',
            'ai generated',
            'auto generated',
        ];
        if (in_array($canonicalLower, $phrases, true)) {
            return 'provenance_leakage';
        }
        $tokens = [
            'autogenerated',
            'metadata',
            'tag',
            'tags',
            'asset',
            'file',
            'generated',
        ];
        if (in_array($canonicalLower, $tokens, true)) {
            return 'provenance_leakage';
        }

        return null;
    }

    /**
     * Allowed multi-word background phrases (not generic "background" filler).
     */
    protected function visionTagBackgroundPhraseIsAllowed(string $canonicalLower): bool
    {
        if (str_contains($canonicalLower, 'transparent') && str_contains($canonicalLower, 'background')) {
            return true;
        }
        if (str_contains($canonicalLower, 'white background') || str_contains($canonicalLower, 'black background')) {
            return true;
        }

        return false;
    }

    /**
     * Reject generic production / mood tags unless the asset family plausibly supports them.
     */
    protected function visionTagGenericFillerRejectionReason(string $c, ?string $family): ?string
    {
        $family ??= 'unknown';
        foreach (['lighting setup', 'studio lighting', 'product photography'] as $p) {
            if (str_contains($c, $p)) {
                return 'global_production_filler';
            }
        }
        if (str_contains($c, 'photoshoot') || str_contains($c, 'photo shoot')) {
            return 'global_production_filler';
        }
        foreach (['professional', 'modern', 'clean', 'aesthetic', 'branding'] as $w) {
            if ($c === $w) {
                return 'generic_one_word';
            }
        }
        if (preg_match('/\bbackground\b/u', $c) === 1 && ! $this->visionTagBackgroundPhraseIsAllowed($c)) {
            return 'generic_background';
        }

        $peopleish = ['lifestyle_photo', 'people_photo'];
        $photoScene = ['lifestyle_photo', 'people_photo', 'environment_photo'];
        $productish = ['product_image', 'product_render'];

        if (preg_match('/\bstudio\b/u', $c) === 1 && ! in_array($family, $peopleish, true)) {
            return 'generic_studio';
        }
        if (preg_match('/\bmodel\b/u', $c) === 1 && ! in_array($family, $peopleish, true)) {
            return 'generic_model';
        }
        if (preg_match('/\bfashion\b/u', $c) === 1 && ! in_array($family, $peopleish, true)) {
            return 'generic_fashion';
        }
        if (preg_match('/\blifestyle\b/u', $c) === 1 && ! in_array($family, $peopleish, true)) {
            return 'generic_lifestyle_word';
        }

        $allowIndoorOutdoor = in_array($family, array_merge($photoScene, $productish), true);
        if (! $allowIndoorOutdoor && (preg_match('/\bindoor\b/u', $c) === 1 || preg_match('/\boutdoor\b/u', $c) === 1)) {
            return 'generic_indoor_outdoor';
        }

        $allowClose = in_array($family, array_merge($peopleish, $productish), true);
        if (! $allowClose && (str_contains($c, 'close up') || str_contains($c, 'closeup'))) {
            return 'generic_close_up';
        }

        return null;
    }

    /**
     * Merged vision-tag ban set: normalized category name/slug (plus simple singular/plural variants) plus
     * aliases from {@see visionTagCategoryAliasBanConfigRows} rows whose `match` rules fit this category.
     *
     * @return array<string, true>
     */
    protected function buildVisionTagCategoryBanSet(?Category $category): array
    {
        if ($category === null) {
            return [];
        }

        $set = [];

        foreach ($this->normalizedCategoryPhraseBanSet($category) as $phrase => $_) {
            if ($phrase !== '') {
                $set[$phrase] = true;
            }
        }

        foreach ($this->visionTagCategoryAliasBanConfigRows() as $row) {
            if (! is_array($row) || ! $this->categoryMatchesVisionTagAliasBanRow($row, $category)) {
                continue;
            }
            $aliases = $row['aliases'] ?? [];
            if (! is_array($aliases)) {
                continue;
            }
            foreach ($aliases as $alias) {
                if (! is_string($alias) || trim($alias) === '') {
                    continue;
                }
                $c = trim($this->applyVisionTagPhraseAliases($this->canonicalizeAiVisionTagString($alias)));
                if ($c !== '') {
                    $set[$c] = true;
                }
            }
        }

        return $set;
    }

    /**
     * @return list<array<string, mixed>>
     */
    protected function visionTagCategoryAliasBanConfigRows(): array
    {
        $base = config('ai.metadata_tagging.vision_tag_category_alias_bans', []);
        $append = config('ai.metadata_tagging.vision_tag_category_alias_bans_append', []);

        return array_merge(
            is_array($base) ? $base : [],
            is_array($append) ? $append : []
        );
    }

    protected function categoryRegexMatches(string $pattern, string $subject): bool
    {
        if ($pattern === '') {
            return false;
        }
        $ok = @preg_match($pattern, $subject);
        if ($ok === false) {
            Log::warning('[AiMetadataGenerationService] Invalid vision_tag_category_alias_bans regex', [
                'pattern' => $pattern,
            ]);

            return false;
        }

        return $ok === 1;
    }

    protected function categoryMatchesVisionTagAliasBanRow(array $row, Category $category): bool
    {
        $match = $row['match'] ?? null;
        if (! is_array($match)) {
            return false;
        }

        $name = (string) $category->name;
        $slug = strtolower(trim(str_replace(['_', '-'], ' ', (string) ($category->slug ?? ''))));

        foreach ($match['name_not_regex_any'] ?? [] as $rx) {
            if (is_string($rx) && $rx !== '' && $this->categoryRegexMatches($rx, $name)) {
                return false;
            }
        }
        foreach ($match['slug_not_regex_any'] ?? [] as $rx) {
            if (is_string($rx) && $rx !== '' && $this->categoryRegexMatches($rx, $slug)) {
                return false;
            }
        }

        foreach ($match['slug_equals_any'] ?? [] as $want) {
            if (! is_string($want) || $want === '') {
                continue;
            }
            if ($slug === strtolower(trim(str_replace(['_', '-'], ' ', $want)))) {
                return true;
            }
        }

        foreach ($match['name_regex_any'] ?? [] as $rx) {
            if (is_string($rx) && $rx !== '' && $this->categoryRegexMatches($rx, $name)) {
                return true;
            }
        }

        foreach ($match['slug_regex_any'] ?? [] as $rx) {
            if (is_string($rx) && $rx !== '' && $this->categoryRegexMatches($rx, $slug)) {
                return true;
            }
        }

        return false;
    }

    /**
     * Normalized category name and slug phrases (plus simple singular/plural) — reject as tags when identical.
     *
     * @return array<string, true>
     */
    protected function normalizedCategoryPhraseBanSet(Category $category): array
    {
        $set = [];
        $sources = [];
        if (is_string($category->name) && trim($category->name) !== '') {
            $sources[] = $category->name;
        }
        $slug = $category->slug ?? null;
        if (is_string($slug) && trim($slug) !== '') {
            $sources[] = str_replace(['-', '_'], ' ', $slug);
        }
        foreach ($sources as $src) {
            $base = $this->canonicalizeAiVisionTagString($src);
            foreach ($this->simpleEnglishPluralSingularPhraseVariants($base) as $v) {
                if ($v !== '') {
                    $set[$v] = true;
                }
            }
        }

        return $set;
    }

    /**
     * @return list<string>
     */
    protected function simpleEnglishPluralSingularPhraseVariants(string $normalizedPhrase): array
    {
        $normalizedPhrase = trim(preg_replace('/\s+/', ' ', $normalizedPhrase));
        if ($normalizedPhrase === '') {
            return [];
        }
        $variants = [$normalizedPhrase];
        if (strlen($normalizedPhrase) >= 3 && substr($normalizedPhrase, -1) === 's' && substr($normalizedPhrase, -2, 1) !== 's') {
            $variants[] = substr($normalizedPhrase, 0, -1);
        } elseif (substr($normalizedPhrase, -1) !== 's') {
            $variants[] = $normalizedPhrase.'s';
        }

        return array_values(array_unique(array_filter($variants)));
    }

    protected function visionTagCategoryRestatementRejectionReason(string $canonicalLower, array $categoryVisionBanSet): ?string
    {
        if (isset($categoryVisionBanSet[$canonicalLower])) {
            return 'category_restatement';
        }

        return null;
    }

    /**
     * @return string|null rejection reason code, or null if passed sanitizer gates (blocklist handled separately)
     */
    protected function getVisionTagSanitizerRejectionReason(
        string $canonicalLower,
        ?string $detectedAssetType,
        array $categoryVisionBanSet = []
    ): ?string {
        if ($canonicalLower === '') {
            return 'empty_after_normalize';
        }
        if ($this->visionTagWordCount($canonicalLower) > self::VISION_TAG_MAX_WORDS) {
            return 'too_many_words';
        }
        if ($this->visionTagLooksLikePromptLeakage($canonicalLower)) {
            return 'prompt_leakage';
        }
        if (($prov = $this->visionTagProvenancePipelineLeakageRejectionReason($canonicalLower)) !== null) {
            return $prov;
        }
        if (($catReason = $this->visionTagCategoryRestatementRejectionReason($canonicalLower, $categoryVisionBanSet)) !== null) {
            return $catReason;
        }
        $filler = $this->visionTagGenericFillerRejectionReason($canonicalLower, $detectedAssetType);
        if ($filler !== null) {
            return $filler;
        }

        return null;
    }

    /**
     * @param  array<string, int|float>  $tagParseStats
     * @param  array<string, true>  $seenCanonicalTags
     * @param  list<array{value: string, confidence: float}>  $tags
     */
    protected function acceptVisionTagCandidate(
        string $assetId,
        string $tagValue,
        mixed $confidence,
        float $minConf,
        array &$tags,
        array &$tagParseStats,
        ?string $detectedAssetType,
        array &$seenCanonicalTags,
        array $categoryVisionBanSet = []
    ): void {
        $tagParseStats['raw_tag_count']++;

        if (! is_numeric($confidence)) {
            $tagParseStats['rejected_low_confidence_count']++;

            return;
        }

        if ((float) $confidence < $minConf) {
            Log::debug('[AiMetadataGenerationService] Low confidence tag skipped', [
                'asset_id' => $assetId,
                'tag' => $tagValue,
                'confidence' => $confidence,
                'min_confidence' => $minConf,
            ]);
            $tagParseStats['rejected_low_confidence_count']++;

            return;
        }

        $canonicalTag = $this->canonicalizeAiVisionTagString($tagValue);
        $canonicalTag = $this->applyVisionTagPhraseAliases($canonicalTag);
        $sanitizerReason = $this->getVisionTagSanitizerRejectionReason($canonicalTag, $detectedAssetType, $categoryVisionBanSet);
        if ($sanitizerReason !== null) {
            $tagParseStats['rejected_sanitizer_count'] = (int) ($tagParseStats['rejected_sanitizer_count'] ?? 0) + 1;
            Log::debug('[AiMetadataGenerationService] Vision tag sanitizer rejected', [
                'asset_id' => $assetId,
                'reason' => $sanitizerReason,
                'original' => $tagValue,
                'normalized' => $canonicalTag,
                'detected_asset_type' => $detectedAssetType,
            ]);

            return;
        }

        if ($this->isVisionTagBlocklisted($canonicalTag)) {
            $tagParseStats['rejected_blocklist_count'] = (int) ($tagParseStats['rejected_blocklist_count'] ?? 0) + 1;
            Log::debug('[AiMetadataGenerationService] Vision tag sanitizer rejected', [
                'asset_id' => $assetId,
                'reason' => 'blocklist',
                'original' => $tagValue,
                'normalized' => $canonicalTag,
                'detected_asset_type' => $detectedAssetType,
            ]);

            return;
        }

        if ($this->isRedundantTag($canonicalTag)) {
            Log::debug('[AiMetadataGenerationService] Vision tag sanitizer rejected', [
                'asset_id' => $assetId,
                'reason' => 'redundant_photoshoot',
                'original' => $tagValue,
                'normalized' => $canonicalTag,
                'detected_asset_type' => $detectedAssetType,
            ]);

            return;
        }

        if (isset($seenCanonicalTags[$canonicalTag])) {
            $tagParseStats['rejected_duplicate_count'] = (int) ($tagParseStats['rejected_duplicate_count'] ?? 0) + 1;
            Log::debug('[AiMetadataGenerationService] Vision tag sanitizer rejected', [
                'asset_id' => $assetId,
                'reason' => 'duplicate',
                'original' => $tagValue,
                'normalized' => $canonicalTag,
                'detected_asset_type' => $detectedAssetType,
            ]);

            return;
        }

        Log::debug('[AiMetadataGenerationService] Vision tag sanitizer accepted', [
            'asset_id' => $assetId,
            'original' => $tagValue,
            'normalized' => $canonicalTag,
            'confidence' => (float) $confidence,
            'detected_asset_type' => $detectedAssetType,
        ]);

        $tagParseStats['passed_confidence_count']++;
        $seenCanonicalTags[$canonicalTag] = true;
        $tags[] = [
            'value' => $canonicalTag,
            'confidence' => (float) $confidence,
        ];
    }

    /**
     * When the primary "tags" array is empty, accept common alternate shapes from vision models.
     *
     * @param  array<string, mixed>  $data
     * @param  array<string, int|float>  $tagParseStats
     * @param  array<string, true>  $seenCanonicalTags
     * @param  list<array{value: string, confidence: float}>  $tags
     */
    protected function parseTagsFromAlternateVisionJsonShapes(
        array $data,
        float $minConf,
        string $assetId,
        array &$tags,
        array &$tagParseStats,
        ?string $detectedAssetType,
        array &$seenCanonicalTags,
        array $categoryVisionBanSet = []
    ): void {
        $rows = [];

        $tagsNode = $data['tags'] ?? null;
        if (is_array($tagsNode) && $tagsNode !== [] && $this->isAssociativeArray($tagsNode)) {
            foreach ($tagsNode as $value => $confidence) {
                if (is_string($value) && $value !== '' && is_numeric($confidence)) {
                    $rows[] = ['value' => $value, 'confidence' => (float) $confidence];
                }
            }
        }

        foreach (['keywords', 'suggested_tags', 'descriptive_tags', 'image_tags', 'search_tags'] as $altKey) {
            $block = $data[$altKey] ?? null;
            if (! is_array($block)) {
                continue;
            }
            foreach ($block as $item) {
                if (is_string($item) && $item !== '') {
                    $rows[] = ['value' => $item, 'confidence' => $minConf];

                    continue;
                }
                if (! is_array($item)) {
                    continue;
                }
                $v = $item['value'] ?? $item['tag'] ?? null;
                $c = $item['confidence'] ?? null;
                if (is_string($v) && $v !== '') {
                    $rows[] = [
                        'value' => $v,
                        'confidence' => is_numeric($c) ? (float) $c : $minConf,
                    ];
                }
            }
        }

        foreach ($rows as $row) {
            $this->acceptVisionTagCandidate(
                $assetId,
                $row['value'],
                $row['confidence'],
                $minConf,
                $tags,
                $tagParseStats,
                $detectedAssetType,
                $seenCanonicalTags,
                $categoryVisionBanSet
            );
        }
    }

    protected function isAssociativeArray(array $arr): bool
    {
        if ($arr === []) {
            return false;
        }

        return array_keys($arr) !== range(0, count($arr) - 1);
    }

    /**
     * Legacy alias for vision-tag canonicalization ({@see canonicalizeAiVisionTagString}).
     *
     * @return string Normalized tag
     */
    protected function normalizeTag(string $tag): string
    {
        return $this->canonicalizeAiVisionTagString($tag);
    }

    /**
     * @return list<string> lowercase normalized single-tag strings to drop (see config ai.metadata_tagging.vision_tag_blocklist).
     */
    protected function visionTagBlocklist(): array
    {
        $raw = config('ai.metadata_tagging.vision_tag_blocklist', ['model', 'fashion']);
        if (! is_array($raw)) {
            return ['model', 'fashion'];
        }
        $out = [];
        foreach ($raw as $t) {
            if (is_string($t) && $t !== '') {
                $out[] = strtolower(trim($t));
            }
        }

        return array_values(array_unique($out));
    }

    protected function isVisionTagBlocklisted(string $normalizedTag): bool
    {
        return in_array($normalizedTag, $this->visionTagBlocklist(), true);
    }

    /**
     * Tags that duplicate category-level concepts and should never be stored (e.g. "photo shoot" in a DAM photography context).
     */
    protected function isRedundantTag(string $normalized): bool
    {
        $t = preg_replace('/\s+/', ' ', trim($normalized));
        $compact = str_replace(' ', '', $t);

        return $t === 'photo shoot' || strcasecmp($compact, 'photoshoot') === 0;
    }

    /**
     * Check if value is allowed (in field options).
     *
     * @param  mixed  $value
     * @param  array  $field  Field definition
     */
    protected function isValueAllowed($value, array $field): bool
    {
        $options = $field['options'] ?? [];

        if ($field['type'] === 'multiselect') {
            if (! is_array($value)) {
                return false;
            }
            // All values must be in options
            foreach ($value as $v) {
                if (! in_array($v, $options, true)) {
                    return false;
                }
            }

            return true;
        }

        // Single select
        return in_array($value, $options, true);
    }

    /**
     * Create metadata field candidates in asset_metadata_candidates table.
     *
     * Stores AI-generated field values as candidates (not approved data).
     * Candidates must be reviewed and approved before being applied to the asset.
     *
     * @param  array  $candidates  Array of field candidates: ['field_key' => ['value' => mixed, 'confidence' => float]]
     * @return int Number of candidates created
     */
    protected function createCandidates(Asset $asset, array $candidates): int
    {
        if (empty($candidates)) {
            return 0;
        }

        $created = 0;
        foreach ($candidates as $fieldKey => $candidateData) {
            // Get field ID
            $field = DB::table('metadata_fields')
                ->where('key', $fieldKey)
                ->where(function ($query) use ($asset) {
                    $query->where('scope', 'system')
                        ->orWhere(function ($q) use ($asset) {
                            $q->where('tenant_id', $asset->tenant_id)
                                ->where('scope', '!=', 'system');
                        });
                })
                ->first();

            if (! $field) {
                continue;
            }

            // Check if candidate already exists
            $existing = DB::table('asset_metadata_candidates')
                ->where('asset_id', $asset->id)
                ->where('metadata_field_id', $field->id)
                ->where('producer', 'ai')
                ->whereNull('resolved_at')
                ->whereNull('dismissed_at')
                ->first();

            if ($existing) {
                // Update existing candidate
                DB::table('asset_metadata_candidates')
                    ->where('id', $existing->id)
                    ->update([
                        'value_json' => json_encode($candidateData['value']),
                        'confidence' => $candidateData['confidence'],
                        'source' => 'ai',
                        'updated_at' => now(),
                    ]);
            } else {
                // Create new candidate
                DB::table('asset_metadata_candidates')->insert([
                    'asset_id' => $asset->id,
                    'metadata_field_id' => $field->id,
                    'value_json' => json_encode($candidateData['value']),
                    'confidence' => $candidateData['confidence'],
                    'source' => 'ai',
                    'producer' => 'ai',
                    'created_at' => now(),
                    'updated_at' => now(),
                ]);
            }

            $created++;
        }

        return $created;
    }

    /**
     * Canonical tag strings already present on the asset ({@see asset_tags}), for deduping AI candidates.
     *
     * @return array<string, true>
     */
    protected function existingCanonicalTagsOnAsset(Asset $asset, ?Tenant $tenant): array
    {
        if (! $tenant) {
            return [];
        }

        $normalizer = app(TagNormalizationService::class);
        $out = [];
        foreach (DB::table('asset_tags')->where('asset_id', $asset->id)->pluck('tag') as $raw) {
            $c = $normalizer->normalize($raw, $tenant);
            if ($c !== null) {
                $out[$c] = true;
            }
        }

        return $out;
    }

    /**
     * Cap how many vision-derived tag candidates we persist so review UI aligns with plan headroom.
     * Tags are sorted by confidence (highest first). Approved `asset_tags` are unchanged — this only
     * limits new candidate rows from Rekognition/OpenAI.
     *
     * @param  list<array{value: string, confidence?: float}>  $tags
     * @return list<array{value: string, confidence?: float}>
     */
    protected function capVisionTagCandidatesForPlan(Asset $asset, array $tags): array
    {
        if ($tags === []) {
            return [];
        }
        $raw = config('ai.metadata_tagging.max_stored_vision_tag_candidates');
        if ($raw !== null && $raw !== '' && is_numeric($raw)) {
            $cap = max(1, (int) $raw);
        } else {
            $tenant = Tenant::find($asset->tenant_id);
            $planMax = $tenant ? app(PlanService::class)->getMaxTagsPerAsset($tenant) : 10;
            $cap = min(20, max(10, $planMax * 2));
        }
        usort($tags, static function (array $a, array $b): int {
            return ((float) ($b['confidence'] ?? 0)) <=> ((float) ($a['confidence'] ?? 0));
        });

        return array_values(array_slice($tags, 0, $cap));
    }

    /**
     * Create tag candidates in asset_tag_candidates table.
     *
     * Stores AI-generated tags as candidates (not approved data).
     * Tags must be reviewed and approved before being applied to the asset.
     *
     * @param  array  $tags  Array of ['value' => string, 'confidence' => float]
     * @return int Number of tag candidates created
     */
    protected function createTags(Asset $asset, array $tags): int
    {
        if (empty($tags)) {
            return 0;
        }

        $tenant = Tenant::find($asset->tenant_id);
        $tagNormalizationService = app(TagNormalizationService::class);
        $existingCanonicalOnAsset = $this->existingCanonicalTagsOnAsset($asset, $tenant);

        $created = 0;
        $now = now();

        foreach ($tags as $tagData) {
            $tagValue = $tagData['value'] ?? null;
            $confidence = $tagData['confidence'] ?? null;

            if (empty($tagValue) || ! is_string($tagValue)) {
                continue;
            }

            // Phase J.2.1: Normalize tag and check if canonical form has been dismissed
            $canonicalTag = $tagNormalizationService->normalize($tagValue, $tenant);

            // Skip if normalization results in blocked/invalid tag
            if ($canonicalTag === null) {
                continue;
            }

            // User (or auto-apply) already has this tag on the asset — skip redundant candidate
            if (isset($existingCanonicalOnAsset[$canonicalTag])) {
                continue;
            }

            // Check if any candidate with this canonical form has been dismissed
            $allCandidates = DB::table('asset_tag_candidates')
                ->where('asset_id', $asset->id)
                ->where('producer', 'ai')
                ->whereNotNull('dismissed_at')
                ->get();

            $canonicalDismissed = false;
            foreach ($allCandidates as $dismissedCandidate) {
                $dismissedCanonical = $tagNormalizationService->normalize($dismissedCandidate->tag, $tenant);
                if ($dismissedCanonical === $canonicalTag) {
                    $canonicalDismissed = true;
                    break;
                }
            }

            if ($canonicalDismissed) {
                // Skip creating candidate for dismissed canonical tag
                continue;
            }

            // Check if candidate already exists (avoid duplicates)
            $existing = DB::table('asset_tag_candidates')
                ->where('asset_id', $asset->id)
                ->where('tag', $tagValue)
                ->where('producer', 'ai')
                ->whereNull('resolved_at')
                ->whereNull('dismissed_at')
                ->first();

            if ($existing) {
                // Update existing candidate with new confidence if higher
                if (is_numeric($confidence) && $confidence > ($existing->confidence ?? 0)) {
                    DB::table('asset_tag_candidates')
                        ->where('id', $existing->id)
                        ->update([
                            'confidence' => $confidence,
                            'updated_at' => $now,
                        ]);
                    $created++;
                }

                continue;
            }

            // Create new tag candidate (NOT approved - stored as candidate for review)
            DB::table('asset_tag_candidates')->insert([
                'asset_id' => $asset->id,
                'tag' => $tagValue,
                'source' => 'ai',
                'confidence' => is_numeric($confidence) ? $confidence : null,
                'producer' => 'ai',
                'created_at' => $now,
                'updated_at' => $now,
            ]);

            $existingCanonicalOnAsset[$canonicalTag] = true;
            $created++;
        }

        return $created;
    }
}
