import { useState } from 'react'
import AssetImagePickerField from '../media/AssetImagePickerField'

/**
 * LogoVariantCard — a single "Display Variant" slot on the Brand Settings Identity tab.
 *
 * Renders a live preview of how the logo will look on the target surface (light or dark)
 * and lets the user choose between:
 *   - "Use primary"  → clears the variant; display call sites fall back to the primary logo
 *   - "Custom"       → shows an AssetImagePickerField for manual upload/picking
 *
 * An inline "Auto-generate from primary" button dispatches the raster variant automation
 * (white silhouette for dark, primary-color wash for light). The button is disabled when
 * its prerequisite isn't met (e.g. no primary color set for the light variant).
 *
 * The component intentionally has no opinion about *which* surface fields a brand should
 * fill — both variants are optional. The whole point is that an unset variant = "use
 * primary automatically" rather than a hidden fallback the user has to discover.
 */
export default function LogoVariantCard({
    id,
    surface, // 'light' | 'dark'
    title,
    description,
    autoGenerateLabel,
    autoGenerateHint,
    autoGenerateDisabled,
    isGenerating,
    onAutoGenerate,
    variantId,
    variantPreview,
    primaryPreview,
    onUsePrimary,
    onChange,
    fetchAssets,
    fetchDeliverables,
    brandId,
}) {
    const hasCustom = Boolean(variantId)
    const [mode, setMode] = useState(hasCustom ? 'custom' : 'primary')

    const selectMode = (next) => {
        if (next === mode) return
        setMode(next)
        if (next === 'primary') {
            onUsePrimary?.()
        }
    }

    const isDark = surface === 'dark'
    const previewBg = isDark ? 'bg-neutral-900' : 'bg-white'
    const previewRing = isDark ? 'ring-neutral-800' : 'ring-gray-200'
    const previewImage = mode === 'primary' ? primaryPreview : (variantPreview ?? primaryPreview)

    return (
        <div
            id={id}
            className={[
                'relative flex flex-col overflow-hidden rounded-xl ring-1',
                isDark ? 'bg-neutral-950 ring-neutral-800' : 'bg-gray-50 ring-gray-200',
            ].join(' ')}
        >
            <div className={['px-4 pt-4', isDark ? 'text-white' : 'text-gray-900'].join(' ')}>
                <div className="flex items-baseline justify-between">
                    <h4 className="text-sm font-semibold">{title}</h4>
                    {mode === 'primary' && (
                        <span className={['text-[11px] uppercase tracking-wide', isDark ? 'text-neutral-400' : 'text-gray-400'].join(' ')}>
                            Using primary
                        </span>
                    )}
                </div>
                <p className={['mt-1 text-xs leading-snug', isDark ? 'text-neutral-400' : 'text-gray-500'].join(' ')}>
                    {description}
                </p>
            </div>

            {/* Live preview on the target surface */}
            <div className="px-4 pt-3">
                <div
                    className={[
                        'flex h-28 items-center justify-center rounded-lg ring-1',
                        previewBg,
                        previewRing,
                    ].join(' ')}
                >
                    {previewImage ? (
                        <img
                            src={previewImage}
                            alt={`Logo preview on ${isDark ? 'dark' : 'light'} background`}
                            className="max-h-20 max-w-[80%] object-contain"
                        />
                    ) : (
                        <span className={['text-xs', isDark ? 'text-neutral-500' : 'text-gray-400'].join(' ')}>
                            No logo set yet
                        </span>
                    )}
                </div>
            </div>

            {/* Mode selector */}
            <div className="px-4 pt-3">
                <div className={['inline-flex rounded-md ring-1', isDark ? 'ring-neutral-700' : 'ring-gray-300'].join(' ')} role="group">
                    <button
                        type="button"
                        onClick={() => selectMode('primary')}
                        className={[
                            'px-3 py-1.5 text-xs font-medium rounded-l-md transition',
                            mode === 'primary'
                                ? (isDark ? 'bg-white text-neutral-900' : 'bg-gray-900 text-white')
                                : (isDark ? 'text-neutral-300 hover:bg-neutral-800' : 'text-gray-700 hover:bg-gray-100'),
                        ].join(' ')}
                    >
                        Use primary
                    </button>
                    <button
                        type="button"
                        onClick={() => selectMode('custom')}
                        className={[
                            'px-3 py-1.5 text-xs font-medium rounded-r-md transition',
                            mode === 'custom'
                                ? (isDark ? 'bg-white text-neutral-900' : 'bg-gray-900 text-white')
                                : (isDark ? 'text-neutral-300 hover:bg-neutral-800' : 'text-gray-700 hover:bg-gray-100'),
                        ].join(' ')}
                    >
                        Custom
                    </button>
                </div>
            </div>

            {/* Custom picker (visible only in custom mode) */}
            {mode === 'custom' && (
                <div className="px-4 pt-3">
                    <div className={['rounded-lg border p-2', isDark ? 'border-neutral-700 bg-neutral-900' : 'border-gray-200 bg-white'].join(' ')}>
                        <AssetImagePickerField
                            value={{
                                preview_url: variantPreview ?? null,
                                asset_id: variantId ?? null,
                            }}
                            onChange={onChange}
                            fetchAssets={fetchAssets}
                            fetchDeliverables={fetchDeliverables}
                            getAssetDownloadUrl={(assetId) => `/app/assets/${assetId}/download`}
                            title={`Select logo for ${isDark ? 'dark' : 'light'} backgrounds`}
                            defaultCategoryLabel="Logos"
                            contextCategory="logos"
                            aspectRatio={{ width: 265, height: 64 }}
                            minWidth={265}
                            minHeight={64}
                            placeholder="Click to choose from library or upload"
                            helperText={isDark ? 'Light-colored logo for dark backgrounds' : 'Dark-colored logo for light/white backgrounds'}
                            theme={isDark ? 'dark' : 'light'}
                            brandId={brandId}
                        />
                    </div>
                </div>
            )}

            {/* Auto-generate footer */}
            <div className={['mt-auto px-4 pt-3 pb-4', isDark ? 'border-neutral-800' : 'border-gray-100'].join(' ')}>
                <button
                    type="button"
                    disabled={autoGenerateDisabled}
                    onClick={() => {
                        selectMode('custom')
                        onAutoGenerate?.()
                    }}
                    className={[
                        'inline-flex items-center gap-1.5 rounded-md px-3 py-1.5 text-xs font-semibold transition disabled:cursor-not-allowed disabled:opacity-50',
                        isDark
                            ? 'bg-neutral-800 text-white ring-1 ring-neutral-700 hover:bg-neutral-700'
                            : 'bg-white text-violet-700 ring-1 ring-violet-200 shadow-sm hover:bg-violet-50',
                    ].join(' ')}
                >
                    <span aria-hidden="true">✨</span>
                    {isGenerating ? 'Working…' : autoGenerateLabel}
                </button>
                {autoGenerateHint && (
                    <p className={['mt-1.5 text-[11px] leading-snug', isDark ? 'text-neutral-500' : 'text-gray-500'].join(' ')}>
                        {autoGenerateHint}
                    </p>
                )}
            </div>
        </div>
    )
}
