<?php

/**
 * Embedded metadata governance: allowlisted keys only are indexed / visible / mappable.
 * Unknown keys remain in raw payload (Layer B) only.
 *
 * Types: string, number, date, datetime, boolean, json, keyword (arrays → one index row per item).
 *
 * system_map_mode: fill_if_empty | overwrite_if_nullish | never | trusted_overwrite
 */

return [
    'schema_version' => '1',

    'sensitive_fq_keys' => [
        'exif.GPSLatitude',
        'exif.GPSLongitude',
        'exif.GPSAltitude',
        'exif.BodySerialNumber',
        'exif.LensSerialNumber',
    ],

    'keys' => [
        'exif.Make' => [
            'namespace' => 'exif',
            'normalized_key' => 'camera_make',
            'type' => 'string',
            'index' => true,
            'filterable' => false,
            'visible' => true,
            'map_to_system' => null,
            'sensitivity' => 'none',
        ],
        'exif.Model' => [
            'namespace' => 'exif',
            'normalized_key' => 'camera_model',
            'type' => 'string',
            'index' => true,
            'filterable' => false,
            'visible' => true,
            'map_to_system' => null,
            'sensitivity' => 'none',
        ],
        'exif.LensModel' => [
            'namespace' => 'exif',
            'normalized_key' => 'lens_model',
            'type' => 'string',
            'index' => true,
            'filterable' => false,
            'visible' => true,
            'map_to_system' => null,
            'sensitivity' => 'none',
        ],
        'exif.DateTimeOriginal' => [
            'namespace' => 'exif',
            'normalized_key' => 'captured_at_embedded',
            'type' => 'datetime',
            'index' => true,
            'filterable' => true,
            'visible' => true,
            'map_to_system' => 'captured_at',
            'system_map_mode' => 'fill_if_empty',
            'sensitivity' => 'none',
        ],
        'exif.ISOSpeedRatings' => [
            'namespace' => 'exif',
            'normalized_key' => 'iso',
            'type' => 'number',
            'index' => true,
            'filterable' => false,
            'visible' => true,
            'map_to_system' => null,
            'sensitivity' => 'none',
        ],
        'exif.PhotographicSensitivity' => [
            'namespace' => 'exif',
            'normalized_key' => 'iso',
            'type' => 'number',
            'index' => true,
            'filterable' => false,
            'visible' => true,
            'map_to_system' => null,
            'sensitivity' => 'none',
        ],
        'exif.FocalLength' => [
            'namespace' => 'exif',
            'normalized_key' => 'focal_length',
            'type' => 'string',
            'index' => true,
            'filterable' => false,
            'visible' => true,
            'map_to_system' => null,
            'sensitivity' => 'none',
        ],
        'exif.FNumber' => [
            'namespace' => 'exif',
            'normalized_key' => 'aperture',
            'type' => 'number',
            'index' => true,
            'filterable' => false,
            'visible' => true,
            'map_to_system' => null,
            'sensitivity' => 'none',
        ],
        'exif.ExposureTime' => [
            'namespace' => 'exif',
            'normalized_key' => 'exposure_time',
            'type' => 'string',
            'index' => true,
            'filterable' => false,
            'visible' => true,
            'map_to_system' => null,
            'sensitivity' => 'none',
        ],

        'iptc.Keywords' => [
            'namespace' => 'iptc',
            'normalized_key' => 'iptc_keyword',
            'type' => 'keyword',
            'index' => true,
            'filterable' => true,
            'visible' => true,
            'map_to_system' => null,
            'sensitivity' => 'none',
        ],
        'iptc.Byline' => [
            'namespace' => 'iptc',
            'normalized_key' => 'author_name',
            'type' => 'string',
            'index' => true,
            'filterable' => false,
            'visible' => true,
            'map_to_system' => null,
            'sensitivity' => 'caution',
        ],
        'iptc.CopyrightNotice' => [
            'namespace' => 'iptc',
            'normalized_key' => 'copyright_notice',
            'type' => 'string',
            'index' => true,
            'filterable' => false,
            'visible' => true,
            'map_to_system' => null,
            'sensitivity' => 'none',
        ],

        'pdf.Author' => [
            'namespace' => 'pdf',
            'normalized_key' => 'document_author',
            'type' => 'string',
            'index' => true,
            'filterable' => false,
            'visible' => true,
            'map_to_system' => null,
            'sensitivity' => 'caution',
        ],
        'pdf.Title' => [
            'namespace' => 'pdf',
            'normalized_key' => 'document_title_embedded',
            'type' => 'string',
            'index' => true,
            'filterable' => false,
            'visible' => true,
            'map_to_system' => null,
            'sensitivity' => 'none',
        ],
        'pdf.Subject' => [
            'namespace' => 'pdf',
            'normalized_key' => 'document_subject',
            'type' => 'string',
            'index' => true,
            'filterable' => false,
            'visible' => true,
            'map_to_system' => null,
            'sensitivity' => 'none',
        ],
        'pdf.Keywords' => [
            'namespace' => 'pdf',
            'normalized_key' => 'document_keyword',
            'type' => 'keyword',
            'index' => true,
            'filterable' => false,
            'visible' => true,
            'map_to_system' => null,
            'sensitivity' => 'none',
        ],
        'pdf.Creator' => [
            'namespace' => 'pdf',
            'normalized_key' => 'document_creator',
            'type' => 'string',
            'index' => true,
            'filterable' => false,
            'visible' => true,
            'map_to_system' => null,
            'sensitivity' => 'none',
        ],
        'pdf.Producer' => [
            'namespace' => 'pdf',
            'normalized_key' => 'document_producer',
            'type' => 'string',
            'index' => true,
            'filterable' => false,
            'visible' => true,
            'map_to_system' => null,
            'sensitivity' => 'none',
        ],
        'pdf.CreationDate' => [
            'namespace' => 'pdf',
            'normalized_key' => 'document_created_at_embedded',
            'type' => 'datetime',
            'index' => true,
            'filterable' => false,
            'visible' => true,
            'map_to_system' => null,
            'sensitivity' => 'none',
        ],
        'pdf.ModDate' => [
            'namespace' => 'pdf',
            'normalized_key' => 'document_modified_at_embedded',
            'type' => 'datetime',
            'index' => true,
            'filterable' => false,
            'visible' => true,
            'map_to_system' => null,
            'sensitivity' => 'none',
        ],

        'image.ColorProfile' => [
            'namespace' => 'image',
            'normalized_key' => 'embedded_color_profile',
            'type' => 'string',
            'index' => true,
            'filterable' => false,
            'visible' => true,
            'map_to_system' => null,
            'sensitivity' => 'none',
        ],
    ],
];
