<?php

/**
 * Structured in-app help actions for Jackpot.
 *
 * Consumed by HelpActionService and GET /app/help/actions.
 * See docs/help-actions.md for AI / retrieval guidance.
 */
return [
    'actions' => [
        [
            'key' => 'assets.upload',
            'title' => 'Upload new assets',
            'aliases' => ['add files', 'ingest', 'import media'],
            'category' => 'Assets',
            'short_answer' => 'Open the Assets library and use the upload flow to add files; Jackpot processes them in the background.',
            'steps' => [
                'Go to Assets.',
                'Click Upload (or open the upload dialog from the library toolbar).',
                'Choose files or drag them into the drop zone and complete any required metadata.',
                'Wait for processing; new rows appear in the grid as derivatives complete.',
            ],
            'route_name' => 'assets.index',
            'route_bindings' => [],
            'deep_link' => [
                'route_name' => 'assets.index',
                'params' => [],
                'query' => [],
            ],
            'highlight' => [
                'selector' => 'assets-upload',
                'label' => 'Add Asset',
            ],
            'page_label' => 'Assets',
            'permissions' => ['asset.upload'],
            'tags' => ['upload', 'files', 'dam'],
            'related' => ['assets.staged', 'assets.processing'],
            'routes' => ['assets.index'],
            'page_context' => ['Assets'],
            'priority' => 90,
            'in_common' => true,
            'common_sort' => 10,
        ],
        [
            'key' => 'assets.browse',
            'title' => 'Browse and open assets',
            'aliases' => ['find asset', 'search library', 'asset grid'],
            'category' => 'Assets',
            'short_answer' => 'Use the Assets grid, filters, and saved views to find work; open an asset to preview details and metadata.',
            'steps' => [
                'Open Assets from the main navigation.',
                'Use filters, categories, or search to narrow the list.',
                'Click an asset to open the detail / drawer experience.',
            ],
            'route_name' => 'assets.index',
            'route_bindings' => [],
            'page_label' => 'Assets',
            'permissions' => [],
            'tags' => ['library', 'grid', 'search'],
            'related' => ['assets.edit_single_metadata', 'assets.view_details', 'collections.add_assets'],
            'routes' => ['assets.index'],
            'page_context' => ['Assets'],
            'priority' => 85,
            'in_common' => true,
            'common_sort' => 20,
        ],
        [
            'key' => 'assets.edit_single_metadata',
            'title' => 'Edit tags, fields, or metadata on one asset',
            'aliases' => [
                'add tag to asset',
                'remove tag from asset',
                'edit asset metadata',
                'change asset fields',
                'asset drawer metadata',
                'update one asset',
                'fix one asset tag',
                'add custom field to asset',
                'this asset',
                'one asset',
                'properties',
                'descriptions',
            ],
            'category' => 'Assets',
            'short_answer' => 'Open the asset from the library, then edit its tags, fields, category, or metadata in the asset drawer / details panel. This is different from Manage, which only changes the tag list and field structure for the whole workspace—not values on a specific file. If you need to change the taxonomy itself, use Manage tags, fields, and metadata structure instead.',
            'steps' => [
                'Go to Assets and open the one asset (click the card to open the drawer).',
                'In the drawer, use the Asset Data / Fields area to edit tags, category, and metadata you have rights to.',
                'Save or apply changes; if approvals are on, watch for pending states in Approvals or Review.',
                'To change the available tags or field definitions for everyone, use Manage → Categories, Tags, Values, or Fields—not this flow.',
            ],
            'route_name' => 'assets.index',
            'route_bindings' => [],
            'deep_link' => [
                'route_name' => 'assets.index',
                'params' => [],
                'query' => [],
            ],
            'highlight' => [
                'selector' => 'asset-metadata-panel',
                'label' => 'Asset metadata (open an asset first)',
            ],
            'page_label' => 'Assets',
            'permissions' => ['metadata.edit_post_upload'],
            'tags' => ['metadata', 'fields', 'tags', 'single', 'drawer'],
            'related' => ['assets.view_details', 'assets.bulk_edit_metadata', 'manage.tags_fields_metadata', 'insights.ai_review'],
            'routes' => ['assets.index', 'assets.staged', 'assets.processing'],
            'page_context' => ['Assets'],
            'priority' => 96,
            'in_common' => true,
            'common_sort' => 28,
        ],
        [
            'key' => 'assets.bulk_edit_metadata',
            'title' => 'Bulk edit tags, fields, or metadata on multiple assets',
            'aliases' => [
                'bulk add tags',
                'remove tags from many assets',
                'edit multiple assets',
                'batch metadata',
                'batch edit fields',
                'apply tag to selected assets',
                'update many assets',
                'bulk actions metadata',
                'multiple assets',
                'many assets',
                'selected assets',
                'bulk edit',
            ],
            'category' => 'Assets',
            'short_answer' => 'Select one or more assets in the Assets grid (checkboxes), then use the floating selected-assets toolbar to open bulk actions—including bulk metadata edits. This updates many assets at once. It is not the same as Manage, which configures the metadata system (tag taxonomy, field definitions, values). The bulk toolbar appears after you select assets.',
            'steps' => [
                'On Assets, select assets using the checkboxes on cards.',
                'When one or more are selected, use the bottom toolbar’s bulk / actions entry (often labeled for bulk operations).',
                'Choose metadata-related actions and confirm prompts; large selections may ask for confirmation. Your role may need bulk-metadata permission.',
                'To edit only one asset, open its drawer instead. To rename or delete a tag globally, use Manage → Tags.',
            ],
            'route_name' => 'assets.index',
            'route_bindings' => [],
            'deep_link' => [
                'route_name' => 'assets.index',
                'params' => [],
                'query' => [],
            ],
            'highlight' => [
                'selector' => 'asset-bulk-edit',
                'label' => 'Bulk actions (select assets first)',
            ],
            'page_label' => 'Assets',
            'permissions' => [],
            'tags' => ['bulk', 'metadata', 'tags', 'fields', 'selection'],
            'related' => ['assets.select_multiple', 'assets.edit_single_metadata', 'manage.tags_fields_metadata'],
            'routes' => ['assets.index', 'assets.staged', 'assets.processing'],
            'page_context' => ['Assets'],
            'priority' => 95,
            'in_common' => true,
            'common_sort' => 29,
        ],
        [
            'key' => 'assets.view_details',
            'title' => 'Open an asset (detail drawer)',
            'aliases' => ['open asset', 'asset preview', 'view asset', 'asset drawer'],
            'category' => 'Assets',
            'short_answer' => 'From the Assets grid, click an asset to open the detail drawer. That is where you review files and edit metadata for that one asset.',
            'steps' => [
                'Go to Assets.',
                'Click the asset card you need; the drawer opens.',
                'Use tabs and sections in the drawer for preview, metadata, and related actions.',
            ],
            'route_name' => 'assets.index',
            'route_bindings' => [],
            'page_label' => 'Assets',
            'permissions' => [],
            'tags' => ['drawer', 'preview', 'detail'],
            'related' => ['assets.edit_single_metadata', 'assets.bulk_edit_metadata'],
            'routes' => ['assets.index', 'assets.staged', 'assets.processing'],
            'page_context' => ['Assets'],
            'priority' => 72,
            'in_common' => false,
            'common_sort' => 535,
        ],
        [
            'key' => 'assets.select_multiple',
            'title' => 'Select multiple assets in the grid',
            'aliases' => ['multi select assets', 'checkbox assets', 'select all on page'],
            'category' => 'Assets',
            'short_answer' => 'Use the checkboxes on asset cards to build a selection; the floating toolbar then offers bulk actions (downloads, metadata, lifecycle, etc.).',
            'steps' => [
                'On Assets, click the checkbox on each card you need (hover may reveal it on desktop).',
                'Watch the selected count in the bottom toolbar.',
                'Open bulk actions from that toolbar when you are ready.',
            ],
            'route_name' => 'assets.index',
            'route_bindings' => [],
            'deep_link' => [
                'route_name' => 'assets.index',
                'params' => [],
                'query' => [],
            ],
            'highlight' => [
                'selector' => 'asset-selection-checkbox',
                'label' => 'Selection checkbox',
            ],
            'page_label' => 'Assets',
            'permissions' => [],
            'tags' => ['selection', 'checkbox', 'grid'],
            'related' => ['assets.bulk_edit_metadata', 'assets.edit_single_metadata'],
            'routes' => ['assets.index'],
            'page_context' => ['Assets'],
            'priority' => 88,
            'in_common' => false,
            'common_sort' => 540,
        ],
        [
            'key' => 'assets.staged',
            'title' => 'Work with staged uploads',
            'aliases' => ['draft uploads', 'incomplete upload'],
            'category' => 'Assets',
            'short_answer' => 'Staged uploads are in-progress or held before finalizing into the library.',
            'steps' => [
                'Open Assets → Staged (or the staged uploads view from the library).',
                'Review each staged item and complete required metadata or fixes.',
                'Finalize or discard items according to your workflow.',
            ],
            'route_name' => 'assets.staged',
            'route_bindings' => [],
            'page_label' => 'Staged uploads',
            'permissions' => [],
            'tags' => ['upload', 'staging'],
            'related' => ['assets.upload', 'assets.processing'],
            'routes' => ['assets.staged'],
            'page_context' => ['Assets'],
            'priority' => 88,
            'in_common' => false,
            'common_sort' => 500,
        ],
        [
            'key' => 'assets.processing',
            'title' => 'See asset processing status',
            'aliases' => ['pipeline', 'thumbnails', 'derivatives', 'processing queue'],
            'category' => 'Assets',
            'short_answer' => 'Use the processing view to see what is still running or failed for your brand.',
            'steps' => [
                'Open Assets → Processing (active jobs / queue).',
                'Identify assets that are still processing or need attention.',
                'From an asset detail view you can often retry or inspect incidents when you have permission.',
            ],
            'route_name' => 'assets.processing',
            'route_bindings' => [],
            'page_label' => 'Asset processing',
            'permissions' => [],
            'tags' => ['processing', 'status', 'pipeline'],
            'related' => ['assets.browse', 'assets.upload'],
            'routes' => ['assets.processing'],
            'page_context' => ['Assets'],
            'priority' => 88,
            'in_common' => true,
            'common_sort' => 45,
        ],
        [
            'key' => 'collections.add_assets',
            'title' => 'Add assets to a collection',
            'aliases' => ['collection membership', 'put in collection'],
            'category' => 'Collections',
            'short_answer' => 'Collections group assets for sharing and campaigns; add assets from the collection or from an asset’s collections controls.',
            'steps' => [
                'Go to Collections and open the collection (or create one).',
                'Use Add assets / pick from the library, or from an asset use Collections to sync membership.',
                'Save changes; verify membership in the collection’s asset list.',
            ],
            'route_name' => 'collections.index',
            'route_bindings' => [],
            'deep_link' => [
                'route_name' => 'collections.index',
                'params' => [],
                'query' => [],
            ],
            'highlight' => [
                'selector' => 'collections-add-assets',
                'label' => 'Selection bar on a collection',
            ],
            'page_label' => 'Collections',
            'permissions' => [],
            'tags' => ['collections', 'organize'],
            'related' => ['collections.share', 'downloads.package'],
            'routes' => ['collections.index'],
            'page_context' => ['Collections'],
            'priority' => 86,
            'in_common' => true,
            'common_sort' => 50,
        ],
        [
            'key' => 'collections.manage',
            'title' => 'Create and manage collections',
            'aliases' => ['new collection', 'edit collection'],
            'category' => 'Collections',
            'short_answer' => 'Collections are managed from the Collections index: create, rename, configure access, and curate membership.',
            'steps' => [
                'Open Collections.',
                'Create a collection or select one to edit.',
                'Adjust settings, members, and linked assets as your role allows.',
            ],
            'route_name' => 'collections.index',
            'route_bindings' => [],
            'deep_link' => [
                'route_name' => 'collections.index',
                'params' => [],
                'query' => [],
            ],
            'highlight' => [
                'selector' => 'collections-create',
                'label' => 'Create collection',
            ],
            'page_label' => 'Collections',
            'permissions' => [],
            'tags' => ['collections', 'manage'],
            'related' => ['collections.add_assets', 'collections.share'],
            'routes' => ['collections.index'],
            'page_context' => ['Collections'],
            'priority' => 82,
            'in_common' => false,
            'common_sort' => 510,
        ],
        [
            'key' => 'collections.share',
            'title' => 'Share a collection',
            'aliases' => ['public link', 'guest access', 'share link'],
            'category' => 'Collections',
            'short_answer' => 'Generate or manage a share experience from the collection so external viewers can review or download within policy.',
            'steps' => [
                'Open Collections and select the collection.',
                'Use the share / public link or invite options in the collection UI.',
                'Copy the link or send instructions; respect download and password rules set by your admin.',
            ],
            'route_name' => 'collections.index',
            'route_bindings' => [],
            'page_label' => 'Collections',
            'permissions' => [],
            'tags' => ['share', 'link', 'guest'],
            'related' => ['collections.add_assets', 'downloads.package'],
            'routes' => ['collections.index'],
            'page_context' => ['Collections'],
            'priority' => 80,
            'in_common' => true,
            'common_sort' => 55,
        ],
        [
            'key' => 'downloads.package',
            'title' => 'Download assets (packaged downloads)',
            'aliases' => ['zip', 'export', 'bulk download'],
            'category' => 'Downloads',
            'short_answer' => 'Build a download from selected assets or a collection, then track status from Downloads.',
            'steps' => [
                'Add assets to your download bucket from the asset grid or asset actions where available.',
                'Create a download / package from the Downloads or bucket UI.',
                'Open Downloads to copy links, track processing, or re-send access.',
            ],
            'route_name' => 'downloads.index',
            'route_bindings' => [],
            'page_label' => 'Downloads',
            'permissions' => [],
            'tags' => ['download', 'export', 'zip'],
            'related' => ['assets.browse', 'collections.share'],
            'routes' => ['downloads.index'],
            'page_context' => ['Downloads'],
            'priority' => 84,
            'in_common' => true,
            'common_sort' => 60,
        ],
        [
            'key' => 'team.invite_company',
            'title' => 'Invite people to the company',
            'aliases' => ['add user', 'team invites', 'workspace members'],
            'category' => 'Team',
            'short_answer' => 'Company admins invite users from Team; they receive email to join the workspace.',
            'steps' => [
                'Open Company → Team.',
                'Click Invite and enter email and role.',
                'The invitee accepts, completes any signup steps, and can be granted brand access.',
            ],
            'route_name' => 'companies.team',
            'route_bindings' => [],
            'deep_link' => [
                'route_name' => 'companies.team',
                'params' => [],
                'query' => [],
            ],
            'highlight' => [
                'selector' => 'team-invite-member',
                'label' => 'Invite Member',
            ],
            'page_label' => 'Company team',
            'permissions' => ['team.manage'],
            'tags' => ['invite', 'users', 'rbac'],
            'related' => ['team.brand_roles', 'company.settings'],
            'in_common' => true,
            'common_sort' => 70,
        ],
        [
            'key' => 'team.brand_roles',
            'title' => 'Assign or change brand roles',
            'aliases' => ['brand access', 'role on brand', 'permissions'],
            'category' => 'Team',
            'short_answer' => 'From Company → Team, edit a member’s brand access and pick the right brand role.',
            'steps' => [
                'Go to Company → Team.',
                'Select a member.',
                'Add brand access or change their brand role; save changes.',
            ],
            'route_name' => 'companies.team',
            'route_bindings' => [],
            'page_label' => 'Company team',
            'permissions' => ['team.manage'],
            'tags' => ['roles', 'brands', 'access'],
            'related' => ['team.invite_company', 'brand.settings'],
            'in_common' => false,
            'common_sort' => 520,
        ],
        [
            'key' => 'workspace.switch_brand',
            'title' => 'Switch the active brand',
            'aliases' => ['change brand', 'brand picker', 'different brand', 'wrong brand'],
            'category' => 'Workspace',
            'short_answer' => 'Use the workspace / brand controls in the header or user menu to change which brand you are working in.',
            'steps' => [
                'Open the user or workspace menu (top right).',
                'Choose another brand you have access to.',
                'Confirm navigation refreshes to that brand’s library and settings.',
            ],
            'route_name' => 'insights.overview',
            'route_bindings' => [],
            'page_label' => 'Insights overview',
            'permissions' => [],
            'tags' => ['brand', 'context', 'navigation'],
            'related' => ['brand.settings', 'assets.browse', 'workspace.switch_company'],
            'routes' => ['insights.overview', 'overview', 'assets.index', 'executions.index', 'collections.index', 'generative.index', 'downloads.index', 'brands.edit'],
            'priority' => 40,
            'in_common' => true,
            'common_sort' => 25,
        ],
        [
            'key' => 'workspace.switch_company',
            'title' => 'Switch or pick a company (workspace)',
            'aliases' => ['change company', 'company picker', 'which workspace', 'multi company', 'another organization'],
            'category' => 'Workspace',
            'short_answer' => 'From the user menu, open your company list to jump to another workspace you belong to.',
            'steps' => [
                'Click your avatar (top right) → open the workspace / company card.',
                'Select another company, or go to View all companies when you need the full picker.',
                'Wait for the switch to finish; you may be asked to pick a brand inside that company.',
            ],
            'route_name' => 'companies.index',
            'route_bindings' => [],
            'page_label' => 'Companies',
            'permissions' => [],
            'tags' => ['company', 'workspace', 'multi-tenant'],
            'related' => ['workspace.switch_brand', 'team.invite_company'],
            'routes' => ['companies.index'],
            'page_context' => ['Companies'],
            'priority' => 55,
            'in_common' => true,
            'common_sort' => 28,
        ],
        [
            'key' => 'brand.settings',
            'title' => 'Manage brand settings',
            'aliases' => ['brand page', 'edit brand', 'colors', 'logo'],
            'category' => 'Brands',
            'short_answer' => 'Brand settings cover identity, defaults, and configuration for the active brand.',
            'steps' => [
                'Switch to the brand you need (if you have several).',
                'Open Brand settings from the navigation / workspace entry.',
                'Update identity, guidelines links, or other options your role allows, then save.',
            ],
            'route_name' => 'brands.edit',
            'route_bindings' => ['brand' => 'active_brand'],
            'deep_link' => [
                'route_name' => 'brands.edit',
                'params' => ['brand' => 'active_brand'],
                'query' => [],
            ],
            'highlight' => [
                'selector' => 'brand-settings-nav',
                'label' => 'Brand settings (Overview sidebar)',
            ],
            'page_label' => 'Brand settings',
            'permissions' => ['brand_settings.manage'],
            'tags' => ['brand', 'settings'],
            'related' => ['manage.tags_fields_metadata', 'manage.categories_fields', 'approvals.queue'],
            'in_common' => true,
            'common_sort' => 80,
        ],
        [
            'key' => 'billing.plan',
            'title' => 'View billing and plan details',
            'aliases' => ['subscription', 'invoice', 'plan limits'],
            'category' => 'Billing',
            'short_answer' => 'Billing shows your subscription, usage-related add-ons, and links to invoices or the customer portal when enabled.',
            'steps' => [
                'Open Billing from the user menu (when you have access).',
                'Review current plan, seats, and add-ons.',
                'Use invoices or the customer portal links as needed.',
            ],
            'route_name' => 'billing',
            'route_bindings' => [],
            'page_label' => 'Billing',
            'permissions' => ['billing.view'],
            'tags' => ['billing', 'plan', 'stripe'],
            'related' => ['billing.upgrade', 'ai.credits_usage'],
            'in_common' => true,
            'common_sort' => 90,
        ],
        [
            'key' => 'billing.upgrade',
            'title' => 'Change or upgrade your plan',
            'aliases' => ['upgrade', 'plans', 'subscribe'],
            'category' => 'Billing',
            'short_answer' => 'Pick a new plan or adjust add-ons from the billing plans experience.',
            'steps' => [
                'Go to Billing → Plans (or the plans section within Billing).',
                'Compare plans and confirm checkout or upgrade steps.',
                'After purchase, verify features and limits on the overview.',
            ],
            'route_name' => 'billing.plans',
            'route_bindings' => [],
            'deep_link' => [
                'route_name' => 'billing.plans',
                'params' => [],
                'query' => [],
            ],
            'highlight' => [
                'selector' => 'billing-upgrade-plan',
                'label' => 'Plan upgrade button',
            ],
            'page_label' => 'Billing plans',
            'permissions' => ['billing.view'],
            'tags' => ['upgrade', 'subscription'],
            'related' => ['billing.plan'],
            'in_common' => false,
            'common_sort' => 530,
        ],
        [
            'key' => 'ai.credits_usage',
            'title' => 'View AI credits and feature usage',
            'aliases' => ['credits', 'usage', 'ai limits'],
            'category' => 'AI & insights',
            'short_answer' => 'Insights → Usage surfaces AI credit consumption and related usage context for your workspace when enabled.',
            'steps' => [
                'Open Insights from the navigation.',
                'Go to the Usage tab.',
                'Review credit usage, warnings, and per-feature breakdown when shown.',
            ],
            'route_name' => 'insights.usage',
            'route_bindings' => [],
            'page_label' => 'Insights — Usage',
            'permissions' => [],
            'tags' => ['ai', 'credits', 'usage'],
            'related' => ['ai.company_usage_panel', 'studio.generative'],
            'in_common' => true,
            'common_sort' => 100,
        ],
        [
            'key' => 'ai.company_usage_panel',
            'title' => 'Company AI usage (detailed)',
            'aliases' => ['ai usage report', 'tenant ai'],
            'category' => 'AI & insights',
            'short_answer' => 'Company settings includes an AI usage section for admins who can view detailed consumption.',
            'steps' => [
                'Open Company → Settings.',
                'Scroll to the AI usage / reporting section (requires permission).',
                'Adjust date range or export if your role supports it.',
            ],
            'route_name' => 'companies.settings',
            'route_bindings' => [],
            'page_label' => 'Company settings',
            'permissions' => ['ai.usage.view'],
            'tags' => ['ai', 'admin', 'reporting'],
            'related' => ['ai.credits_usage', 'company.settings'],
            'in_common' => false,
            'common_sort' => 540,
        ],
        [
            'key' => 'studio.generative',
            'title' => 'Use Studio (Generative beta)',
            'aliases' => ['editor', 'compositions', 'creative', 'generate', 'studio beta', 'ai layouts', 'variants'],
            'category' => 'Studio',
            'short_answer' => 'Studio (Generative beta) is the main nav entry for AI-assisted creative work and compositions when your workspace enables it.',
            'steps' => [
                'Open Studio from the main navigation (shown when Generative is enabled for your company).',
                'Start from an existing composition or template, or create a new one from the hub.',
                'Watch AI credit usage in-product; export or save results according to your brand rules.',
            ],
            'route_name' => 'generative.index',
            'route_bindings' => [],
            'page_label' => 'Studio',
            'permissions' => [],
            'tags' => ['studio', 'generative', 'creative'],
            'related' => ['ai.credits_usage', 'assets.browse', 'executions.hub'],
            'routes' => ['generative.index'],
            'page_context' => ['Studio'],
            'priority' => 88,
            'in_common' => true,
            'common_sort' => 110,
        ],
        [
            'key' => 'insights.ai_review',
            'title' => 'Review AI metadata and tag suggestions',
            'aliases' => ['suggestions', 'accept tags', 'review workspace'],
            'category' => 'AI & insights',
            'short_answer' => 'Insights → Review aggregates AI suggestions so you can accept or reject in bulk where permitted.',
            'steps' => [
                'Navigate to Insights → Review.',
                'Filter by suggestion type or brand as needed.',
                'Accept, edit-accept, or reject suggestions following your governance rules.',
            ],
            'route_name' => 'insights.review',
            'route_bindings' => [],
            'page_label' => 'Insights — Review',
            'permissions' => [],
            'tags' => ['ai', 'review', 'metadata'],
            'related' => ['assets.edit_single_metadata', 'approvals.queue', 'insights.metadata_coverage'],
            'routes' => ['insights.review'],
            'page_context' => ['Insights'],
            'priority' => 82,
            'in_common' => true,
            'common_sort' => 120,
        ],
        [
            'key' => 'approvals.queue',
            'title' => 'Review contributor asset approvals',
            'aliases' => ['approve assets', 'pending approvals', 'submissions'],
            'category' => 'Approvals',
            'short_answer' => 'Approvers use the brand Approvals page to publish or reject submitted assets.',
            'steps' => [
                'Open Brand → Approvals (or the Approvals entry for your brand).',
                'Open a pending submission.',
                'Approve, reject with feedback, or request changes per workflow.',
            ],
            'route_name' => 'brands.approvals',
            'route_bindings' => ['brand' => 'active_brand'],
            'page_label' => 'Brand approvals',
            'permissions' => [],
            'tags' => ['approvals', 'governance'],
            'related' => ['insights.ai_review', 'assets.edit_single_metadata', 'prostaff.creators_tab'],
            'routes' => ['brands.approvals'],
            'page_context' => ['Brand settings'],
            'priority' => 84,
            'in_common' => true,
            'common_sort' => 130,
        ],
        [
            'key' => 'manage.tags_fields_metadata',
            'title' => 'Manage tags, fields, and metadata structure',
            'aliases' => [
                'manage tags',
                'edit tag list',
                'delete a tag globally',
                'create custom field',
                'manage fields',
                'field values',
                'metadata settings',
                'taxonomy',
                'metadata registry',
                'categories and fields',
                'rename tag',
                'metadata structure',
                'configure metadata',
            ],
            'category' => 'Manage',
            'short_answer' => 'Use Manage (and, for advanced company-wide definitions, Company metadata admin tools) to configure the tag taxonomy, custom fields, allowed values, categories, and how metadata is structured. This is administration: it does not edit metadata on a specific asset. To change tags or fields on files, open one asset or use bulk edit on the Assets grid.',
            'steps' => [
                'Go to Manage → Categories, Tags, Values, Fields, or Structure depending on what you are changing.',
                'Adjust categories, tag vocabulary, field placement, or allowed values for the active brand.',
                'For tenant-wide field definitions or registry visibility, use Company → Metadata fields / registry when you have admin access.',
                'After changes, editors apply values on assets from the asset drawer or bulk actions—not from this Manage area.',
            ],
            'route_name' => 'manage.categories',
            'route_bindings' => [],
            'deep_link' => [
                'route_name' => 'manage.categories',
                'params' => [],
                'query' => [],
            ],
            'highlight' => [
                'selector' => 'manage-metadata-structure',
                'label' => 'Manage library metadata',
            ],
            'page_label' => 'Manage',
            'permissions' => [],
            'tags' => ['manage', 'metadata', 'taxonomy', 'fields', 'tags', 'admin'],
            'related' => ['manage.categories_fields', 'manage.tags', 'manage.values', 'tenant.metadata_registry', 'assets.edit_single_metadata', 'assets.bulk_edit_metadata'],
            'routes' => [
                'manage.categories',
                'manage.tags',
                'manage.values',
                'manage.structure',
                'manage.fields',
                'tenant.metadata.fields.index',
                'tenant.metadata.fields.show',
                'tenant.metadata.registry.index',
            ],
            'page_context' => ['Manage', 'Company'],
            'priority' => 94,
            'in_common' => false,
            'common_sort' => 520,
        ],
        [
            'key' => 'manage.categories_fields',
            'title' => 'Manage categories, folders, and fields',
            'aliases' => ['folder structure', 'category editor', 'field visibility by category'],
            'category' => 'Manage',
            'short_answer' => 'Manage → Categories organizes folder structure and which fields appear for the active brand. This configures the library—it does not change metadata values on a particular asset. To change values on files, use the asset drawer or bulk edit on Assets.',
            'steps' => [
                'Open Manage → Categories (use Structure first if you need hierarchy changes).',
                'Edit categories, reorder, or adjust field visibility for the brand.',
                'Coordinate with admins when changing fields that affect many assets.',
                'Editors then fill in metadata on assets from the grid—not from this screen.',
            ],
            'route_name' => 'manage.categories',
            'route_bindings' => [],
            'page_label' => 'Manage — Categories',
            'permissions' => ['brand_settings.manage'],
            'tags' => ['categories', 'fields', 'taxonomy'],
            'related' => ['manage.tags_fields_metadata', 'manage.tags', 'manage.values', 'manage.structure'],
            'routes' => ['manage.categories'],
            'page_context' => ['Manage'],
            'priority' => 68,
            'in_common' => false,
            'common_sort' => 550,
        ],
        [
            'key' => 'manage.tags',
            'title' => 'Manage tags',
            'aliases' => ['tag library', 'controlled vocabulary', 'global tag list'],
            'category' => 'Manage',
            'short_answer' => 'Manage → Tags maintains the workspace tag list (merge, rename, retire). To add or remove a tag on one asset only, open that asset’s drawer or use bulk edit—not this page.',
            'steps' => [
                'Go to Manage → Tags.',
                'Merge, rename, or purge tags according to policy.',
                'Confirm downstream assets reflect updates after operations complete.',
            ],
            'route_name' => 'manage.tags',
            'route_bindings' => [],
            'page_label' => 'Manage — Tags',
            'permissions' => ['brand_settings.manage'],
            'tags' => ['tags', 'taxonomy'],
            'related' => ['manage.tags_fields_metadata', 'manage.categories_fields', 'manage.values'],
            'routes' => ['manage.tags'],
            'page_context' => ['Manage'],
            'priority' => 64,
            'in_common' => false,
            'common_sort' => 560,
        ],
        [
            'key' => 'manage.values',
            'title' => 'Manage metadata values',
            'aliases' => ['allowed values', 'options', 'picklists'],
            'category' => 'Manage',
            'short_answer' => 'Manage → Values maintains allowed option lists for structured fields (picklists). Changing values here is configuration—not the same as editing a field on a single asset in the drawer.',
            'steps' => [
                'Open Manage → Values.',
                'Select a field or value group to edit.',
                'Add, rename, or retire values carefully to avoid breaking existing assets.',
            ],
            'route_name' => 'manage.values',
            'route_bindings' => [],
            'page_label' => 'Manage — Values',
            'permissions' => ['brand_settings.manage'],
            'tags' => ['metadata', 'values'],
            'related' => ['manage.tags_fields_metadata', 'manage.categories_fields', 'tenant.metadata_fields'],
            'routes' => ['manage.values'],
            'page_context' => ['Manage'],
            'priority' => 62,
            'in_common' => false,
            'common_sort' => 570,
        ],
        [
            'key' => 'tenant.metadata_fields',
            'title' => 'Tenant custom metadata fields (admin)',
            'aliases' => ['field definitions', 'company field admin'],
            'category' => 'Admin',
            'short_answer' => 'Advanced admin: define or adjust tenant-level metadata fields and how brands attach them. This is not where you edit values on an individual asset—use the asset drawer or bulk edit for that.',
            'steps' => [
                'Ensure you have tenant metadata field permissions.',
                'Use Manage → Fields for brand-facing placement and Company metadata admin tools for tenant-wide definitions when applicable.',
                'Coordinate with library managers before altering production fields.',
            ],
            'route_name' => 'manage.fields',
            'route_bindings' => [],
            'page_label' => 'Manage — Fields',
            'permissions' => ['metadata.tenant.field.manage'],
            'tags' => ['metadata', 'tenant', 'admin'],
            'related' => ['manage.tags_fields_metadata', 'tenant.metadata_registry', 'manage.categories_fields', 'company.settings'],
            'routes' => ['manage.fields', 'tenant.metadata.fields.index'],
            'page_context' => ['Manage', 'Company'],
            'in_common' => false,
            'common_sort' => 580,
        ],
        [
            'key' => 'support.open_ticket',
            'title' => 'Contact Jackpot support',
            'aliases' => ['help desk', 'ticket', 'issue', 'file a ticket', 'open a case', 'something broken', 'report a bug'],
            'category' => 'Support',
            'short_answer' => 'Open a support ticket from the in-app Support section so your workspace context travels with the request.',
            'steps' => [
                'Go to Support → Tickets.',
                'Create a ticket with a clear subject and reproduction steps.',
                'Attach examples or links (non-secret) and watch for email replies.',
            ],
            'route_name' => 'support.tickets.index',
            'route_bindings' => [],
            'page_label' => 'Support tickets',
            'permissions' => [],
            'tags' => ['support', 'help'],
            'related' => ['account.profile', 'notifications.preferences'],
            'routes' => ['support.tickets.index', 'support.tickets.create'],
            'page_context' => ['Support'],
            'priority' => 50,
            'in_common' => true,
            'common_sort' => 140,
        ],
        [
            'key' => 'notifications.preferences',
            'title' => 'Notification preferences',
            'aliases' => ['email alerts', 'bell', 'push'],
            'category' => 'Account',
            'short_answer' => 'Use the notification bell for activity; tune delivery preferences from your profile / notification settings where available.',
            'steps' => [
                'Click the bell in the header for recent in-app notifications.',
                'Open Profile / account settings for email or channel preferences when exposed.',
                'Adjust categories you care about and save.',
            ],
            'route_name' => 'profile.index',
            'route_bindings' => [],
            'page_label' => 'Profile',
            'permissions' => [],
            'tags' => ['notifications', 'alerts'],
            'related' => ['support.open_ticket', 'account.profile'],
            'in_common' => true,
            'common_sort' => 150,
        ],
        [
            'key' => 'account.profile',
            'title' => 'Account profile and security',
            'aliases' => ['password', 'avatar', 'my account'],
            'category' => 'Account',
            'short_answer' => 'Profile holds your personal settings: name, avatar, password, and data export options.',
            'steps' => [
                'Choose Profile from the user menu.',
                'Update profile details or password.',
                'Review privacy / export tools if your organization allows self-service.',
            ],
            'route_name' => 'profile.index',
            'route_bindings' => [],
            'page_label' => 'Profile',
            'permissions' => [],
            'tags' => ['account', 'security', 'profile'],
            'related' => ['notifications.preferences', 'company.settings'],
            'in_common' => true,
            'common_sort' => 160,
        ],
        [
            'key' => 'company.settings',
            'title' => 'Company workspace settings',
            'aliases' => ['tenant settings', 'workspace admin'],
            'category' => 'Company',
            'short_answer' => 'Company settings cover workspace-wide options such as downloads policy, AI controls, and related admin surfaces.',
            'steps' => [
                'Open Company → Settings.',
                'Review each section you have access to.',
                'Apply changes deliberately—some affect all brands and users.',
            ],
            'route_name' => 'companies.settings',
            'route_bindings' => [],
            'page_label' => 'Company settings',
            'permissions' => ['company_settings.view'],
            'tags' => ['company', 'admin', 'settings'],
            'related' => ['team.invite_company', 'ai.company_usage_panel', 'company.permissions_page', 'company.activity'],
            'routes' => ['companies.settings'],
            'page_context' => ['Company settings'],
            'priority' => 72,
            'in_common' => false,
            'common_sort' => 590,
        ],
        [
            'key' => 'executions.hub',
            'title' => 'Executions (Brand Intelligence runs)',
            'aliases' => ['deliverables', 'scoring runs', 'brand intelligence', 'execution queue', 'my executions'],
            'category' => 'Executions',
            'short_answer' => 'Executions is the hub for Brand Intelligence scoring workflows tied to your brand—start runs, track progress, and open results from the main nav.',
            'steps' => [
                'Click Executions in the top navigation.',
                'Create or resume a run from the hub; pick the scope your role allows.',
                'Open finished executions to review scores, rationale, and recommended follow-ups.',
            ],
            'route_name' => 'executions.index',
            'route_bindings' => [],
            'deep_link' => [
                'route_name' => 'executions.index',
                'params' => [],
                'query' => [],
            ],
            'page_label' => 'Executions',
            'permissions' => [],
            'tags' => ['executions', 'brand intelligence', 'scoring'],
            'related' => ['assets.browse', 'collections.campaign_identity', 'studio.generative'],
            'routes' => ['executions.index'],
            'page_context' => ['Executions'],
            'priority' => 90,
            'in_common' => true,
            'common_sort' => 42,
        ],
        [
            'key' => 'overview.tasks',
            'title' => 'Overview tasks and workspace home',
            'aliases' => ['dashboard', 'home', 'my tasks', 'to do', 'getting started'],
            'category' => 'Overview',
            'short_answer' => 'Overview → Tasks is your workspace home for assigned work, shortcuts, and signals across brands.',
            'steps' => [
                'Open Overview from the nav (or go to /app/overview).',
                'Review tasks, alerts, and quick links for the active brand.',
                'Use sub-pages like Creator Home or Insights from the Overview menu when they appear for your role.',
            ],
            'route_name' => 'overview',
            'route_bindings' => [],
            'page_label' => 'Overview',
            'permissions' => [],
            'tags' => ['overview', 'tasks', 'home'],
            'related' => ['insights.overview_digest', 'prostaff.creator_home', 'workspace.switch_brand'],
            'routes' => ['overview', 'app'],
            'page_context' => ['Overview'],
            'priority' => 78,
            'in_common' => true,
            'common_sort' => 18,
        ],
        [
            'key' => 'insights.overview_digest',
            'title' => 'Insights Overview (metrics at a glance)',
            'aliases' => ['analytics home', 'kpi', 'dashboard metrics', 'how are we doing'],
            'category' => 'AI & insights',
            'short_answer' => 'Insights → Overview summarizes adoption, metadata health, and key usage signals for admins and power users.',
            'steps' => [
                'Go to Insights from the Overview submenu or direct nav.',
                'Start on Overview for headline metrics and trends.',
                'Drill into Metadata, Usage, Activity, or Review from the Insights tabs as needed.',
            ],
            'route_name' => 'insights.overview',
            'route_bindings' => [],
            'page_label' => 'Insights — Overview',
            'permissions' => [],
            'tags' => ['insights', 'analytics', 'overview'],
            'related' => ['insights.metadata_coverage', 'insights.activity', 'ai.credits_usage'],
            'routes' => ['insights.overview', 'insights.overview.metadata-analytics'],
            'page_context' => ['Insights'],
            'priority' => 80,
            'in_common' => false,
            'common_sort' => 600,
        ],
        [
            'key' => 'insights.metadata_coverage',
            'title' => 'Metadata coverage and field analytics',
            'aliases' => ['missing metadata', 'field fill rate', 'taxonomy health', 'metadata dashboard', 'metadata coverage'],
            'category' => 'AI & insights',
            'short_answer' => 'Insights → Metadata is for auditing how completely assets use governed fields and where gaps cluster. It is an analytics view—not the place to edit one asset’s values. To fix a specific file, open it on Assets; to fix many, use bulk edit; to change the field/tag system itself, use Manage tags, fields, and metadata structure.',
            'steps' => [
                'Navigate to Insights → Metadata.',
                'Filter by brand, category, or time range when available.',
                'Use the report to prioritize follow-up: bulk metadata updates on Assets, single-asset fixes in the drawer, or structural changes in Manage / Company metadata admin.',
            ],
            'route_name' => 'insights.metadata',
            'route_bindings' => [],
            'page_label' => 'Insights — Metadata',
            'permissions' => [],
            'tags' => ['metadata', 'coverage', 'analytics'],
            'related' => ['manage.tags_fields_metadata', 'assets.bulk_edit_metadata', 'assets.edit_single_metadata', 'insights.ai_review', 'manage.categories_fields'],
            'routes' => ['insights.metadata'],
            'page_context' => ['Insights'],
            'priority' => 92,
            'in_common' => false,
            'common_sort' => 610,
        ],
        [
            'key' => 'insights.activity',
            'title' => 'Activity and change history (Insights)',
            'aliases' => ['audit trail', 'who changed what', 'recent activity', 'event log'],
            'category' => 'AI & insights',
            'short_answer' => 'Insights → Activity surfaces recent DAM events so you can trace uploads, edits, and governance actions.',
            'steps' => [
                'Open Insights → Activity.',
                'Narrow by actor, object, or timeframe depending on filters.',
                'Follow links back to assets or collections when you need to remediate.',
            ],
            'route_name' => 'insights.activity',
            'route_bindings' => [],
            'page_label' => 'Insights — Activity',
            'permissions' => [],
            'tags' => ['activity', 'audit', 'history'],
            'related' => ['company.activity', 'assets.browse'],
            'routes' => ['insights.activity'],
            'page_context' => ['Insights'],
            'priority' => 74,
            'in_common' => false,
            'common_sort' => 620,
        ],
        [
            'key' => 'insights.creator_workspace',
            'title' => 'Creator approvals (Insights)',
            'aliases' => ['creator submissions', 'external creators', 'prostaff queue'],
            'category' => 'AI & insights',
            'short_answer' => 'Insights → Creator aggregates pending creator submissions that need brand review when Creator workflows are enabled.',
            'steps' => [
                'Open Insights → Creator.',
                'Review pending items and open each for detail.',
                'Approve, reject with notes, or route work per your governance playbook.',
            ],
            'route_name' => 'insights.creator',
            'route_bindings' => [],
            'page_label' => 'Insights — Creator',
            'permissions' => [],
            'tags' => ['creator', 'approvals', 'proststaff'],
            'related' => ['approvals.queue', 'prostaff.creators_tab', 'overview.tasks'],
            'routes' => ['insights.creator'],
            'page_context' => ['Insights'],
            'priority' => 72,
            'in_common' => false,
            'common_sort' => 630,
        ],
        [
            'key' => 'manage.structure',
            'title' => 'Manage library structure',
            'aliases' => ['folder tree', 'category tree', 'reorder folders', 'where fields show up'],
            'category' => 'Manage',
            'short_answer' => 'Manage → Structure adjusts category hierarchy and relationships for the brand library—admin configuration only. To change metadata on a specific asset, use the asset drawer or bulk edit instead.',
            'steps' => [
                'Open Manage → Structure.',
                'Adjust the tree, merges, or ordering according to your taxonomy policy.',
                'Validate downstream effects in Manage → Categories; editors still apply values per asset from Assets.',
            ],
            'route_name' => 'manage.structure',
            'route_bindings' => [],
            'page_label' => 'Manage — Structure',
            'permissions' => ['brand_settings.manage'],
            'tags' => ['structure', 'taxonomy', 'categories'],
            'related' => ['manage.tags_fields_metadata', 'manage.categories_fields', 'manage.tags'],
            'routes' => ['manage.structure'],
            'page_context' => ['Manage'],
            'priority' => 70,
            'in_common' => false,
            'common_sort' => 640,
        ],
        [
            'key' => 'guidelines.read_portal',
            'title' => 'Read Brand Guidelines',
            'aliases' => ['brand book', 'style guide', 'colors and fonts', 'public guidelines'],
            'category' => 'Brand guidelines',
            'short_answer' => 'The guidelines experience summarizes voice, color, typography, and usage rules curated for each brand.',
            'steps' => [
                'Use Brand Guidelines from the user menu or go to /app/brand-guidelines for the active brand.',
                'Navigate sections (colors, type, imagery, etc.) using the sidebar.',
                'Download packaged assets when your admins expose them.',
            ],
            'route_name' => 'brands.guidelines.index',
            'route_bindings' => ['brand' => 'active_brand'],
            'deep_link' => [
                'route_name' => 'brand-guidelines.index',
                'params' => [],
                'query' => [],
            ],
            'page_label' => 'Brand guidelines',
            'permissions' => ['view brand'],
            'tags' => ['guidelines', 'brand', 'read-only'],
            'related' => ['guidelines.builder_wizard', 'brand.settings'],
            'routes' => ['brands.guidelines.index', 'brand-guidelines.index'],
            'page_context' => ['Brand guidelines'],
            'priority' => 82,
            'in_common' => true,
            'common_sort' => 125,
        ],
        [
            'key' => 'guidelines.builder_wizard',
            'title' => 'Build or refresh Brand DNA / Guidelines',
            'aliases' => ['guidelines wizard', 'brand dna builder', 'ingest pdf', 'publish guidelines'],
            'category' => 'Brand guidelines',
            'short_answer' => 'Admins use the Brand DNA / Guidelines builder to research, draft, and publish an internal brand system.',
            'steps' => [
                'From Brand settings or DNA tools, open the builder experience.',
                'Run research, attach references, and resolve AI suggestions with human review.',
                'Publish when ready so downstream Studio and metadata experiences pick up the latest truth.',
            ],
            'route_name' => 'brands.brand-guidelines.builder',
            'route_bindings' => ['brand' => 'active_brand'],
            'page_label' => 'Guidelines builder',
            'permissions' => ['brand_settings.manage'],
            'tags' => ['guidelines', 'dna', 'admin'],
            'related' => ['guidelines.read_portal', 'brand.settings', 'brand.research_lab'],
            'routes' => ['brands.brand-guidelines.builder', 'brands.research.show', 'brands.review.show'],
            'page_context' => ['Brand guidelines', 'Brand settings'],
            'priority' => 68,
            'in_common' => false,
            'common_sort' => 650,
        ],
        [
            'key' => 'brand.research_lab',
            'title' => 'Brand research (web + PDF signals)',
            'aliases' => ['competitive research', 'run brand research', 'ingest website'],
            'category' => 'Brands',
            'short_answer' => 'The dedicated Research page collects external signals before you lock DNA or guideline drafts.',
            'steps' => [
                'Open Brand → Research (from settings or builder flows).',
                'Trigger analysis, attach PDFs, or rerun when positioning changes.',
                'Advance to Review only after stakeholders sign off on the captured facts.',
            ],
            'route_name' => 'brands.research.show',
            'route_bindings' => ['brand' => 'active_brand'],
            'page_label' => 'Brand research',
            'permissions' => ['brand_settings.manage'],
            'tags' => ['research', 'brand', 'ai'],
            'related' => ['guidelines.builder_wizard', 'brand.settings'],
            'routes' => ['brands.research.show'],
            'page_context' => ['Brand settings'],
            'priority' => 60,
            'in_common' => false,
            'common_sort' => 660,
        ],
        [
            'key' => 'collections.campaign_identity',
            'title' => 'Collection campaign identity',
            'aliases' => ['campaign brief', 'collection brief', 'alignment', 'creative brief in collection'],
            'category' => 'Collections',
            'short_answer' => 'Campaign identity on a collection captures messaging constraints so assets and executions stay on-brief.',
            'steps' => [
                'Open the collection and find the Campaign / identity panel.',
                'Enter required messaging, audiences, or mandatory claims.',
                'Save and notify collaborators; link executions or downloads from the same collection when needed.',
            ],
            'route_name' => 'collections.index',
            'route_bindings' => [],
            'page_label' => 'Collections',
            'permissions' => [],
            'tags' => ['campaign', 'collections', 'brief'],
            'related' => ['collections.manage', 'executions.hub', 'assets.browse'],
            'routes' => ['collections.index'],
            'page_context' => ['Collections'],
            'priority' => 62,
            'in_common' => false,
            'common_sort' => 670,
        ],
        [
            'key' => 'collection.collaborator_access',
            'title' => 'Collection-only access (external collaborators)',
            'aliases' => ['shared collection', 'guest collection', 'collection invite', 'no brand access'],
            'category' => 'Collections',
            'short_answer' => 'Some users only receive collection grants—navigation is limited to those collections and related downloads.',
            'steps' => [
                'Accept the collection invite email and sign in when prompted.',
                'Use the Collections tab to switch between collections shared with you.',
                'Download or comment according to the permissions on the invite; request broader brand access from your admin if needed.',
            ],
            'route_name' => 'collection-invite.landing',
            'route_bindings' => [],
            'page_label' => 'Collection access',
            'permissions' => [],
            'tags' => ['collection', 'guest', 'external'],
            'related' => ['collections.share', 'downloads.package'],
            'routes' => ['collection-invite.landing', 'collection-invite.view'],
            'page_context' => ['Collections'],
            'priority' => 92,
            'in_common' => false,
            'common_sort' => 680,
        ],
        [
            'key' => 'onboarding.first_run',
            'title' => 'New workspace onboarding',
            'aliases' => ['first time setup', 'getting started wizard', 'new company setup', 'upload logo onboarding'],
            'category' => 'Workspace',
            'short_answer' => 'Onboarding walks new admins through brand shell, starter assets, and activation steps before the full DAM unlocks.',
            'steps' => [
                'Follow the on-screen checklist after you create or join a workspace.',
                'Upload logos, invite teammates, and configure starter categories when prompted.',
                'Click Activate / Complete only when required steps are finished—skipping may limit features.',
            ],
            'route_name' => 'onboarding.show',
            'route_bindings' => [],
            'page_label' => 'Onboarding',
            'permissions' => [],
            'tags' => ['onboarding', 'setup', 'new user'],
            'related' => ['team.invite_company', 'brand.settings'],
            'routes' => ['onboarding.show', 'onboarding.verify-email'],
            'page_context' => ['Onboarding'],
            'priority' => 95,
            'in_common' => false,
            'common_sort' => 690,
        ],
        [
            'key' => 'company.permissions_page',
            'title' => 'Understand company roles and permissions',
            'aliases' => ['role matrix', 'what can members do', 'permission table', 'rbac'],
            'category' => 'Company',
            'short_answer' => 'Company → Permissions compares built-in roles so admins can reason about access before inviting users.',
            'steps' => [
                'Open Company → Permissions (admins and owners only).',
                'Scan the grid for capabilities like billing, settings, or asset delete.',
                'Pair this with Team when planning invites or promotions.',
            ],
            'route_name' => 'companies.permissions',
            'route_bindings' => [],
            'page_label' => 'Company permissions',
            'permissions' => ['team.manage'],
            'tags' => ['permissions', 'roles', 'admin'],
            'related' => ['team.invite_company', 'team.brand_roles', 'company.settings'],
            'routes' => ['companies.permissions'],
            'page_context' => ['Company'],
            'priority' => 58,
            'in_common' => false,
            'common_sort' => 700,
        ],
        [
            'key' => 'company.activity',
            'title' => 'Company activity log',
            'aliases' => ['workspace audit', 'admin activity', 'security log'],
            'category' => 'Company',
            'short_answer' => 'Company → Activity lists important workspace events for compliance and troubleshooting.',
            'steps' => [
                'Navigate to Company → Activity.',
                'Filter or search for the user or action you need.',
                'Export or escalate findings according to your internal policy.',
            ],
            'route_name' => 'companies.activity',
            'route_bindings' => [],
            'page_label' => 'Company activity',
            'permissions' => ['activity_logs.view'],
            'tags' => ['activity', 'audit', 'company'],
            'related' => ['company.settings', 'insights.activity'],
            'routes' => ['companies.activity'],
            'page_context' => ['Company'],
            'priority' => 56,
            'in_common' => false,
            'common_sort' => 710,
        ],
        [
            'key' => 'agency.client_portfolio',
            'title' => 'Agency dashboard and client workspaces',
            'aliases' => ['agency clients', 'managed companies', 'incubation', 'switch client'],
            'category' => 'Agency',
            'short_answer' => 'Agency operators use the Agency dashboard to provision clients, monitor health, and jump between managed workspaces.',
            'steps' => [
                'Switch into your agency tenant or an agency-managed client from the workspace picker.',
                'Open Agency dashboard from the agency strip or user menu shortcuts.',
                'Use client rows to jump into brands, billing escalations, or support tasks.',
            ],
            'route_name' => 'agency.dashboard',
            'route_bindings' => [],
            'page_label' => 'Agency dashboard',
            'permissions' => [],
            'tags' => ['agency', 'clients', 'managed'],
            'related' => ['workspace.switch_company', 'company.settings'],
            'routes' => ['agency.dashboard'],
            'page_context' => ['Agency'],
            'priority' => 85,
            'in_common' => false,
            'common_sort' => 720,
        ],
        [
            'key' => 'prostaff.creators_tab',
            'title' => 'Creators tab (manage external contributors)',
            'aliases' => ['prostaff', 'contributor dashboard', 'invite creators', 'creator roster'],
            'category' => 'Creators',
            'short_answer' => 'Brand admins manage prostaff / creator memberships from Brand → Creators when the module is enabled.',
            'steps' => [
                'Open Brand settings and choose the Creators tab (or the Creators nav entry when visible).',
                'Invite, suspend, or adjust creator roles.',
                'Pair with Approvals to ensure submissions route to the right reviewers.',
            ],
            'route_name' => 'brands.creators',
            'route_bindings' => ['brand' => 'active_brand'],
            'page_label' => 'Brand creators',
            'permissions' => [],
            'tags' => ['creators', 'proststaff', 'contributors'],
            'related' => ['approvals.queue', 'insights.creator_workspace', 'prostaff.creator_home'],
            'routes' => ['brands.creators', 'brands.creators.show'],
            'page_context' => ['Brand settings'],
            'priority' => 70,
            'in_common' => false,
            'common_sort' => 730,
        ],
        [
            'key' => 'prostaff.creator_home',
            'title' => 'Creator Home (contributor tasks)',
            'aliases' => ['my submissions', 'fix rejected upload', 'creator progress'],
            'category' => 'Creators',
            'short_answer' => 'Creator Home highlights work contributors must finish—especially resubmissions after rejection.',
            'steps' => [
                'Open Overview → Creator Home when your account has creator access.',
                'Resolve rejected items by uploading replacements or fixing metadata.',
                'Watch counts in the nav badge for urgent follow-ups.',
            ],
            'route_name' => 'overview.creator-progress',
            'route_bindings' => [],
            'page_label' => 'Creator Home',
            'permissions' => [],
            'tags' => ['creator', 'tasks', 'submissions'],
            'related' => ['assets.upload', 'approvals.queue', 'prostaff.creators_tab'],
            'routes' => ['overview.creator-progress'],
            'page_context' => ['Overview'],
            'priority' => 88,
            'in_common' => false,
            'common_sort' => 740,
        ],
        [
            'key' => 'downloads.manage_delivery',
            'title' => 'Manage download links (expiry, access, re-send)',
            'aliases' => ['revoke download', 'extend link', 'password protect download', 'regenerate zip'],
            'category' => 'Downloads',
            'short_answer' => 'From Downloads you can change access windows, regenerate packages, or revoke links when collateral rotates.',
            'steps' => [
                'Open Downloads and select the package.',
                'Use settings actions to extend, revoke, change password mode, or regenerate.',
                'Notify recipients with updated instructions when links change.',
            ],
            'route_name' => 'downloads.index',
            'route_bindings' => [],
            'page_label' => 'Downloads',
            'permissions' => [],
            'tags' => ['downloads', 'security', 'links'],
            'related' => ['downloads.package', 'collections.share'],
            'routes' => ['downloads.index'],
            'page_context' => ['Downloads'],
            'priority' => 70,
            'in_common' => false,
            'common_sort' => 750,
        ],
        [
            'key' => 'assets.archive_trash',
            'title' => 'Archive, trash, and restore assets',
            'aliases' => ['delete asset', 'soft delete', 'bring back', 'recover file'],
            'category' => 'Assets',
            'short_answer' => 'Assets can be archived or moved to trash depending on policy; restores are available while retention allows.',
            'steps' => [
                'Select an asset (or bulk select) in the grid.',
                'Choose Archive or Move to trash from the actions menu.',
                'Use trash or archive views to restore or permanently delete when you have permission.',
            ],
            'route_name' => 'assets.index',
            'route_bindings' => [],
            'page_label' => 'Assets',
            'permissions' => [],
            'tags' => ['archive', 'trash', 'lifecycle'],
            'related' => ['assets.browse', 'approvals.queue'],
            'routes' => ['assets.index'],
            'page_context' => ['Assets'],
            'priority' => 55,
            'in_common' => false,
            'common_sort' => 760,
        ],
        [
            'key' => 'tenant.metadata_registry',
            'title' => 'Tenant metadata registry (advanced admin)',
            'aliases' => ['field library', 'company metadata schema', 'registry visibility', 'system fields reveal'],
            'category' => 'Admin',
            'short_answer' => 'The tenant metadata registry is an advanced company-admin surface for field visibility, system seeds, and registry-wide operations. It configures the metadata system—not day-to-day values on individual assets (use the asset drawer or bulk edit for those).',
            'steps' => [
                'Open Company → Tenant metadata registry (or the registry route your workspace exposes) when you have metadata admin rights.',
                'Review field visibility, suppressed categories, or pending system reveals according to your change process.',
                'Coordinate with brand librarians before operations that affect many assets.',
            ],
            'route_name' => 'tenant.metadata.registry.index',
            'route_bindings' => [],
            'page_label' => 'Tenant metadata registry',
            'permissions' => ['metadata.tenant.field.manage'],
            'tags' => ['metadata', 'tenant', 'registry', 'admin'],
            'related' => ['manage.tags_fields_metadata', 'tenant.metadata_fields', 'manage.categories_fields'],
            'routes' => ['tenant.metadata.registry.index', 'tenant.metadata.fields.index', 'tenant.metadata.fields.show'],
            'page_context' => ['Company'],
            'priority' => 60,
            'in_common' => false,
            'common_sort' => 770,
        ],
    ],
];
