<?php

/**
 * Structured in-app help actions for Jackpot.
 *
 * Consumed by HelpActionService and GET /app/help/actions.
 * See docs/help-actions.md for AI / retrieval guidance.
 */
return [
    'actions' => [
        [
            'key' => 'assets.upload',
            'title' => 'Upload new assets',
            'aliases' => ['add files', 'ingest', 'import media'],
            'category' => 'Assets',
            'short_answer' => 'Open the Assets library and use the upload flow to add files; Jackpot processes them in the background.',
            'steps' => [
                'Go to Assets.',
                'Click Upload (or open the upload dialog from the library toolbar).',
                'Choose files or drag them into the drop zone and complete any required metadata.',
                'Wait for processing; new rows appear in the grid as derivatives complete.',
            ],
            'route_name' => 'assets.index',
            'route_bindings' => [],
            'deep_link' => [
                'route_name' => 'assets.index',
                'params' => [],
                'query' => [],
            ],
            'highlight' => [
                'selector' => 'assets-upload',
                'label' => 'Add Asset',
            ],
            'page_label' => 'Assets',
            'permissions' => ['asset.upload'],
            'tags' => ['upload', 'files', 'dam'],
            'related' => ['assets.staged', 'assets.processing'],
            'routes' => ['assets.index'],
            'page_context' => ['Assets'],
            'priority' => 90,
            'in_common' => true,
            'common_sort' => 10,
        ],
        [
            'key' => 'assets.browse',
            'title' => 'Browse and open assets',
            'aliases' => ['find asset', 'search library', 'asset grid'],
            'category' => 'Assets',
            'short_answer' => 'Use the Assets grid, filters, and saved views to find work; open an asset to preview details and metadata.',
            'steps' => [
                'Open Assets from the main navigation.',
                'Use filters, categories, or search to narrow the list.',
                'Click an asset to open the detail / drawer experience.',
            ],
            'route_name' => 'assets.index',
            'route_bindings' => [],
            'page_label' => 'Assets',
            'permissions' => [],
            'tags' => ['library', 'grid', 'search'],
            'related' => ['assets.metadata_edit', 'collections.add_assets'],
            'routes' => ['assets.index'],
            'page_context' => ['Assets'],
            'priority' => 85,
            'in_common' => true,
            'common_sort' => 20,
        ],
        [
            'key' => 'assets.metadata_edit',
            'title' => 'Edit asset metadata',
            'aliases' => ['tags', 'fields', 'properties', 'descriptions'],
            'category' => 'Assets',
            'short_answer' => 'Open an asset and edit metadata fields you have rights to; some changes may go through approval depending on your role.',
            'steps' => [
                'From Assets, open the asset you need.',
                'Expand the metadata panel / drawer.',
                'Edit fields, tags, or values and save.',
                'If your workspace uses approvals, watch for pending or rejected states and follow up in Approvals or Review.',
            ],
            'route_name' => 'assets.index',
            'route_bindings' => [],
            'page_label' => 'Assets',
            'permissions' => ['metadata.edit_post_upload'],
            'tags' => ['metadata', 'fields', 'tags'],
            'related' => ['insights.ai_review', 'assets.browse'],
            'routes' => ['assets.index'],
            'page_context' => ['Assets'],
            'priority' => 78,
            'in_common' => true,
            'common_sort' => 30,
        ],
        [
            'key' => 'assets.staged',
            'title' => 'Work with staged uploads',
            'aliases' => ['draft uploads', 'incomplete upload'],
            'category' => 'Assets',
            'short_answer' => 'Staged uploads are in-progress or held before finalizing into the library.',
            'steps' => [
                'Open Assets → Staged (or the staged uploads view from the library).',
                'Review each staged item and complete required metadata or fixes.',
                'Finalize or discard items according to your workflow.',
            ],
            'route_name' => 'assets.staged',
            'route_bindings' => [],
            'page_label' => 'Staged uploads',
            'permissions' => [],
            'tags' => ['upload', 'staging'],
            'related' => ['assets.upload', 'assets.processing'],
            'routes' => ['assets.staged'],
            'page_context' => ['Assets'],
            'priority' => 88,
            'in_common' => false,
            'common_sort' => 500,
        ],
        [
            'key' => 'assets.processing',
            'title' => 'See asset processing status',
            'aliases' => ['pipeline', 'thumbnails', 'derivatives', 'processing queue'],
            'category' => 'Assets',
            'short_answer' => 'Use the processing view to see what is still running or failed for your brand.',
            'steps' => [
                'Open Assets → Processing (active jobs / queue).',
                'Identify assets that are still processing or need attention.',
                'From an asset detail view you can often retry or inspect incidents when you have permission.',
            ],
            'route_name' => 'assets.processing',
            'route_bindings' => [],
            'page_label' => 'Asset processing',
            'permissions' => [],
            'tags' => ['processing', 'status', 'pipeline'],
            'related' => ['assets.browse', 'assets.upload'],
            'routes' => ['assets.processing'],
            'page_context' => ['Assets'],
            'priority' => 88,
            'in_common' => true,
            'common_sort' => 45,
        ],
        [
            'key' => 'collections.add_assets',
            'title' => 'Add assets to a collection',
            'aliases' => ['collection membership', 'put in collection'],
            'category' => 'Collections',
            'short_answer' => 'Collections group assets for sharing and campaigns; add assets from the collection or from an asset’s collections controls.',
            'steps' => [
                'Go to Collections and open the collection (or create one).',
                'Use Add assets / pick from the library, or from an asset use Collections to sync membership.',
                'Save changes; verify membership in the collection’s asset list.',
            ],
            'route_name' => 'collections.index',
            'route_bindings' => [],
            'deep_link' => [
                'route_name' => 'collections.index',
                'params' => [],
                'query' => [],
            ],
            'highlight' => [
                'selector' => 'collections-add-assets',
                'label' => 'Selection bar on a collection',
            ],
            'page_label' => 'Collections',
            'permissions' => [],
            'tags' => ['collections', 'organize'],
            'related' => ['collections.share', 'downloads.package'],
            'routes' => ['collections.index'],
            'page_context' => ['Collections'],
            'priority' => 86,
            'in_common' => true,
            'common_sort' => 50,
        ],
        [
            'key' => 'collections.manage',
            'title' => 'Create and manage collections',
            'aliases' => ['new collection', 'edit collection'],
            'category' => 'Collections',
            'short_answer' => 'Collections are managed from the Collections index: create, rename, configure access, and curate membership.',
            'steps' => [
                'Open Collections.',
                'Create a collection or select one to edit.',
                'Adjust settings, members, and linked assets as your role allows.',
            ],
            'route_name' => 'collections.index',
            'route_bindings' => [],
            'deep_link' => [
                'route_name' => 'collections.index',
                'params' => [],
                'query' => [],
            ],
            'highlight' => [
                'selector' => 'collections-create',
                'label' => 'Create collection',
            ],
            'page_label' => 'Collections',
            'permissions' => [],
            'tags' => ['collections', 'manage'],
            'related' => ['collections.add_assets', 'collections.share'],
            'routes' => ['collections.index'],
            'page_context' => ['Collections'],
            'priority' => 82,
            'in_common' => false,
            'common_sort' => 510,
        ],
        [
            'key' => 'collections.share',
            'title' => 'Share a collection',
            'aliases' => ['public link', 'guest access', 'share link'],
            'category' => 'Collections',
            'short_answer' => 'Generate or manage a share experience from the collection so external viewers can review or download within policy.',
            'steps' => [
                'Open Collections and select the collection.',
                'Use the share / public link or invite options in the collection UI.',
                'Copy the link or send instructions; respect download and password rules set by your admin.',
            ],
            'route_name' => 'collections.index',
            'route_bindings' => [],
            'page_label' => 'Collections',
            'permissions' => [],
            'tags' => ['share', 'link', 'guest'],
            'related' => ['collections.add_assets', 'downloads.package'],
            'routes' => ['collections.index'],
            'page_context' => ['Collections'],
            'priority' => 80,
            'in_common' => true,
            'common_sort' => 55,
        ],
        [
            'key' => 'downloads.package',
            'title' => 'Download assets (packaged downloads)',
            'aliases' => ['zip', 'export', 'bulk download'],
            'category' => 'Downloads',
            'short_answer' => 'Build a download from selected assets or a collection, then track status from Downloads.',
            'steps' => [
                'Add assets to your download bucket from the asset grid or asset actions where available.',
                'Create a download / package from the Downloads or bucket UI.',
                'Open Downloads to copy links, track processing, or re-send access.',
            ],
            'route_name' => 'downloads.index',
            'route_bindings' => [],
            'page_label' => 'Downloads',
            'permissions' => [],
            'tags' => ['download', 'export', 'zip'],
            'related' => ['assets.browse', 'collections.share'],
            'routes' => ['downloads.index'],
            'page_context' => ['Downloads'],
            'priority' => 84,
            'in_common' => true,
            'common_sort' => 60,
        ],
        [
            'key' => 'team.invite_company',
            'title' => 'Invite people to the company',
            'aliases' => ['add user', 'team invites', 'workspace members'],
            'category' => 'Team',
            'short_answer' => 'Company admins invite users from Team; they receive email to join the workspace.',
            'steps' => [
                'Open Company → Team.',
                'Click Invite and enter email and role.',
                'The invitee accepts, completes any signup steps, and can be granted brand access.',
            ],
            'route_name' => 'companies.team',
            'route_bindings' => [],
            'deep_link' => [
                'route_name' => 'companies.team',
                'params' => [],
                'query' => [],
            ],
            'highlight' => [
                'selector' => 'team-invite-member',
                'label' => 'Invite Member',
            ],
            'page_label' => 'Company team',
            'permissions' => ['team.manage'],
            'tags' => ['invite', 'users', 'rbac'],
            'related' => ['team.brand_roles', 'company.settings'],
            'in_common' => true,
            'common_sort' => 70,
        ],
        [
            'key' => 'team.brand_roles',
            'title' => 'Assign or change brand roles',
            'aliases' => ['brand access', 'role on brand', 'permissions'],
            'category' => 'Team',
            'short_answer' => 'From Company → Team, edit a member’s brand access and pick the right brand role.',
            'steps' => [
                'Go to Company → Team.',
                'Select a member.',
                'Add brand access or change their brand role; save changes.',
            ],
            'route_name' => 'companies.team',
            'route_bindings' => [],
            'page_label' => 'Company team',
            'permissions' => ['team.manage'],
            'tags' => ['roles', 'brands', 'access'],
            'related' => ['team.invite_company', 'brand.settings'],
            'in_common' => false,
            'common_sort' => 520,
        ],
        [
            'key' => 'workspace.switch_brand',
            'title' => 'Switch the active brand',
            'aliases' => ['change brand', 'brand picker'],
            'category' => 'Workspace',
            'short_answer' => 'Use the workspace / brand controls in the header or user menu to change which brand you are working in.',
            'steps' => [
                'Open the user or workspace menu (top right).',
                'Choose another brand you have access to.',
                'Confirm navigation refreshes to that brand’s library and settings.',
            ],
            'route_name' => 'insights.overview',
            'route_bindings' => [],
            'page_label' => 'Insights overview',
            'permissions' => [],
            'tags' => ['brand', 'context', 'navigation'],
            'related' => ['brand.settings', 'assets.browse'],
            'in_common' => true,
            'common_sort' => 25,
        ],
        [
            'key' => 'brand.settings',
            'title' => 'Manage brand settings',
            'aliases' => ['brand page', 'edit brand', 'colors', 'logo'],
            'category' => 'Brands',
            'short_answer' => 'Brand settings cover identity, defaults, and configuration for the active brand.',
            'steps' => [
                'Switch to the brand you need (if you have several).',
                'Open Brand settings from the navigation / workspace entry.',
                'Update identity, guidelines links, or other options your role allows, then save.',
            ],
            'route_name' => 'brands.edit',
            'route_bindings' => ['brand' => 'active_brand'],
            'deep_link' => [
                'route_name' => 'brands.edit',
                'params' => ['brand' => 'active_brand'],
                'query' => [],
            ],
            'highlight' => [
                'selector' => 'brand-settings-nav',
                'label' => 'Brand settings (Overview sidebar)',
            ],
            'page_label' => 'Brand settings',
            'permissions' => ['brand_settings.manage'],
            'tags' => ['brand', 'settings'],
            'related' => ['manage.categories_fields', 'approvals.queue'],
            'in_common' => true,
            'common_sort' => 80,
        ],
        [
            'key' => 'billing.plan',
            'title' => 'View billing and plan details',
            'aliases' => ['subscription', 'invoice', 'plan limits'],
            'category' => 'Billing',
            'short_answer' => 'Billing shows your subscription, usage-related add-ons, and links to invoices or the customer portal when enabled.',
            'steps' => [
                'Open Billing from the user menu (when you have access).',
                'Review current plan, seats, and add-ons.',
                'Use invoices or the customer portal links as needed.',
            ],
            'route_name' => 'billing',
            'route_bindings' => [],
            'page_label' => 'Billing',
            'permissions' => ['billing.view'],
            'tags' => ['billing', 'plan', 'stripe'],
            'related' => ['billing.upgrade', 'ai.credits_usage'],
            'in_common' => true,
            'common_sort' => 90,
        ],
        [
            'key' => 'billing.upgrade',
            'title' => 'Change or upgrade your plan',
            'aliases' => ['upgrade', 'plans', 'subscribe'],
            'category' => 'Billing',
            'short_answer' => 'Pick a new plan or adjust add-ons from the billing plans experience.',
            'steps' => [
                'Go to Billing → Plans (or the plans section within Billing).',
                'Compare plans and confirm checkout or upgrade steps.',
                'After purchase, verify features and limits on the overview.',
            ],
            'route_name' => 'billing.plans',
            'route_bindings' => [],
            'deep_link' => [
                'route_name' => 'billing.plans',
                'params' => [],
                'query' => [],
            ],
            'highlight' => [
                'selector' => 'billing-upgrade-plan',
                'label' => 'Plan upgrade button',
            ],
            'page_label' => 'Billing plans',
            'permissions' => ['billing.view'],
            'tags' => ['upgrade', 'subscription'],
            'related' => ['billing.plan'],
            'in_common' => false,
            'common_sort' => 530,
        ],
        [
            'key' => 'ai.credits_usage',
            'title' => 'View AI credits and feature usage',
            'aliases' => ['credits', 'usage', 'ai limits'],
            'category' => 'AI & insights',
            'short_answer' => 'Insights → Usage surfaces AI credit consumption and related usage context for your workspace when enabled.',
            'steps' => [
                'Open Insights from the navigation.',
                'Go to the Usage tab.',
                'Review credit usage, warnings, and per-feature breakdown when shown.',
            ],
            'route_name' => 'insights.usage',
            'route_bindings' => [],
            'page_label' => 'Insights — Usage',
            'permissions' => [],
            'tags' => ['ai', 'credits', 'usage'],
            'related' => ['ai.company_usage_panel', 'studio.generative'],
            'in_common' => true,
            'common_sort' => 100,
        ],
        [
            'key' => 'ai.company_usage_panel',
            'title' => 'Company AI usage (detailed)',
            'aliases' => ['ai usage report', 'tenant ai'],
            'category' => 'AI & insights',
            'short_answer' => 'Company settings includes an AI usage section for admins who can view detailed consumption.',
            'steps' => [
                'Open Company → Settings.',
                'Scroll to the AI usage / reporting section (requires permission).',
                'Adjust date range or export if your role supports it.',
            ],
            'route_name' => 'companies.settings',
            'route_bindings' => [],
            'page_label' => 'Company settings',
            'permissions' => ['ai.usage.view'],
            'tags' => ['ai', 'admin', 'reporting'],
            'related' => ['ai.credits_usage', 'company.settings'],
            'in_common' => false,
            'common_sort' => 540,
        ],
        [
            'key' => 'studio.generative',
            'title' => 'Use Studio / Generative creative tools',
            'aliases' => ['editor', 'compositions', 'creative', 'generate'],
            'category' => 'Studio',
            'short_answer' => 'Generative / Studio tools let you create compositions and variants when your company has the feature enabled.',
            'steps' => [
                'Open Generative / Studio from the navigation when visible.',
                'Pick or create a composition and follow the in-app workflow.',
                'Watch credit usage and export or promote results per your DAM policies.',
            ],
            'route_name' => 'generative.index',
            'route_bindings' => [],
            'page_label' => 'Generative',
            'permissions' => [],
            'tags' => ['studio', 'generative', 'creative'],
            'related' => ['ai.credits_usage', 'assets.browse'],
            'in_common' => true,
            'common_sort' => 110,
        ],
        [
            'key' => 'insights.ai_review',
            'title' => 'Review AI metadata and tag suggestions',
            'aliases' => ['suggestions', 'accept tags', 'review workspace'],
            'category' => 'AI & insights',
            'short_answer' => 'Insights → Review aggregates AI suggestions so you can accept or reject in bulk where permitted.',
            'steps' => [
                'Navigate to Insights → Review.',
                'Filter by suggestion type or brand as needed.',
                'Accept, edit-accept, or reject suggestions following your governance rules.',
            ],
            'route_name' => 'insights.review',
            'route_bindings' => [],
            'page_label' => 'Insights — Review',
            'permissions' => [],
            'tags' => ['ai', 'review', 'metadata'],
            'related' => ['assets.metadata_edit', 'approvals.queue'],
            'in_common' => true,
            'common_sort' => 120,
        ],
        [
            'key' => 'approvals.queue',
            'title' => 'Review contributor asset approvals',
            'aliases' => ['approve assets', 'pending approvals', 'submissions'],
            'category' => 'Approvals',
            'short_answer' => 'Approvers use the brand Approvals page to publish or reject submitted assets.',
            'steps' => [
                'Open Brand → Approvals (or the Approvals entry for your brand).',
                'Open a pending submission.',
                'Approve, reject with feedback, or request changes per workflow.',
            ],
            'route_name' => 'brands.approvals',
            'route_bindings' => ['brand' => 'active_brand'],
            'page_label' => 'Brand approvals',
            'permissions' => [],
            'tags' => ['approvals', 'governance'],
            'related' => ['insights.ai_review', 'assets.metadata_edit'],
            'in_common' => true,
            'common_sort' => 130,
        ],
        [
            'key' => 'manage.categories_fields',
            'title' => 'Manage categories, folders, and fields',
            'aliases' => ['taxonomy', 'folder structure', 'field visibility'],
            'category' => 'Manage',
            'short_answer' => 'Manage → Categories is the workspace for folder structure, fields, and related brand library configuration.',
            'steps' => [
                'Open Manage → Categories (or Structure as labeled in your build).',
                'Edit categories, reorder, or adjust field visibility for the active brand.',
                'Save and verify changes in the asset metadata experience.',
            ],
            'route_name' => 'manage.categories',
            'route_bindings' => [],
            'page_label' => 'Manage — Categories',
            'permissions' => ['brand_settings.manage'],
            'tags' => ['categories', 'fields', 'taxonomy'],
            'related' => ['manage.tags', 'manage.values'],
            'in_common' => false,
            'common_sort' => 550,
        ],
        [
            'key' => 'manage.tags',
            'title' => 'Manage tags',
            'aliases' => ['tag library', 'controlled vocabulary'],
            'category' => 'Manage',
            'short_answer' => 'Manage → Tags centralizes tag hygiene for the brand library.',
            'steps' => [
                'Go to Manage → Tags.',
                'Merge, rename, or purge tags according to policy.',
                'Confirm downstream assets reflect updates after operations complete.',
            ],
            'route_name' => 'manage.tags',
            'route_bindings' => [],
            'page_label' => 'Manage — Tags',
            'permissions' => ['brand_settings.manage'],
            'tags' => ['tags', 'taxonomy'],
            'related' => ['manage.categories_fields', 'manage.values'],
            'in_common' => false,
            'common_sort' => 560,
        ],
        [
            'key' => 'manage.values',
            'title' => 'Manage metadata values',
            'aliases' => ['allowed values', 'options', 'picklists'],
            'category' => 'Manage',
            'short_answer' => 'Manage → Values helps maintain allowed metadata values for structured fields.',
            'steps' => [
                'Open Manage → Values.',
                'Select a field or value group to edit.',
                'Add, rename, or retire values carefully to avoid breaking existing assets.',
            ],
            'route_name' => 'manage.values',
            'route_bindings' => [],
            'page_label' => 'Manage — Values',
            'permissions' => ['brand_settings.manage'],
            'tags' => ['metadata', 'values'],
            'related' => ['manage.categories_fields', 'tenant.metadata_fields'],
            'in_common' => false,
            'common_sort' => 570,
        ],
        [
            'key' => 'tenant.metadata_fields',
            'title' => 'Tenant custom metadata fields (admin)',
            'aliases' => ['custom fields', 'field definitions'],
            'category' => 'Admin',
            'short_answer' => 'Tenant-level custom fields are created by company admins or metadata admins; Manage covers most day-to-day field placement.',
            'steps' => [
                'Ensure you have tenant metadata field permissions.',
                'Use Company settings and metadata admin tools, or Manage → Fields for brand-facing configuration.',
                'Coordinate changes with library managers before altering production fields.',
            ],
            'route_name' => 'manage.fields',
            'route_bindings' => [],
            'page_label' => 'Manage — Fields',
            'permissions' => ['metadata.tenant.field.manage'],
            'tags' => ['metadata', 'tenant', 'admin'],
            'related' => ['manage.categories_fields', 'company.settings'],
            'in_common' => false,
            'common_sort' => 580,
        ],
        [
            'key' => 'support.open_ticket',
            'title' => 'Contact Jackpot support',
            'aliases' => ['help desk', 'ticket', 'issue'],
            'category' => 'Support',
            'short_answer' => 'Open a support ticket from the in-app Support section so your workspace context travels with the request.',
            'steps' => [
                'Go to Support → Tickets.',
                'Create a ticket with a clear subject and reproduction steps.',
                'Attach examples or links (non-secret) and watch for email replies.',
            ],
            'route_name' => 'support.tickets.index',
            'route_bindings' => [],
            'page_label' => 'Support tickets',
            'permissions' => [],
            'tags' => ['support', 'help'],
            'related' => ['account.profile', 'notifications.preferences'],
            'in_common' => true,
            'common_sort' => 140,
        ],
        [
            'key' => 'notifications.preferences',
            'title' => 'Notification preferences',
            'aliases' => ['email alerts', 'bell', 'push'],
            'category' => 'Account',
            'short_answer' => 'Use the notification bell for activity; tune delivery preferences from your profile / notification settings where available.',
            'steps' => [
                'Click the bell in the header for recent in-app notifications.',
                'Open Profile / account settings for email or channel preferences when exposed.',
                'Adjust categories you care about and save.',
            ],
            'route_name' => 'profile.index',
            'route_bindings' => [],
            'page_label' => 'Profile',
            'permissions' => [],
            'tags' => ['notifications', 'alerts'],
            'related' => ['support.open_ticket', 'account.profile'],
            'in_common' => true,
            'common_sort' => 150,
        ],
        [
            'key' => 'account.profile',
            'title' => 'Account profile and security',
            'aliases' => ['password', 'avatar', 'my account'],
            'category' => 'Account',
            'short_answer' => 'Profile holds your personal settings: name, avatar, password, and data export options.',
            'steps' => [
                'Choose Profile from the user menu.',
                'Update profile details or password.',
                'Review privacy / export tools if your organization allows self-service.',
            ],
            'route_name' => 'profile.index',
            'route_bindings' => [],
            'page_label' => 'Profile',
            'permissions' => [],
            'tags' => ['account', 'security', 'profile'],
            'related' => ['notifications.preferences', 'company.settings'],
            'in_common' => true,
            'common_sort' => 160,
        ],
        [
            'key' => 'company.settings',
            'title' => 'Company workspace settings',
            'aliases' => ['tenant settings', 'workspace admin'],
            'category' => 'Company',
            'short_answer' => 'Company settings cover workspace-wide options such as downloads policy, AI controls, and related admin surfaces.',
            'steps' => [
                'Open Company → Settings.',
                'Review each section you have access to.',
                'Apply changes deliberately—some affect all brands and users.',
            ],
            'route_name' => 'companies.settings',
            'route_bindings' => [],
            'page_label' => 'Company settings',
            'permissions' => ['company_settings.view'],
            'tags' => ['company', 'admin', 'settings'],
            'related' => ['team.invite_company', 'ai.company_usage_panel'],
            'in_common' => false,
            'common_sort' => 590,
        ],
    ],
];
