<?php

/**
 * Bundled Studio fonts (repo-shipped TTF/OTF under resources/fonts).
 *
 * @return array<string, array{label:string,family:string,weight:int,style:string,path:string,export_supported:bool,fallback_key?:string}>
 */
$b = static fn (string $rel): string => resource_path($rel);

return [
    'inter-regular' => [
        'label' => 'Inter',
        'family' => 'Inter',
        'weight' => 400,
        'style' => 'normal',
        'path' => $b('fonts/inter/Inter-Regular.ttf'),
        'export_supported' => true,
    ],
    'inter-bold' => [
        'label' => 'Inter',
        'family' => 'Inter',
        'weight' => 700,
        'style' => 'normal',
        'path' => $b('fonts/inter/Inter-Bold.ttf'),
        'export_supported' => true,
    ],
    'system-ui-regular' => [
        'label' => 'System UI',
        'family' => 'system-ui',
        'weight' => 400,
        'style' => 'normal',
        'path' => $b('fonts/inter/Inter-Regular.ttf'),
        'export_supported' => true,
        'fallback_key' => 'bundled:inter-regular',
    ],
    'roboto-regular' => [
        'label' => 'Roboto',
        'family' => 'Roboto',
        'weight' => 400,
        'style' => 'normal',
        'path' => $b('fonts/roboto/Roboto-Regular.ttf'),
        'export_supported' => true,
    ],
    'roboto-bold' => [
        'label' => 'Roboto',
        'family' => 'Roboto',
        'weight' => 700,
        'style' => 'normal',
        'path' => $b('fonts/roboto/Roboto-Bold.ttf'),
        'export_supported' => true,
    ],
    'open-sans-regular' => [
        'label' => 'Open Sans',
        'family' => 'Open Sans',
        'weight' => 400,
        'style' => 'normal',
        'path' => $b('fonts/opensans/OpenSans.ttf'),
        'export_supported' => true,
    ],
    'open-sans-bold' => [
        'label' => 'Open Sans',
        'family' => 'Open Sans',
        'weight' => 700,
        'style' => 'normal',
        'path' => $b('fonts/opensans/OpenSans-Bold.ttf'),
        'export_supported' => true,
    ],
    'lato-regular' => [
        'label' => 'Lato',
        'family' => 'Lato',
        'weight' => 400,
        'style' => 'normal',
        'path' => $b('fonts/lato/Lato-Regular.ttf'),
        'export_supported' => true,
    ],
    'lato-bold' => [
        'label' => 'Lato',
        'family' => 'Lato',
        'weight' => 700,
        'style' => 'normal',
        'path' => $b('fonts/lato/Lato-Bold.ttf'),
        'export_supported' => true,
    ],
    'montserrat-regular' => [
        'label' => 'Montserrat',
        'family' => 'Montserrat',
        'weight' => 400,
        'style' => 'normal',
        'path' => $b('fonts/montserrat/Montserrat.ttf'),
        'export_supported' => true,
    ],
    'montserrat-bold' => [
        'label' => 'Montserrat',
        'family' => 'Montserrat',
        'weight' => 700,
        'style' => 'normal',
        'path' => $b('fonts/montserrat/Montserrat-Bold.ttf'),
        'export_supported' => true,
    ],
    'poppins-regular' => [
        'label' => 'Poppins',
        'family' => 'Poppins',
        'weight' => 400,
        'style' => 'normal',
        'path' => $b('fonts/poppins/Poppins-Regular.ttf'),
        'export_supported' => true,
    ],
    'poppins-bold' => [
        'label' => 'Poppins',
        'family' => 'Poppins',
        'weight' => 700,
        'style' => 'normal',
        'path' => $b('fonts/poppins/Poppins-Bold.ttf'),
        'export_supported' => true,
    ],
    'raleway-regular' => [
        'label' => 'Raleway',
        'family' => 'Raleway',
        'weight' => 400,
        'style' => 'normal',
        'path' => $b('fonts/raleway/Raleway.ttf'),
        'export_supported' => true,
    ],
    'raleway-bold' => [
        'label' => 'Raleway',
        'family' => 'Raleway',
        'weight' => 700,
        'style' => 'normal',
        'path' => $b('fonts/raleway/Raleway-Bold.ttf'),
        'export_supported' => true,
    ],
    'merriweather-regular' => [
        'label' => 'Merriweather',
        'family' => 'Merriweather',
        'weight' => 400,
        'style' => 'normal',
        'path' => $b('fonts/merriweather/Merriweather.ttf'),
        'export_supported' => true,
    ],
    'merriweather-bold' => [
        'label' => 'Merriweather',
        'family' => 'Merriweather',
        'weight' => 700,
        'style' => 'normal',
        'path' => $b('fonts/merriweather/Merriweather-Bold.ttf'),
        'export_supported' => true,
    ],
    'playfair-display-regular' => [
        'label' => 'Playfair Display',
        'family' => 'Playfair Display',
        'weight' => 400,
        'style' => 'normal',
        'path' => $b('fonts/playfairdisplay/PlayfairDisplay.ttf'),
        'export_supported' => true,
    ],
    'playfair-display-bold' => [
        'label' => 'Playfair Display',
        'family' => 'Playfair Display',
        'weight' => 700,
        'style' => 'normal',
        'path' => $b('fonts/playfairdisplay/PlayfairDisplay-Bold.ttf'),
        'export_supported' => true,
    ],
    'oswald-regular' => [
        'label' => 'Oswald',
        'family' => 'Oswald',
        'weight' => 400,
        'style' => 'normal',
        'path' => $b('fonts/oswald/Oswald.ttf'),
        'export_supported' => true,
    ],
    'oswald-bold' => [
        'label' => 'Oswald',
        'family' => 'Oswald',
        'weight' => 700,
        'style' => 'normal',
        'path' => $b('fonts/oswald/Oswald-Bold.ttf'),
        'export_supported' => true,
    ],
    'source-sans-3-regular' => [
        'label' => 'Source Sans 3',
        'family' => 'Source Sans 3',
        'weight' => 400,
        'style' => 'normal',
        'path' => $b('fonts/sourcesans3/SourceSans3.ttf'),
        'export_supported' => true,
    ],
    'source-sans-3-bold' => [
        'label' => 'Source Sans 3',
        'family' => 'Source Sans 3',
        'weight' => 700,
        'style' => 'normal',
        'path' => $b('fonts/sourcesans3/SourceSans3-Bold.ttf'),
        'export_supported' => true,
    ],
    'source-serif-4-regular' => [
        'label' => 'Source Serif 4',
        'family' => 'Source Serif 4',
        'weight' => 400,
        'style' => 'normal',
        'path' => $b('fonts/sourceserif4/SourceSerif4.ttf'),
        'export_supported' => true,
    ],
    'source-serif-4-bold' => [
        'label' => 'Source Serif 4',
        'family' => 'Source Serif 4',
        'weight' => 700,
        'style' => 'normal',
        'path' => $b('fonts/sourceserif4/SourceSerif4-Bold.ttf'),
        'export_supported' => true,
    ],
    'noto-sans-regular' => [
        'label' => 'Noto Sans',
        'family' => 'Noto Sans',
        'weight' => 400,
        'style' => 'normal',
        'path' => $b('fonts/notosans/NotoSans.ttf'),
        'export_supported' => true,
    ],
    'noto-sans-bold' => [
        'label' => 'Noto Sans',
        'family' => 'Noto Sans',
        'weight' => 700,
        'style' => 'normal',
        'path' => $b('fonts/notosans/NotoSans-Bold.ttf'),
        'export_supported' => true,
    ],
    'noto-serif-regular' => [
        'label' => 'Noto Serif',
        'family' => 'Noto Serif',
        'weight' => 400,
        'style' => 'normal',
        'path' => $b('fonts/notoserif/NotoSerif.ttf'),
        'export_supported' => true,
    ],
    'noto-serif-bold' => [
        'label' => 'Noto Serif',
        'family' => 'Noto Serif',
        'weight' => 700,
        'style' => 'normal',
        'path' => $b('fonts/notoserif/NotoSerif-Bold.ttf'),
        'export_supported' => true,
    ],
    'ibm-plex-sans-regular' => [
        'label' => 'IBM Plex Sans',
        'family' => 'IBM Plex Sans',
        'weight' => 400,
        'style' => 'normal',
        'path' => $b('fonts/ibmplexsans/IBMPlexSans.ttf'),
        'export_supported' => true,
    ],
    'ibm-plex-sans-bold' => [
        'label' => 'IBM Plex Sans',
        'family' => 'IBM Plex Sans',
        'weight' => 700,
        'style' => 'normal',
        'path' => $b('fonts/ibmplexsans/IBMPlexSans-Bold.ttf'),
        'export_supported' => true,
    ],
    'ibm-plex-serif-regular' => [
        'label' => 'IBM Plex Serif',
        'family' => 'IBM Plex Serif',
        'weight' => 400,
        'style' => 'normal',
        'path' => $b('fonts/ibmplexserif/IBMPlexSerif-Regular.ttf'),
        'export_supported' => true,
    ],
    'ibm-plex-serif-bold' => [
        'label' => 'IBM Plex Serif',
        'family' => 'IBM Plex Serif',
        'weight' => 700,
        'style' => 'normal',
        'path' => $b('fonts/ibmplexserif/IBMPlexSerif-Bold.ttf'),
        'export_supported' => true,
    ],
    'georgia-regular' => [
        'label' => 'Georgia',
        'family' => 'Georgia',
        'weight' => 400,
        'style' => 'normal',
        'path' => $b('fonts/georgia/Georgia-Regular.ttf'),
        'export_supported' => true,
        'fallback_key' => 'bundled:inter-regular',
    ],
    'georgia-bold' => [
        'label' => 'Georgia',
        'family' => 'Georgia',
        'weight' => 700,
        'style' => 'normal',
        'path' => $b('fonts/georgia/Georgia-Bold.ttf'),
        'export_supported' => true,
    ],
];
