<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Vite Configuration
    |--------------------------------------------------------------------------
    |
    | Environment-based Vite asset handling:
    |
    | LOCAL (APP_ENV=local):
    |   - Uses Vite dev server (VITE_DEV_SERVER_URL)
    |   - Does NOT require manifest.json
    |   - Dev server must be running: npm run dev
    |
    | STAGING/PRODUCTION (APP_ENV=staging|production):
    |   - Requires built assets (public/build/manifest.json)
    |   - Manifest MUST exist or RuntimeException is thrown
    |   - Build assets: npm run build
    |
    | The @vite() directive in Blade templates automatically uses:
    |   - Dev server when APP_ENV=local and manifest missing
    |   - Manifest file when it exists (or in non-local environments)
    |
    */

    /**
     * The base URL for the Vite dev server.
     * Only used when APP_ENV=local.
     *
     * Set this in your .env file:
     * VITE_DEV_SERVER_URL=http://localhost:5173
     */
    'dev_server_url' => env('VITE_DEV_SERVER_URL', 'http://localhost:5173'),

    /*
    |--------------------------------------------------------------------------
    | Manifest Path
    |--------------------------------------------------------------------------
    |
    | The path to the "manifest" file that contains a list of all assets.
    | This file is generated by Vite when running `npm run build`.
    |
    | In local environment, this is optional (dev server is used).
    | In staging/production, this file MUST exist or an exception will be thrown
    | during application boot (see AppServiceProvider::validateViteManifest()).
    |
    */
    'manifest' => public_path('build/manifest.json'),

];
