<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

/**
 * Asset Embedding
 *
 * Stores embedding vectors for assets used in imagery similarity scoring.
 * Vectors are generated by GenerateAssetEmbeddingJob.
 */
class AssetEmbedding extends Model
{
    protected $fillable = [
        'asset_id',
        'embedding_vector',
        'model',
    ];

    protected function casts(): array
    {
        return [
            'embedding_vector' => 'array',
        ];
    }

    public function asset(): BelongsTo
    {
        return $this->belongsTo(Asset::class);
    }
}
