import LegalPage, { LegalSection, LegalParagraph, LegalList } from '../../Components/Legal/LegalPage'

/**
 * Accessibility Statement for Jackpot Brand Asset Management, LLC.
 *
 * Drafting posture (per product direction): aspirational language only. No commitments to
 * conform to any specific standard, no dates, no warranties of accessibility. Positions
 * Jackpot as actively working on accessibility while preserving maximum flexibility to
 * change scope, standards, remediation timing, and priorities. Third-party content and
 * Customer-uploaded material are expressly excluded. Users are invited to report issues.
 *
 * This file is a template, not legal advice.
 */
export default function Accessibility() {
    return (
        <LegalPage title="Accessibility Statement" effectiveDate="April 18, 2026">
            <LegalParagraph>
                Jackpot Brand Asset Management, LLC ("Jackpot," "we," "us," or "our") believes that digital
                experiences should be usable by as many people as reasonably possible. This statement describes
                our general approach to accessibility for the Jackpot website and platform (together, the
                <strong> "Services"</strong>). It is provided for informational purposes only and is not a
                warranty, guarantee, representation, or binding commitment of any kind.
            </LegalParagraph>

            <LegalSection id="approach" number="1" title="Our General Approach">
                <LegalParagraph>
                    We aim, where reasonably practicable and consistent with our product priorities, to design
                    and build the Services with accessibility in mind. Our development teams consult
                    industry-recognized guidance, including the Web Content Accessibility Guidelines (WCAG)
                    published by the World Wide Web Consortium, as one input among many. We do not represent
                    that the Services conform, or will at any time conform, to any particular version or level
                    of WCAG or to any other specific standard. Accessibility is an ongoing and evolving effort,
                    and conditions, standards, technologies, and our implementation of them change over time.
                </LegalParagraph>
            </LegalSection>

            <LegalSection id="scope" number="2" title="Scope and Limitations">
                <LegalParagraph>
                    This statement, to the extent it applies at all, applies only to the pages and features of
                    the Services that are owned and operated directly by Jackpot. The following, without
                    limitation, are expressly excluded:
                </LegalParagraph>
                <LegalList
                    items={[
                        'content uploaded, created, posted, linked, or generated by customers, their authorized users, agencies, brand portal visitors, or any other third party, including assets, logos, text, images, video, audio, and metadata;',
                        'AI-generated or AI-assisted output, which is non-deterministic and may vary from request to request;',
                        'third-party services, integrations, libraries, fonts, widgets, model providers, payment processors, content-delivery networks, hosting infrastructure, email providers, or any external website to which the Services may link or embed;',
                        'legacy pages, internal tools, experimental or beta features, and pages served from partners, resellers, or white-label deployments;',
                        'assistive technologies or browser, operating-system, or device configurations not tested by Jackpot;',
                        'any offline document, downloadable asset, PDF, ZIP archive, or other exported file, even if generated by the Services;',
                        'issues caused by network conditions, user configurations, browser extensions, content blockers, or conflicts with other installed software.',
                    ]}
                />
                <LegalParagraph>
                    Jackpot reserves the right to determine, in its sole discretion, what portions of the
                    Services are in scope, the priority in which accessibility matters are addressed, and what,
                    if any, remediation is undertaken.
                </LegalParagraph>
            </LegalSection>

            <LegalSection id="ongoing" number="3" title="Ongoing Effort">
                <LegalParagraph>
                    We work on accessibility on a continuing and best-effort basis alongside other product,
                    security, reliability, and business priorities. We do not commit to any timeline, milestone,
                    audit cadence, certification, attestation, or any specific remediation of any specific
                    issue. The Services are updated frequently; a feature available or behaving in a particular
                    way on one date may be modified, removed, or replaced on another date without notice.
                </LegalParagraph>
            </LegalSection>

            <LegalSection id="no-warranty" number="4" title="No Warranty">
                <LegalParagraph>
                    TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, THE SERVICES AND THIS STATEMENT ARE
                    PROVIDED <strong>"AS IS"</strong> AND <strong>"AS AVAILABLE,"</strong> WITHOUT ANY
                    REPRESENTATION OR WARRANTY THAT THE SERVICES ARE OR WILL BE ACCESSIBLE, USABLE, OR SUITABLE
                    FOR ANY PARTICULAR INDIVIDUAL, DEVICE, ASSISTIVE TECHNOLOGY, ENVIRONMENT, CONTEXT, OR
                    PURPOSE, OR THAT THEY WILL CONFORM TO ANY ACCESSIBILITY STANDARD, GUIDELINE, BEST PRACTICE,
                    OR APPLICABLE LAW. NOTHING IN THIS STATEMENT CREATES ANY OBLIGATION, LEGAL DUTY, OR
                    ENFORCEABLE COMMITMENT ON THE PART OF JACKPOT, AND THIS STATEMENT IS SUBJECT IN ALL RESPECTS
                    TO THE DISCLAIMERS AND LIMITATIONS SET FORTH IN THE JACKPOT{' '}
                    <a href="/terms" className="text-white hover:underline">Terms of Service</a>.
                </LegalParagraph>
            </LegalSection>

            <LegalSection id="feedback" number="5" title="Feedback and Accommodations">
                <LegalParagraph>
                    If you encounter a barrier that limits your ability to use the Services, or if you would
                    like to request information or an alternative means of access, please contact us at{' '}
                    <a href="mailto:support@jackpotbam.com" className="text-white hover:underline">
                        support@jackpotbam.com
                    </a>
                    . Please include a description of the issue, the page or feature involved, the browser and
                    operating system you are using, and any assistive technology you have configured. We will
                    review reports in the ordinary course of business and may, at our discretion and on a
                    best-effort basis, respond, investigate, provide information, or adjust the Services. We do
                    not commit to a response time, to any particular remedy, or to any accommodation. All
                    feedback is provided on a non-confidential basis and is subject to the feedback license in
                    our Terms of Service.
                </LegalParagraph>
            </LegalSection>

            <LegalSection id="changes" number="6" title="Changes to This Statement">
                <LegalParagraph>
                    We may revise, replace, or withdraw this statement at any time and for any reason, in our
                    sole discretion, without notice. The most current version will be available at this URL.
                    Any interpretive questions about this statement will be resolved in Jackpot's favor.
                </LegalParagraph>
            </LegalSection>

            <LegalSection id="contact" number="7" title="Contact">
                <LegalParagraph>
                    Accessibility-related inquiries:{' '}
                    <a href="mailto:support@jackpotbam.com" className="text-white hover:underline">
                        support@jackpotbam.com
                    </a>
                    .
                </LegalParagraph>
            </LegalSection>

            <div className="mt-16 rounded-xl border border-white/[0.06] bg-white/[0.02] p-6 text-xs text-white/45">
                <p>
                    This statement is provided for informational purposes only, does not constitute legal
                    advice, and is not a substitute for an accessibility audit, a formal accessibility
                    conformance report (such as a VPAT), or any contractual accessibility commitment, none of
                    which are granted by this statement or by any use of the Services.
                </p>
            </div>
        </LegalPage>
    )
}
